// application/uiGateway.js
// Contrat unique entre l'interface et l'application.

function interactivePayload(session, extra = {}) {
    const step = session?.step || null;
    return { interactive: true, interactiveStep: step, interactiveDecision: step?.kind === 'decision' ? session?.decision || null : null, interactiveEvent: extra.event || null, matchImportance: extra.matchImportance || session?.importance || null, playerSelection: extra.playerSelection || session?.match?.playerSelection || null };
}
export class UIGateway {
    constructor({ application, engine } = {}) { if (!application) throw new Error('UIGateway requires a GameApplication.'); this.application = application; this.engine = engine || application.engine; }
    get state() { return this.engine?.state || this.application.state || null; }
    startCareer(selectedData = {}) { const state = this.application.registry?.careerApplication?.create?.(selectedData); if (state) this.engine.state = state; return state; }
    playBlock(choice = null) { return this.application.registry?.blockSystem?.execute?.(this.state, choice) ?? null; }
    playNextBlock(choice = null) {
        const state = this.state; if (!state?.player) return null; const active = state.activeMatchSession;
        if (active) { const result = this.advanceInteractiveMatch(choice); if (!result.finished) return interactivePayload(result.session, { event: result.event }); }
        const next = this.getNextPlayableMatch();
        if (next) { const fixture = this.withComputedImportance(next); fixture.playerSelection = next.selection || null; fixture.minutes = next.selection?.minutes || 90; const session = this.startInteractiveMatch(fixture, next.matchIndex); return interactivePayload(session, { matchImportance: next.importance || null, playerSelection: next.selection || null }); }
        return this.completeInteractiveBlock();
    }
    advanceCalendar() { return this.application.registry?.calendarSystem?.advance?.(this.state) ?? null; }
    setTrainingFocus(focusKey) { const training=this.application.registry?.trainingSystem;if(!training?.isValidFocus?.(focusKey)||!this.state?.player)return false;this.state.trainingFocus=focusKey;this.application.registry.blockSystem.stateManager.save(this.state);return true; }
    shouldTriggerMatchDilemma(){if(this.state?.activeMatchSession)return true;return Boolean(!this.state?.player?.isInjured&&this.getNextPlayableMatch());}
    getMatchDilemma(type='standard',opponent="l'adversaire"){const state=this.state;if(!state?.activeMatchSession){const next=this.getNextPlayableMatch();if(next){const fixture=this.withComputedImportance(next);fixture.playerSelection=next.selection||null;fixture.minutes=next.selection?.minutes||90;this.startInteractiveMatch(fixture,next.matchIndex);}}return state?.activeMatchSession?.decision||this.application.registry?.matchChoiceManager?.getMatchDilemma?.(type,opponent)||null;}
    resolveEventChoice(i){return this.application.registry?.interactionSystem?.resolveEventChoice?.(this.state,i)??null;} resolveCoachChoice(i){return this.application.registry?.interactionSystem?.resolveCoachChoice?.(this.state,i)??null;} resolveMediaDilemma(i){return this.application.registry?.interactionSystem?.resolveMediaChoice?.(this.state,i)??null;} resolvePositionProposal(a){return this.application.registry?.interactionSystem?.resolvePositionProposal?.(this.state,a)??null;} acceptTransferOffer(){return this.application.registry?.transferSystem?.accept?.(this.state)??null;} rejectTransferOffer(){return this.application.registry?.transferSystem?.reject?.(this.state)??false;} retireCareer(){return this.application.registry?.careerLifecycleSystem?.retire?.(this.state)??null;} resetCareer(){const result=this.application.registry?.careerLifecycleSystem?.reset?.();this.engine.state=null;return result;} getPeriodName(month){return this.application.registry?.calendarSystem?.getPeriodName?.(month)??'';}
    getScheduledMatches(){try{const plan=this.application.registry?.competitionSystem?.getBlockPlan?.(this.state);return Array.isArray(plan?.scheduledMatches)?plan.scheduledMatches:[];}catch{return[];}}
    getSquadSelectionPlan(){const state=this.state;if(!state?.player)return{key:null,status:'Hors groupe',score:0,entries:[]};const matches=this.getScheduledMatches(),system=this.application.registry?.squadSelectionSystem;return system?.getPlan?.(state,matches)||{key:null,status:'Titulaire',score:50,entries:matches.map((fixture,matchIndex)=>({matchIndex,fixture,appearance:'starter',selected:true,started:true,minutes:90}))};}
    getMatchInteractionPlan(){const state=this.state;if(!state?.player)return{key:null,budget:0,playableCount:0,entries:[]};const matches=this.getScheduledMatches(),key=`${state.calendar?.currentSeasonYear??state.season??'season'}:${state.calendar?.currentMonth??'month'}:${matches.length}`,selectionPlan=this.getSquadSelectionPlan(),cached=state.matchInteractionPlan;if(cached?.key===key&&Array.isArray(cached.entries))return{...cached,entries:cached.entries.map(entry=>({...entry,fixture:matches[entry.matchIndex]||null,selection:selectionPlan.entries.find(item=>Number(item.matchIndex)===Number(entry.matchIndex))||null}))};const planner=this.application.registry?.matchImportanceSystem,planned=planner?.planBlock?.(state,matches)||{key,budget:0,playableCount:0,entries:[]};const entries=(planned.entries||[]).map(entry=>{const selection=selectionPlan.entries.find(item=>Number(item.matchIndex)===Number(entry.matchIndex))||null;return{...entry,playable:Boolean(entry.playable&&selection?.selected),selection};});const serializable={key,budget:planned.budget||0,playableCount:entries.filter(entry=>entry.playable).length,entries:entries.map(({fixture,selection,...entry})=>({...entry,selection:selection?{...selection,fixture:undefined}:null}))};state.matchInteractionPlan=serializable;return{...serializable,entries:entries.map(entry=>({...entry,fixture:matches[entry.matchIndex]||null}))};}
    getNextPlayableMatch(){const plan=this.getMatchInteractionPlan(),completed=new Set((Array.isArray(this.state?.interactiveBlockResults)?this.state.interactiveBlockResults:[]).map(result=>Number(result?.matchIndex)).filter(Number.isFinite));return plan.entries.find(entry=>entry.playable&&entry.fixture&&entry.selection?.selected&&!completed.has(Number(entry.matchIndex)))||null;}
    withComputedImportance(entry){if(!entry?.fixture)return entry?.fixture||null;return{...entry.fixture,importance:entry.importance?.level||entry.fixture.importance,importanceScore:entry.importance?.score??entry.fixture.importanceScore,importanceReasons:entry.importance?.reasons||entry.fixture.importanceReasons||[]};}
    startInteractiveMatch(match,index=0){const manager=this.application.registry?.interactiveMatchSystem,session=manager?.startInteractiveMatch?.(this.state,match,index);if(session)this.state.activeMatchSession=session;return session;}
    resolveInteractiveMatchDecision(choiceIndex){return this.advanceInteractiveMatch(choiceIndex);}
    advanceInteractiveMatch(choice=null){const manager=this.application.registry?.interactiveMatchSystem,session=this.state?.activeMatchSession;if(!manager||!session)throw new Error('Aucun match interactif actif.');const timedOut=Boolean(choice&&typeof choice==='object'&&choice.timedOut===true),choices=session.decision?.choices||[];const choiceIndex=session.step?.kind!=='decision'||timedOut?null:typeof choice==='number'?choice:choices.findIndex(item=>item===choice||item?.text===choice?.text||item?.texte===choice?.texte);const normalizedChoiceIndex=Number.isInteger(choiceIndex)&&choiceIndex>=0?choiceIndex:null;const result=manager.advanceInteractiveMatch?manager.advanceInteractiveMatch(this.state,session,{choiceIndex:normalizedChoiceIndex,timedOut}):manager.resolveInteractiveDecision(this.state,session,normalizedChoiceIndex);if(result.finished){manager.commitInteractiveResult(this.state,result.result);this.state.interactiveBlockResults||=[];this.state.interactiveBlockResults.push({...result.result,fixture:session.match,interactive:true,playerSelection:session.match?.playerSelection||null,minutesPlayed:session.match?.minutes||90,started:session.match?.playerSelection?.started??true});this.state.activeMatchSession=null;}else this.state.activeMatchSession=result.session;return result;}
    completeInteractiveBlock(){return this.application.registry?.blockSystem?.execute?.(this.state)??null;} getSuccessorOptions(playerId=this.state?.player?.id,currentAge=this.state?.player?.age){return this.application.registry?.generationSimulationFacade?.getOptions?.({state:this.state,playerId,currentAge})||[];} simulateChildTo14(childId,playerId=this.state?.player?.id){const result=this.application.registry?.generationSimulationFacade?.simulateTo14?.({state:this.state,playerId,childId,currentAge:this.state?.player?.age,world:this.state?.world||{}});this.application.registry?.blockSystem?.stateManager?.save?.(this.state);return result;} startSuccessorCareer(childId,playerId=this.state?.player?.id){const result=this.application.registry?.generationSimulationFacade?.startIfReady?.({state:this.state,playerId,childId,currentAge:this.state?.player?.age,world:this.state?.world||{}});if(result)this.application.registry?.blockSystem?.stateManager?.save?.(this.state);return result;}
}
export default UIGateway;
