// Compose les scènes de fin de match à partir des faits déjà validés.
// Une phrase décrivant un match ne peut jamais emprunter les statistiques d'un autre match du bloc.

import { impactLevel } from './narrativeSignificance.js';
import { stableNarrativeId } from './narrativeFactNormalizer.js';

const n=value=>Number.isFinite(Number(value))?Number(value):0;
const finite=value=>Number.isFinite(Number(value))?Number(value):null;

function resultView(fact={}){const metrics=fact.metrics||{},payload=fact.payload||{};return{factId:fact.id,fixture:payload.fixture||{},matchIndex:metrics.matchIndex,opponent:payload.opponent||'Adversaire',competitionName:payload.competitionName||'Match',result:fact.outcome?.result||null,teamGoals:n(metrics.teamGoals),opponentGoals:n(metrics.opponentGoals),rating:metrics.rating===null?null:n(metrics.rating),goals:n(metrics.goals),assists:n(metrics.assists),playerPlayed:metrics.playerPlayed!==false,started:metrics.started!==false,minutesPlayed:n(metrics.minutesPlayed),interactive:Boolean(metrics.interactive),appearance:payload.appearance||(metrics.started===false?'substitute':'starter')};}
function scoreText(result){return`${n(result?.teamGoals)}-${n(result?.opponentGoals)}`;}
function appearanceLabel(result={}){if(result.playerPlayed===false)return result.appearance==='bench'?'Resté sur le banc':'Hors groupe';if(result.started===false)return`Entré en jeu · ${n(result.minutesPlayed)} min`;if(n(result.minutesPlayed))return`Titulaire · ${n(result.minutesPlayed)} min`;return'Titulaire';}
function impactLabel(level){return{decisive:'Impact décisif',strong:'Impact fort',present:'Présent',difficult:'En difficulté',unused:'Non utilisé'}[level]||'Présent';}
function impactDetail(result={}){if(result.playerPlayed===false)return appearanceLabel(result);const parts=[],goals=n(result.goals),assists=n(result.assists),rating=n(result.rating);if(goals)parts.push(`${goals} but${goals>1?'s':''}`);if(assists)parts.push(`${assists} passe${assists>1?'s':''} décisive${assists>1?'s':''}`);if(rating>0)parts.push(`note ${rating.toFixed(1)}`);return parts.join(' · ');}
function goalHaulLabel(goals){return{2:'un doublé',3:'un triplé',4:'un quadruplé',5:'un quintuplé',6:'un sextuplé'}[goals]||`${goals} buts`;}
function performanceText(result){if(!result)return null;if(result.playerPlayed===false)return result.appearance==='bench'?'Tu as suivi toute la rencontre depuis le banc sans que ton numéro soit appelé.':'Cette fois, tu n’étais pas dans le groupe.';const rating=n(result.rating),goals=n(result.goals),assists=n(result.assists);if(result.started===false&&(goals||assists))return`Tu entres en cours de match et réussis à laisser une trace : ${goals?`${goals} but${goals>1?'s':''}`:''}${goals&&assists?' et ':''}${assists?`${assists} passe${assists>1?'s':''} décisive${assists>1?'s':''}`:''}.`;if(goals>=3)return`Tu quittes le terrain avec ${goalHaulLabel(goals)}. À chaque retour au rond central, le match te redonne encore une occasion d’y laisser ta marque — et tu recommences.`;if(goals===2)return`Deux buts, deux moments différents. Au deuxième, tes coéquipiers viennent te chercher avant même que tu aies le temps de réaliser : ton doublé a vraiment fait basculer la rencontre.`;if(goals===1&&assists>=1)return`Un but et une passe décisive : sur ce match, tu as pesé de deux façons différentes.`;if(goals===1)return`Ton but devient le moment personnel le plus net de cette rencontre.`;if(assists>=2)return`Tes ${assists} passes décisives racontent mieux ton influence sur ce match que n’importe quel résumé général.`;if(assists===1)return`Ta passe décisive a directement changé une séquence de cette rencontre.`;if(rating>=8.2)return`Sans statistique décisive, tu as pourtant imposé ta présence pendant presque tout le match.`;if(rating<5.5)return`Tu quittes le terrain avec une sensation claire : cette fois, tu es passé à côté.`;return`Tu as tenu ton rôle sans geste décisif. Le match ne devient pas mémorable pour autant, mais il compte dans la continuité.`;}
function outcomeText(result){if(result?.result==='win')return`Le coup de sifflet confirme la victoire ${scoreText(result)}.`;if(result?.result==='loss')return`Le match s’achève sur une défaite ${scoreText(result)}.`;return`Le score reste bloqué à ${scoreText(result)} au coup de sifflet.`;}
function blockOverviewText(results){if(results.length<=1)return null;const played=results.filter(item=>item.playerPlayed!==false);if(!played.length)return`Tu n’as pas été utilisé sur cette séquence. La prochaine occasion aura forcément plus de poids.`;const statuses=played.map(item=>item.started!==false?'starter':'substitute');const changed=statuses.some((status,index)=>index>0&&status!==statuses[index-1]);if(!changed)return null;return`Ton statut a réellement bougé dans cette période : tu passes du onze au banc, ou l’inverse. Cette fois, la hiérarchie change assez pour mériter d’être racontée.`;}
function atmosphereText(result,context={}){const age=n(context?.player?.age),competition=String(result?.competitionName||'').toLowerCase(),youth=(age&&age<19)||/u ?1[5678]|formation|academy|jeune/.test(competition);if(youth){if(result?.result==='win')return`Au bord du terrain, les proches et les éducateurs continuent de parler pendant que les joueurs récupèrent leurs affaires.`;if(result?.result==='loss')return`Les joueurs récupèrent leurs sacs plus lentement. Les proches restent près de la ligne pendant que chacun encaisse le résultat à sa manière.`;return`Les joueurs se regroupent près des bancs pendant que les familles attendent un peu plus loin.`;}if(result?.result==='win')return`Les réactions accompagnent encore les joueurs qui quittent la pelouse.`;if(result?.result==='loss')return`Le bruit autour de toi paraît plus lointain au moment de rentrer.`;return`Les joueurs se dispersent lentement pendant que l’enceinte retrouve son rythme normal.`;}
function firstCareerGoalMatch(context,results=[]){const seasonGoals=finite(context?.player?.seasonStats?.goals),previousGoals=finite(context?.career?.completedGoals);if(seasonGoals===null||previousGoals===null||previousGoals!==0)return null;const played=results.filter(result=>result.playerPlayed!==false),blockGoals=played.reduce((sum,result)=>sum+n(result.goals),0);if(blockGoals<=0||seasonGoals!==blockGoals)return null;return played.filter(result=>n(result.goals)>0).sort((a,b)=>n(a.matchIndex)-n(b.matchIndex))[0]?.factId||null;}
function mindsetText(context,result,{firstCareerGoal=false}={}){
    if(!result)return null;
    const morale=finite(context?.player?.mindset?.morale??context?.player?.morale),rating=result.rating===null?null:n(result.rating),contribution=n(result.goals)+n(result.assists);
    if(firstCareerGoal)return result.result==='loss'
        ?'La défaite prend presque toute la place. Presque. Au milieu de la frustration, une chose reste à toi : c’était le premier.'
        :'Tu peux rejouer l’action autant que tu veux : une chose restera différente pour toujours. C’était le premier but de ta carrière.';
    if(result.playerPlayed===false&&morale!==null&&morale<=35)return`Regarder le match avancer sans toi laisse une question difficile à chasser : comment reprendre ta place ?`;
    if(result.started===false&&(contribution>0||(rating!==null&&rating>=7.3))){
        const minutes=result.minutesPlayed?`${result.minutesPlayed} minutes`:'peu de temps';
        return`Tu n’avais que ${minutes} pour entrer dans l’histoire du match. En quittant le terrain, tu sais que tu as utilisé cette fenêtre au lieu de simplement la traverser.`;
    }
    if(result.result==='loss'&&(contribution>0||(rating!==null&&rating>=7.5))){
        return`Ta prestation tient debout, et c’est presque ce qui rend la soirée plus frustrante. Tu peux savoir que tu as répondu présent et sentir malgré tout que le résultat a avalé le reste.`;
    }
    if(rating!==null&&rating<5.5){
        if(morale!==null&&morale<=35)return`Tu sais déjà quelles erreurs vont revenir dans ta tête. Dans une période où la confiance est fragile, la seule réponse utile commence à la prochaine séance.`;
        return`Tu sais déjà quelles actions vont revenir dans ta tête. La réponse utile commencera à la prochaine séance.`;
    }
    if(result.result==='win'&&rating>=7.8)return`En rentrant, tu sens surtout une chose : ce match peut changer légèrement la manière dont le coach te regardera demain.`;
    return null;
}
function titleFor(result,matchCount,firstCareerGoal){if(firstCareerGoal)return'Le premier restera à part';if(matchCount>1)return'Ce que cette séquence change';if(result?.result==='win')return'Le travail est fait';if(result?.result==='loss')return'Une soirée à digérer';return'Un match qui laisse des questions';}
function toneFor(result){if(result?.result==='win')return n(result.rating)>=7.5?'triumph':'relief';if(result?.result==='loss')return n(result.rating)>=7?'bittersweet':'disappointment';return'reflection';}
function recap(facts,featuredFact,evaluations){return facts.map(fact=>{const result=resultView(fact),level=evaluations.get(fact.id)?.impactLevel||impactLevel(fact);return{matchIndex:result.matchIndex,opponent:result.opponent,competition:result.competitionName,score:scoreText(result),result:result.result,rating:result.playerPlayed===false?null:n(result.rating),goals:n(result.goals),assists:n(result.assists),interactive:result.interactive,playerPlayed:result.playerPlayed,started:result.started,appearance:result.appearance,minutesPlayed:result.minutesPlayed,appearanceLabel:appearanceLabel(result),impactLevel:level,impactLabel:impactLabel(level),impactDetail:impactDetail(result),isNarrativeFocus:fact.id===featuredFact.id,isImpactMatch:fact.id===featuredFact.id};});}

export class NarrativeBeatComposer{
 compose({plan,context,memory}={}){
   if(!plan?.primary?.featuredFact||!context?.player)return{primaryScene:null,callbackCommands:[]};
   const{featuredFact,facts,evaluation,evaluations,arc}=plan.primary,results=facts.map(resultView),featured=resultView(featuredFact),importance=evaluation?.importance||'normal',firstGoalFactId=firstCareerGoalMatch(context,results),firstCareerGoal=Boolean(firstGoalFactId&&featured.factId===firstGoalFactId),overview=blockOverviewText(results),mind=mindsetText(context,featured,{firstCareerGoal}),callback=memory?.callbacksByFactId?.[featuredFact.id]||null,continuity=memory?.continuityByFactId?.[featuredFact.id]||null,beats=[];
   const add=beat=>{const text=String(beat?.text||'').trim();if(!text)return;if(beats.some(existing=>String(existing.text||'').trim().toLowerCase()===text.toLowerCase()))return;beats.push({...beat,key:`${featuredFact.id}:${beat.kind}`});};
   if(overview)add({kind:'block-overview',text:overview,delay:700,emphasis:true});
   add({kind:'result',text:outcomeText(featured),delay:850,emphasis:true});
   add({kind:'player',text:performanceText(featured),delay:900});
   if(mind)add({kind:'player-mindset',text:mind,delay:1000,intimate:true,emphasis:firstCareerGoal});
   add({kind:'atmosphere',text:atmosphereText(featured,context),delay:750});
   if(callback)add({kind:'memory',text:callback.text,delay:1050,callback:true});else if(continuity)add({kind:'continuity',text:continuity,delay:950});
   const scene={id:stableNarrativeId('narrative_match',featuredFact.id),type:'match.end',importance,tone:toneFor(featured),title:titleFor(featured,results.length,firstCareerGoal),subtitle:results.length>1?`Séquence de championnat · ${results.filter(item=>item.playerPlayed!==false).length} apparition${results.filter(item=>item.playerPlayed!==false).length>1?'s':''}`:`${featured.competitionName} · ${featured.opponent}`,matchIndex:featured.matchIndex,impactMatchIndex:featured.matchIndex,interactive:featured.interactive,matches:recap(facts,featuredFact,evaluations),beats,arc,narrativeSeed:context.seed,sourceFactIds:facts.map(fact=>fact.id),facts:{matchCount:results.length,appearances:results.filter(item=>item.playerPlayed!==false).length,result:featured.result,score:scoreText(featured),rating:featured.playerPlayed?n(featured.rating):0,goals:n(featured.goals),assists:n(featured.assists),firstCareerGoal}};
   const callbackCommands=callback?[{id:stableNarrativeId('callback',{memoryId:callback.memoryId,factId:featuredFact.id}),action:'record',memoryId:callback.memoryId,factId:featuredFact.id,sceneId:scene.id,occurredAt:featuredFact.occurredAt}]:[];
   return{primaryScene:scene,callbackCommands};
 }
}
export default NarrativeBeatComposer;
