// Street to Pro — voix intérieure brute / instinctive.
// Réactions très courtes : jurons, fragments, impulsions. Elles ne doivent pas remplacer les pensées profondes.

const raw = (id, text, family, tags = [], intensity = 1) => ({
  id, text, family, tags, intensity, depth: 'raw', raw: true, unique: false
});

export const PLAYER_INNER_VOICE_RAW = [
  // 1. Colère / frustration brute
  raw('raw_frustration_001','Fait chier !','raw_frustration',['match','frustration'],2),
  raw('raw_frustration_002','Putain, je l’ai encore perdu.','raw_frustration',['match','turnover','repeat'],2),
  raw('raw_frustration_003','Non mais sérieux ?!','raw_frustration',['match','frustration','surprise'],2),
  raw('raw_frustration_004','Merde, merde, merde.','raw_frustration',['match','frustration'],2),
  raw('raw_frustration_005','N’importe quoi ce ballon.','raw_frustration',['match','bad_touch'],2),
  raw('raw_frustration_006','Putain de touche.','raw_frustration',['match','bad_touch'],2),
  raw('raw_frustration_007','Ça m’énerve grave.','raw_frustration',['match','frustration'],2),
  raw('raw_frustration_008','Toujours moi.','raw_frustration',['match','frustration','self_blame'],2),
  raw('raw_frustration_009','Rah, c’est pas vrai.','raw_frustration',['match','frustration'],1),
  raw('raw_frustration_010','Putain, qu’est-ce que je fous ?','raw_frustration',['match','self_blame'],3),
  raw('raw_frustration_011','Bordel de contrôle.','raw_frustration',['match','bad_touch'],2),
  raw('raw_frustration_012','Encore raté, putain.','raw_frustration',['match','miss','repeat'],3),
  raw('raw_frustration_013','Ça sert à rien.','raw_frustration',['match','frustration','confidence_low'],2),
  raw('raw_frustration_014','J’en ai marre, là.','raw_frustration',['match','frustration'],3),
  raw('raw_frustration_015','Putain de journée.','raw_frustration',['career','bad_day'],2),
  raw('raw_frustration_016','Nan, nan, nan.','raw_frustration',['match','frustration'],1),
  raw('raw_frustration_017','Ça peut pas être vrai.','raw_frustration',['match','frustration','surprise'],2),
  raw('raw_frustration_018','Sérieux, là ?','raw_frustration',['match','frustration'],1),
  raw('raw_frustration_019','Merde alors.','raw_frustration',['match','frustration'],1),
  raw('raw_frustration_020','Putain de ballon.','raw_frustration',['match','frustration'],2),

  // 2. Joie / euphorie brute
  raw('raw_joy_001','Ouais !!','raw_joy',['match','success','joy'],2),
  raw('raw_joy_002','Let’s go !!','raw_joy',['match','success','joy'],2),
  raw('raw_joy_003','Yes, putain, yes !','raw_joy',['match','success','joy'],3),
  raw('raw_joy_004','Enfin !','raw_joy',['match','relief','joy'],2),
  raw('raw_joy_005','Ah ouais !','raw_joy',['match','success','surprise'],2),
  raw('raw_joy_006','C’est ça !','raw_joy',['match','success'],2),
  raw('raw_joy_007','Voilà !','raw_joy',['match','success'],1),
  raw('raw_joy_008','Trop bien !','raw_joy',['match','success','young'],2),
  raw('raw_joy_009','Ah là là, oui !','raw_joy',['match','success','joy'],2),
  raw('raw_joy_010','Ouais, je le savais.','raw_joy',['match','success','confidence'],2),
  raw('raw_joy_011','C’est parti !','raw_joy',['match','momentum','joy'],2),
  raw('raw_joy_012','Wouh !','raw_joy',['match','success','joy'],1),
  raw('raw_joy_013','Ah, c’est beau ça.','raw_joy',['match','beautiful_play','joy'],2),
  raw('raw_joy_014','Sérieux, énorme.','raw_joy',['match','big_moment','joy'],3),
  raw('raw_joy_015','Ouiii, enfin !','raw_joy',['match','relief','joy'],3),
  raw('raw_joy_016','Ça fait du bien.','raw_joy',['match','relief','joy'],2),
  raw('raw_joy_017','J’y crois pas, ouais !','raw_joy',['match','surprise','joy'],3),
  raw('raw_joy_018','Trop content, là.','raw_joy',['match','success','young'],2),
  raw('raw_joy_019','Allez, ouais !','raw_joy',['match','success','momentum'],2),
  raw('raw_joy_020','Ça, c’est fait.','raw_joy',['match','success','relief'],1),

  // 3. Douleur / fatigue brute
  raw('raw_pain_001','Aïe.','raw_pain',['match','pain'],2),
  raw('raw_pain_002','Ça pique.','raw_pain',['match','pain','fatigue'],1),
  raw('raw_pain_003','Putain, ma cuisse.','raw_pain',['match','pain','thigh'],3),
  raw('raw_pain_004','J’en peux plus.','raw_pain',['match','fatigue_high'],3),
  raw('raw_pain_005','Ouille.','raw_pain',['match','pain'],1),
  raw('raw_pain_006','Ça brûle.','raw_pain',['match','fatigue','muscle_burn'],2),
  raw('raw_pain_007','Plus une goutte d’essence.','raw_pain',['match','fatigue_high'],3),
  raw('raw_pain_008','Mes jambes, putain.','raw_pain',['match','fatigue_high','legs'],3),
  raw('raw_pain_009','Ça tire fort, là.','raw_pain',['match','pain','muscle'],3),
  raw('raw_pain_010','Aïe, aïe, aïe.','raw_pain',['match','pain'],2),
  raw('raw_pain_011','Je tiens plus.','raw_pain',['match','fatigue_high'],3),
  raw('raw_pain_012','C’est fini pour moi, là.','raw_pain',['match','injury_fear','fatigue_high'],3),
  raw('raw_pain_013','Ça fait mal.','raw_pain',['match','pain'],2),
  raw('raw_pain_014','Putain, ce point de côté.','raw_pain',['match','pain','stitch'],2),
  raw('raw_pain_015','Encore un effort, allez.','raw_pain',['match','fatigue','resilience'],2),
  raw('raw_pain_016','Ça y est, cramé.','raw_pain',['match','fatigue_high'],3),
  raw('raw_pain_017','J’ai plus rien.','raw_pain',['match','fatigue_high'],3),
  raw('raw_pain_018','Souffle, souffle.','raw_pain',['match','fatigue','breathing'],1),
  raw('raw_pain_019','Putain, c’est dur.','raw_pain',['match','fatigue','pressure'],2),
  raw('raw_pain_020','Tiens bon, tiens bon.','raw_pain',['match','fatigue','resilience'],2),

  // 4. Choc / surprise brute
  raw('raw_surprise_001','Quoi ?!','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_002','Sérieux ?','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_003','C’est pas possible.','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_004','Hein ?','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_005','Putain, j’y crois pas.','raw_surprise',['match','surprise','big_moment'],3),
  raw('raw_surprise_006','Wow.','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_007','Non mais attends.','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_008','Ça vient d’où, ça ?','raw_surprise',['match','unexpected'],2),
  raw('raw_surprise_009','J’ai rien vu venir.','raw_surprise',['match','unexpected'],2),
  raw('raw_surprise_010','Ah bah ça alors.','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_011','C’est quoi, ça ?','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_012','Whoa.','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_013','Pas possible.','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_014','J’ai halluciné, là.','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_015','Sérieux, ça vient de se passer ?','raw_surprise',['match','big_moment','surprise'],3),
  raw('raw_surprise_016','Ok, là c’est énorme.','raw_surprise',['match','big_moment','surprise'],3),
  raw('raw_surprise_017','Ah ouais, quand même.','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_018','Ça alors.','raw_surprise',['match','surprise'],1),
  raw('raw_surprise_019','J’en reviens pas.','raw_surprise',['match','surprise'],2),
  raw('raw_surprise_020','Putain, quel geste.','raw_surprise',['match','spectacular_gesture','surprise'],3),

  // 5. Autocritique brute
  raw('raw_selfcrit_001','Nul.','raw_selfcriticism',['match','self_blame'],2),
  raw('raw_selfcrit_002','Putain, t’es nul là.','raw_selfcriticism',['match','self_blame','confidence_low'],3),
  raw('raw_selfcrit_003','Allez, réveille-toi.','raw_selfcriticism',['match','self_command'],2),
  raw('raw_selfcrit_004','Sérieux, concentre-toi.','raw_selfcriticism',['match','focus'],2),
  raw('raw_selfcrit_005','Ça suffit les erreurs.','raw_selfcriticism',['match','mistake','repeat'],3),
  raw('raw_selfcrit_006','Ressaisis-toi.','raw_selfcriticism',['match','self_command'],2),
  raw('raw_selfcrit_007','Merde, réagis.','raw_selfcriticism',['match','self_command'],2),
  raw('raw_selfcrit_008','T’es où, là ?','raw_selfcriticism',['match','focus','self_blame'],2),
  raw('raw_selfcrit_009','Bouge-toi, putain.','raw_selfcriticism',['match','self_command'],3),
  raw('raw_selfcrit_010','Franchement, honteux.','raw_selfcriticism',['match','self_blame'],3),
  raw('raw_selfcrit_011','Fais mieux.','raw_selfcriticism',['match','self_command'],1),
  raw('raw_selfcrit_012','Allez, réveille-toi.','raw_selfcriticism',['match','self_command','repeat'],2),
  raw('raw_selfcrit_013','Pathétique, ça.','raw_selfcriticism',['match','self_blame'],3),
  raw('raw_selfcrit_014','Putain, reprends-toi.','raw_selfcriticism',['match','self_command'],3),
  raw('raw_selfcrit_015','Trop mou aujourd’hui.','raw_selfcriticism',['match','form_low'],2),
  raw('raw_selfcrit_016','Sérieux, plus d’attention.','raw_selfcriticism',['match','focus'],2),
  raw('raw_selfcrit_017','Ça, c’est pas toi.','raw_selfcriticism',['match','identity','form_low'],2),
  raw('raw_selfcrit_018','Concentre-toi, bon sang.','raw_selfcriticism',['match','focus'],2),
  raw('raw_selfcrit_019','Allez, sois pro.','raw_selfcriticism',['match','professional','self_command'],2),
  raw('raw_selfcrit_020','Reste focus, putain.','raw_selfcriticism',['match','focus'],3),

  // 6. Rage de vaincre / motivation brute
  raw('raw_drive_001','Allez !','raw_drive',['match','motivation'],1),
  raw('raw_drive_002','Vas-y !','raw_drive',['match','motivation'],1),
  raw('raw_drive_003','On lâche rien.','raw_drive',['match','motivation','team'],2),
  raw('raw_drive_004','Allez, allez, allez !','raw_drive',['match','motivation'],2),
  raw('raw_drive_005','Fonce !','raw_drive',['match','motivation','attack'],2),
  raw('raw_drive_006','On y va.','raw_drive',['match','motivation','team'],1),
  raw('raw_drive_007','Bats-toi.','raw_drive',['match','motivation','self_command'],2),
  raw('raw_drive_008','Encore un effort.','raw_drive',['match','fatigue','motivation'],2),
  raw('raw_drive_009','Donne tout.','raw_drive',['match','motivation','late_match'],3),
  raw('raw_drive_010','Grave envie de gagner ça.','raw_drive',['match','motivation','important_match'],3),
  raw('raw_drive_011','On les tient.','raw_drive',['match','leading','team'],2),
  raw('raw_drive_012','Continue, continue.','raw_drive',['match','motivation'],1),
  raw('raw_drive_013','Allez putain, pousse.','raw_drive',['match','motivation','pressure'],3),
  raw('raw_drive_014','Rien lâcher.','raw_drive',['match','motivation'],2),
  raw('raw_drive_015','Crois-y, avance.','raw_drive',['match','motivation','self_command'],2),
  raw('raw_drive_016','On va les avoir.','raw_drive',['match','motivation','team'],2),
  raw('raw_drive_017','Reste dedans.','raw_drive',['match','focus','motivation'],2),
  raw('raw_drive_018','Encore, encore.','raw_drive',['match','motivation','momentum'],2),
  raw('raw_drive_019','Allez, on tient bon.','raw_drive',['match','late_match','team'],2),
  raw('raw_drive_020','Fonce, fonce !','raw_drive',['match','motivation','attack'],2),

  // 7. Peur / doute brute
  raw('raw_fear_001','Et si je rate ?','raw_fear',['match','fear','chance'],2),
  raw('raw_fear_002','Putain, j’ai peur là.','raw_fear',['match','fear','pressure'],3),
  raw('raw_fear_003','Ça va aller ?','raw_fear',['match','fear','uncertainty'],2),
  raw('raw_fear_004','J’ai un doute.','raw_fear',['match','doubt'],2),
  raw('raw_fear_005','Sérieux, j’y crois pas trop.','raw_fear',['match','confidence_low'],2),
  raw('raw_fear_006','Ça sent pas bon.','raw_fear',['match','fear','bad_feeling'],2),
  raw('raw_fear_007','Putain, stress.','raw_fear',['match','pressure','fear'],2),
  raw('raw_fear_008','J’ai les jambes en coton.','raw_fear',['match','pressure','fear','legs'],3),
  raw('raw_fear_009','Ça va foirer.','raw_fear',['match','fear','confidence_low'],3),
  raw('raw_fear_010','J’y arrive pas, là.','raw_fear',['match','confidence_low'],3),
  raw('raw_fear_011','Merde, j’ai peur de rater.','raw_fear',['match','fear','chance'],3),
  raw('raw_fear_012','Ça tremble.','raw_fear',['match','pressure','fear'],2),
  raw('raw_fear_013','Je sens pas ce coup-là.','raw_fear',['match','fear','bad_feeling'],2),
  raw('raw_fear_014','Putain, c’est chaud.','raw_fear',['match','pressure'],2),
  raw('raw_fear_015','J’ose pas.','raw_fear',['match','fear','hesitation'],3),
  raw('raw_fear_016','Et si ça part mal ?','raw_fear',['match','fear','uncertainty'],2),
  raw('raw_fear_017','Ça me fait flipper.','raw_fear',['match','fear'],3),
  raw('raw_fear_018','J’ai un mauvais pressentiment.','raw_fear',['match','fear','bad_feeling'],2),
  raw('raw_fear_019','Putain, le stress monte.','raw_fear',['match','pressure','fear'],3),
  raw('raw_fear_020','Ça va pas le faire.','raw_fear',['match','confidence_low','fear'],3),

  // 8. Soulagement brut
  raw('raw_relief_001','Ouf.','raw_relief',['match','relief'],1),
  raw('raw_relief_002','Putain, ça va.','raw_relief',['match','relief'],2),
  raw('raw_relief_003','Enfin fini.','raw_relief',['match','final_whistle','relief'],2),
  raw('raw_relief_004','Ouf, ça passe.','raw_relief',['match','relief','close_call'],2),
  raw('raw_relief_005','Ça va, respire.','raw_relief',['match','relief','self_command'],1),
  raw('raw_relief_006','Putain, sauvé.','raw_relief',['match','relief','close_call'],3),
  raw('raw_relief_007','Ouf, pas grave.','raw_relief',['match','relief','mistake'],1),
  raw('raw_relief_008','Ça va aller finalement.','raw_relief',['match','relief'],2),
  raw('raw_relief_009','Bon, ça passe.','raw_relief',['match','relief'],1),
  raw('raw_relief_010','Ouf, c’était moins une.','raw_relief',['match','close_call','relief'],3),
  raw('raw_relief_011','Ça y est, c’est bon.','raw_relief',['match','relief'],2),
  raw('raw_relief_012','Enfin le sifflet.','raw_relief',['match','final_whistle','relief'],2),
  raw('raw_relief_013','Ouf, terminé.','raw_relief',['match','final_whistle','relief'],2),
  raw('raw_relief_014','Ça soulage.','raw_relief',['match','relief'],2),
  raw('raw_relief_015','Bon débarras ce match.','raw_relief',['match','final_whistle','bad_match'],3),
  raw('raw_relief_016','Putain, enfin.','raw_relief',['match','relief'],2),
  raw('raw_relief_017','Ouf, plus de stress.','raw_relief',['match','relief','pressure'],2),
  raw('raw_relief_018','Ça fait du bien de souffler.','raw_relief',['match','relief','fatigue'],2),
  raw('raw_relief_019','Enfin tranquille.','raw_relief',['match','relief'],1),
  raw('raw_relief_020','Ouf, ça a payé.','raw_relief',['match','relief','success'],2),

  // 9. Arbitre / adversaire brute
  raw('raw_conflict_001','N’importe quoi cet arbitrage.','raw_conflict',['match','referee','anger'],3),
  raw('raw_conflict_002','Sérieux, monsieur l’arbitre ?','raw_conflict',['match','referee'],2),
  raw('raw_conflict_003','Ça, c’est faute putain.','raw_conflict',['match','referee','foul'],3),
  raw('raw_conflict_004','Il a rien vu ou quoi ?','raw_conflict',['match','referee','anger'],3),
  raw('raw_conflict_005','Allez, carton putain.','raw_conflict',['match','referee','card'],3),
  raw('raw_conflict_006','C’est une blague ?','raw_conflict',['match','referee','surprise'],2),
  raw('raw_conflict_007','Franchement, aveugle.','raw_conflict',['match','referee','anger'],3),
  raw('raw_conflict_008','Ça se voit pas, ça ?','raw_conflict',['match','referee'],2),
  raw('raw_conflict_009','Putain, quelle faute.','raw_conflict',['match','foul','anger'],3),
  raw('raw_conflict_010','Il fait exprès ou quoi ?','raw_conflict',['match','opponent','provocation'],3),
  raw('raw_conflict_011','Sérieux, réveillez-vous.','raw_conflict',['match','referee','anger'],3),
  raw('raw_conflict_012','Ça mérite un jaune, ça.','raw_conflict',['match','referee','card'],2),
  raw('raw_conflict_013','N’importe quoi cette décision.','raw_conflict',['match','referee','anger'],3),
  raw('raw_conflict_014','Ah bah voilà, typique.','raw_conflict',['match','referee','frustration'],2),
  raw('raw_conflict_015','Toujours pareil avec lui.','raw_conflict',['match','direct_opponent','repeat'],2),
  raw('raw_conflict_016','Ça suffit ces provocations.','raw_conflict',['match','opponent','provocation'],3),
  raw('raw_conflict_017','Touche-moi encore pour voir.','raw_conflict',['match','direct_opponent','provocation','ego_high'],3),
  raw('raw_conflict_018','Ok, très bien. Je note.','raw_conflict',['match','direct_opponent','provocation','memory'],3),
  raw('raw_conflict_019','Ça va chauffer si ça continue.','raw_conflict',['match','direct_opponent','provocation','anger'],3),
  raw('raw_conflict_020','Franchement, du grand n’importe quoi.','raw_conflict',['match','referee','frustration'],3),

  // 10. Encouragement collectif / soi
  raw('raw_team_001','Allez les gars !','raw_team',['match','team','encouragement'],2),
  raw('raw_team_002','On tient, on tient.','raw_team',['match','team','leading','late_match'],2),
  raw('raw_team_003','Reste avec moi.','raw_team',['match','team','defending'],2),
  raw('raw_team_004','Allez, ensemble.','raw_team',['match','team','encouragement'],2),
  raw('raw_team_005','On y croit.','raw_team',['match','team','motivation'],2),
  raw('raw_team_006','Courage, courage.','raw_team',['match','team','fatigue'],2),
  raw('raw_team_007','Serrez les rangs.','raw_team',['match','team','defending'],2),
  raw('raw_team_008','Allez, on pousse.','raw_team',['match','team','attacking'],2),
  raw('raw_team_009','Restez concentrés.','raw_team',['match','team','focus'],2),
  raw('raw_team_010','On lâche rien les gars.','raw_team',['match','team','motivation'],3),
  raw('raw_team_011','Allez, un dernier effort tous ensemble.','raw_team',['match','team','late_match'],3),
  raw('raw_team_012','On se soutient.','raw_team',['match','team','encouragement'],2),
  raw('raw_team_013','Bouge, on est avec toi.','raw_team',['match','team','encouragement'],2),
  raw('raw_team_014','Allez, courage à tous.','raw_team',['match','team','encouragement'],2),
  raw('raw_team_015','On reste solides.','raw_team',['match','team','defending'],2),
  raw('raw_team_016','Serre les dents avec nous.','raw_team',['match','team','fatigue'],2),
  raw('raw_team_017','Allez, on y est presque.','raw_team',['match','team','late_match'],3),
  raw('raw_team_018','Tenez bon.','raw_team',['match','team','late_match','defending'],2),
  raw('raw_team_019','On finit fort.','raw_team',['match','team','late_match'],3),
  raw('raw_team_020','Allez, tous ensemble jusqu’au bout.','raw_team',['match','team','late_match'],3)
];

export const RAW_INNER_VOICE_FAMILIES = Object.freeze([
  'raw_frustration','raw_joy','raw_pain','raw_surprise','raw_selfcriticism',
  'raw_drive','raw_fear','raw_relief','raw_conflict','raw_team'
]);

export default PLAYER_INNER_VOICE_RAW;
