create table if not exists public.beta_signups (
  id bigint generated by default as identity primary key,
  email text not null,
  platform text not null check (platform in ('PC', 'iOS', 'Android')),
  source text not null default 'direct',
  campaign text,
  created_at timestamptz not null default now(),
  constraint beta_signups_email_unique unique (email)
);

alter table public.beta_signups enable row level security;

-- No public INSERT/SELECT policies on purpose.
-- The Vercel serverless endpoint writes with SUPABASE_SERVICE_ROLE_KEY,
-- which must remain server-side only.

create index if not exists beta_signups_created_at_idx
  on public.beta_signups (created_at desc);

create index if not exists beta_signups_source_idx
  on public.beta_signups (source);