// V2 des attributs : couche canonique de lecture pour le moteur de jeu.
// Les 7 anciens attributs restent compatibles pour les sauvegardes.
export const FOOTBALL_ATTRIBUTES_V2=['vitesse','acceleration','endurance','puissance','finition','tir','passe','controle','dribble','vision','placement','defense'];
export const MENTAL_ATTRIBUTES=['concentration','sangFroid','decision','regularite','resistancePression'];
const LEGACY_MAP={vitesse:'vitesse',tir:'tir,passe'.split(',')[0],passe:'passe',passes:'passe',dribble:'dribble',defense:'defense',physique:'puissance',mental:'concentration',tete:'concentration'};
const clamp=(v,min=1,max=99)=>Math.min(max,Math.max(min,Math.round(Number(v)||0)));
const avg=values=>values.reduce((a,b)=>a+b,0)/Math.max(1,values.length);
export function createFromLegacy(attributes={},hidden={}){
 const vitesse=clamp(attributes.vitesse??50),tir=clamp(attributes.tir??50),passe=clamp(attributes.passe??attributes.passes??50),dribble=clamp(attributes.dribble??50),defense=clamp(attributes.defense??50),physique=clamp(attributes.physique??50),mental=clamp(attributes.mental??attributes.tete??50),regularite=clamp((hidden.consistency??12)*5.5);
 return {vitesse,acceleration:clamp(vitesse+(dribble-50)*.25),endurance:clamp(avg([physique,vitesse,mental])),puissance:physique,finition:tir,tir,passe,controle:clamp(avg([dribble,passe,mental])),dribble,vision:clamp(avg([passe,mental])),placement:clamp(avg([defense,mental])),defense,mental:{concentration:mental,sangFroid:clamp(avg([mental,tir])),decision:clamp(avg([mental,passe,dribble])),regularite,resistancePression:clamp(avg([mental,regularite]))}};
}
export function ensure(player){if(!player)return null;const migrated=createFromLegacy(player.attributes||{},player.hidden||{});if(!player.attributesV2)player.attributesV2=migrated;for(const key of FOOTBALL_ATTRIBUTES_V2)player.attributesV2[key]=clamp(player.attributesV2[key]??migrated[key]);player.attributesV2.mental={...migrated.mental,...(player.attributesV2.mental||{})};for(const key of MENTAL_ATTRIBUTES)player.attributesV2.mental[key]=clamp(player.attributesV2.mental[key]);return player.attributesV2;}
export function syncLegacy(player){const a=ensure(player);player.attributes=player.attributes||{};Object.assign(player.attributes,{vitesse:a.vitesse,tir:a.tir,passe:a.passe,dribble:a.dribble,defense:a.defense,physique:a.puissance,mental:a.mental.concentration});return player.attributes;}
export function get(player,key,fallback=50){const a=ensure(player);const mapped=LEGACY_MAP[key]||key;if(FOOTBALL_ATTRIBUTES_V2.includes(mapped))return clamp(a[mapped]??fallback);if(MENTAL_ATTRIBUTES.includes(mapped))return clamp(a.mental?.[mapped]??fallback);return clamp(fallback);}
export function getRoleProfile(player){const p=String(player?.position||'').toUpperCase();if(['GK','GB','G'].includes(p))return'goalkeeper';if(['DC','CB','DD','DG','RB','LB','D','LAT'].includes(p))return'defender';if(['MC','CM','MOC','CAM','MD','MG','M','MDEF','MOFF'].includes(p))return'midfielder';return'attacker';}
export function calculateOverall(player){const a=ensure(player);const weights={attacker:{finition:.25,tir:.12,dribble:.14,vitesse:.10,acceleration:.08,controle:.08,vision:.07,placement:.10,endurance:.02,puissance:.02,passe:.02},midfielder:{passe:.18,vision:.16,controle:.13,dribble:.11,endurance:.09,placement:.10,defense:.07,tir:.06,vitesse:.04,acceleration:.03,finition:.03},defender:{defense:.22,placement:.15,puissance:.13,endurance:.11,vitesse:.08,acceleration:.06,passe:.10,controle:.06,vision:.04,tir:.02,finition:.01},goalkeeper:{defense:.24,placement:.18,puissance:.12,endurance:.08,passe:.08,vision:.08,controle:.05,vitesse:.05,acceleration:.04,tir:.02,finition:.01}}[getRoleProfile(player)];return clamp(Object.entries(weights).reduce((sum,[key,w])=>sum+a[key]*w,0));}
export function describe(player){const a=ensure(player);return{football:Object.fromEntries(FOOTBALL_ATTRIBUTES_V2.map(k=>[k,a[k]])),mental:{...a.mental},overall:calculateOverall(player)};}
export default{FOOTBALL_ATTRIBUTES_V2,MENTAL_ATTRIBUTES,createFromLegacy,ensure,syncLegacy,get,getRoleProfile,calculateOverall,describe};
