/* =========================================================
   CAREER SIMULATION V5 — calibration du moteur canonique
   Outil de développement uniquement.
   ========================================================= */
import { PlayerLogic } from './player.js';
import { CareerSystem } from './careerSystem.js';
import { PotentialSystem } from './potentialSystem.js';
import { TrainingManager } from './entrainement.js';
import SimulatedMatchSystem from './domain/match/simulatedMatchSystem.js';
import { CompetitionSystem } from './competitionSystem.js';
import { WorldSystem } from './worldSystem.js';
import { CupSystem } from './cupSystemV2.js';
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;const pick=a=>a[Math.floor(Math.random()*a.length)];
const POSITIONS=['BU','MOC','MC','AD','AG','DC','DD','DG','GK'];const ORIGINS=['CENTRE_FORMATION','CLUB_AMATEUR','FUTSAL','STREET','ATHLETE','DEBUTANT_TARDIF','FILS_DE_PRO'];const FOCUSES=['TECHNIQUE','FINITION','DEPLACEMENT','DEFENSE','COACH','RECUPERATION','REPOS'];const MONTHS=[8,9,10,11,12,1,2,3,4,5];
const matchSystem=new SimulatedMatchSystem();
function resetStats(p){p.stats.matchesPlayed=0;p.stats.goals=0;p.stats.assists=0;p.stats.successfulPasses=0;p.stats.tackles=0;p.stats.yellowCards=0;p.stats.cleanSheets=0;p.stats.averageRating=0;}
function createState(player,year){return{schemaVersion:9,player,trainingFocus:'TECHNIQUE',social:{coachData:{name:'Sim Coach',relation:50,opinion:'Neutre'}},media:{},career:{balance:0,seasonHistory:[],totalCareerIncome:0},calendar:{currentMonth:8,currentSeasonYear:year,currentPeriod:'Pré-saison & reprise',totalMonths:12,seasonSchedule:null,seasonMatchCursor:0},seasonPhase:'pre_season',pendingEvent:null,pendingCoachEvent:null,pendingMediaDilemma:null,pendingTransferOffer:null,pendingPositionProposal:null,world:{version:1,leagues:{},lastSeasonFinalized:null},cups:{},cupHistory:[],careerStructure:player.careerProfile||null,relationships:{},careerMemory:[]};}
function createCareer(index,year){const player=PlayerLogic.createPlayerProfile({firstname:`SIM${index}`,lastname:'TEST',nationality:'France',country:'France',position:pick(POSITIONS),origin:pick(ORIGINS),age:14});WorldSystem.ensureWorld({player,world:{version:1,leagues:{}}});const clubs=WorldSystem.getClubs('FR_L1');const club=clubs[Math.floor(Math.random()*clubs.length)]||clubs[0];if(!club)throw new Error('Aucun club disponible dans WorldSystem.');player.club=club.name;player.clubId=club.id;player.clubCountry=club.country||'France';player.clubLevel=Number(club.tier)||1;player.isYouthPlayer=true;player.youthClubName=club.name;CareerSystem.initialize(player,club);PotentialSystem.ensure(player);player.morale=80;player.fitness=90;player.isInjured=false;player.injuryDuration=0;const state=createState(player,year);WorldSystem.ensureWorld(state);CupSystem.ensure?.(state);CompetitionSystem.ensureSeasonSchedule(state);return{player,state};}
function setupSeason(state){state.calendar.seasonSchedule=null;state.calendar.seasonMatchCursor=0;state.calendar.currentMonth=8;state.seasonPhase='pre_season';WorldSystem.ensureWorld(state);CupSystem.ensure?.(state);CompetitionSystem.ensureSeasonSchedule(state);}
function simulateSeason(career,year){const{player,state}=career;setupSeason(state);resetStats(player);const startOverall=n(player.overall),startPotential=n(player.potential),startAge=n(player.age),reports=[];for(const month of MONTHS){state.calendar.currentMonth=month;state.calendar.currentPeriod=CompetitionSystem.getPeriodName?.(month)||state.calendar.currentPeriod;const focus=pick(FOCUSES);state.trainingFocus=focus;TrainingManager.applyTraining(player,focus);player.morale=clamp(player.morale+(Math.random()-.5)*3,20,100);const report=matchSystem.simulateBlock(state,focus,null);if(report)reports.push(report);player.fitness=clamp(player.fitness-1,20,100);}const matches=n(player.stats.matchesPlayed,reports.reduce((s,r)=>s+n(r.summary?.matchesPlayed),0)),rating=n(player.stats.averageRating),goals=n(player.stats.goals),assists=n(player.stats.assists);const potentialResult=PotentialSystem.finalizeSeason(player,{seasonLabel:`${year}/${year+1}`,age:startAge,overall:player.overall,matches,averageRating:rating,goals,assists});PotentialSystem.advanceAge(player);return{age:startAge,endAge:n(player.age),startOverall,startPotential,endOverall:n(player.overall),endPotential:n(player.potential),potentialChange:n(potentialResult?.change),matches,averageRating:rating,goals,assists,fitness:n(player.fitness),morale:n(player.morale)};}
function percentile(values,p){const s=[...values].sort((a,b)=>a-b);if(!s.length)return 0;const i=(s.length-1)*p,l=Math.floor(i),u=Math.ceil(i);return l===u?s[l]:s[l]+(s[u]-s[l])*(i-l);}
function dist(values){if(!values.length)return null;return{mean:values.reduce((a,b)=>a+b,0)/values.length,median:percentile(values,.5),p10:percentile(values,.1),p90:percentile(values,.9),min:Math.min(...values),max:Math.max(...values)};}
export function simulateCareers(count=1000,options={}){const total=Math.max(1,Math.floor(Number(count)||1000)),maxAge=Math.min(42,Math.max(18,Number(options.maxAge)||34)),startYear=Number(options.startSeasonYear)||new Date().getFullYear(),checkpoints=options.checkpoints||[18,20,22,25,28,30,34],careers=[],errors=[];for(let i=1;i<=total;i++){try{const c=createCareer(i,startYear),r={id:i,position:c.player.position,initialOverall:n(c.player.overall),initialPotential:n(c.player.potential),peakOverall:n(c.player.overall),peakAge:n(c.player.age),seasons:[],finalOverall:0,finalPotential:0,totalMatches:0};while(n(c.player.age)<maxAge&&!c.player.careerEnded){const s=simulateSeason(c,startYear+r.seasons.length);r.seasons.push(s);r.totalMatches+=s.matches;if(s.endOverall>r.peakOverall){r.peakOverall=s.endOverall;r.peakAge=s.endAge;}}r.finalOverall=n(c.player.overall);r.finalPotential=n(c.player.potential);r.finalAge=n(c.player.age);careers.push(r);}catch(error){errors.push({id:i,message:error?.message||String(error)});}}
const finalsO=careers.map(c=>c.finalOverall),finalsP=careers.map(c=>c.finalPotential),peaks=careers.map(c=>c.peakOverall),thresholds={overall85Plus:careers.filter(c=>c.peakOverall>=85).length,overall90Plus:careers.filter(c=>c.peakOverall>=90).length,overall95Plus:careers.filter(c=>c.peakOverall>=95).length,potential85Plus:careers.filter(c=>c.finalPotential>=85).length,potential90Plus:careers.filter(c=>c.finalPotential>=90).length,potential95Plus:careers.filter(c=>c.finalPotential>=95).length};const rates=Object.fromEntries(Object.entries(thresholds).map(([k,v])=>[k,careers.length?v/careers.length*100:0]));const checkpointsResult=Object.fromEntries(checkpoints.map(age=>{const rows=careers.map(c=>c.seasons.find(s=>s.endAge===age)).filter(Boolean);return[age,{count:rows.length,overall:dist(rows.map(r=>r.endOverall)),potential:dist(rows.map(r=>r.endPotential)),rating:dist(rows.map(r=>r.averageRating)),matches:dist(rows.map(r=>r.matches))}]}));return{version:5,simulatorType:'canonical-match-performance',countRequested:total,countCompleted:careers.length,countErrors:errors.length,maxAge,generatedAt:new Date().toISOString(),engine:'SimulatedMatchSystem -> matchPerformanceEngine -> PlayerSystem',finalOverall:dist(finalsO),finalPotential:dist(finalsP),peakOverall:dist(peaks),thresholds,rates,checkpoints:checkpointsResult,errors,careers};}
export const simulateCareer=simulateCareers;
export function printSimulationReport(r){console.table({'Demandées':r.countRequested,'Terminées':r.countCompleted,'Erreurs':r.countErrors,'GEN initial moyen':dist(r.careers.map(c=>c.initialOverall))?.mean?.toFixed(2)||'-','GEN final moyen':r.finalOverall?.mean?.toFixed(2)||'-','Potentiel final moyen':r.finalPotential?.mean?.toFixed(2)||'-','Potentiel >=85':`${r.thresholds.potential85Plus} (${r.rates.potential85Plus.toFixed(1)}%)`,'Potentiel >=90':`${r.thresholds.potential90Plus} (${r.rates.potential90Plus.toFixed(1)}%)`,'Potentiel >=95':`${r.thresholds.potential95Plus} (${r.rates.potential95Plus.toFixed(1)}%)`});return r;}
export default simulateCareers;
