// consequenceSystem.js — choix = émotions/relations/moral; effet sportif indirect.
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const LIMITS={morale:[0,100],confidence:[0,100],mental:[0,100],relationCoach:[0,100],vestiaire:[0,100],discipline:[0,100],fame:[0,100],reputation:[0,100]};
const LABELS={morale:'Moral',confidence:'Confiance',mental:'Mental',relationCoach:'Relation coach',vestiaire:'Vestiaire',discipline:'Discipline',fame:'Réputation',reputation:'Réputation'};const EMOTIONAL=new Set(Object.keys(LIMITS));
function ensure(p){if(!p)throw new Error('ConsequenceSystem : joueur manquant.');p.stats||={};p.temporaryEffects||=[];for(const[k,v]of Object.entries({morale:50,confidence:50,mental:50,relationCoach:50,vestiaire:50,discipline:50,fame:10,reputation:10}))if(p[k]===undefined&&p.stats[k]===undefined)p[k]=v;return p;}
function read(p,k){return p[k]!==undefined?num(p[k]):num(p.stats?.[k]);}
function write(p,k,d){if(!EMOTIONAL.has(k))return null;const before=read(p,k),after=clamp(before+num(d),...LIMITS[k]);if(p[k]!==undefined)p[k]=after;else p.stats[k]=after;return{stat:k,label:LABELS[k]||k,before,after,delta:after-before,type:'emotional'};}
function normalize(choice={}){const c=choice.consequences&&typeof choice.consequences==='object'?choice.consequences:{};const legacy=choice.impacts||choice;const permanent={...(c.permanent||{}),...(c.emotional||{})};for(const[k,v]of Object.entries(legacy||{}))if(EMOTIONAL.has(k)&&permanent[k]===undefined)permanent[k]=v;const temporary=[...(c.temporary||c.effects||[])];if(legacy.matchBonuses)for(const[k,v]of Object.entries(legacy.matchBonuses))if(typeof v==='number')temporary.push({stat:`matchBonus.${k}`,value:v,duration:1,label:k});return{title:c.title||choice.title||null,message:c.message||choice.message||null,permanent,temporary};}
function addTemporary(p,e,source){if(!e?.stat||!num(e.value))return null;const d=clamp(Math.round(num(e.duration,2)),1,3),x={id:e.id||`effect_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,stat:e.stat,value:num(e.value),duration:d,remainingMatches:d,source:e.source||source||'Choix',label:e.label||e.stat,description:e.description||null};p.temporaryEffects.push(x);if(p.temporaryEffects.length>8)p.temporaryEffects.shift();return x;}
function mentalEffect(changes){let x=0;for(const c of changes){const d=num(c.delta);if(c.stat==='morale')x+=d*.025;else if(c.stat==='confidence')x+=d*.035;else if(c.stat==='mental')x+=d*.03;else if(c.stat==='relationCoach')x+=d*.015;else if(c.stat==='discipline')x+=d*.008;}return clamp(x,-.35,.35);}
function applyInternal(player,choice,source){ensure(player);const c=normalize(choice),changes=[],temporary=[];for(const[k,v]of Object.entries(c.permanent)){if(!EMOTIONAL.has(k)||!num(v))continue;const x=write(player,k,v);if(x)changes.push(x);}const mentalBoost=mentalEffect(changes);if(mentalBoost)temporary.push(addTemporary(player,{stat:'matchPerformance',value:mentalBoost,duration:2,label:'État mental'},source));for(const e of c.temporary){const x=addTemporary(player,e,source);if(x)temporary.push(x);}return{title:c.title||'Conséquences',message:c.message||null,source,changes,temporary:temporary.filter(Boolean),xp:0};}
export const ConsequenceSystem={LIMITS,LABELS,initialize:ensure,normalizeChoice:normalize,apply(player,choice={},options={}){return applyInternal(player,choice,options.source||'Choix');},applyToState(state,choice={},options={}){return state?.player?applyInternal(state.player,choice,options.source||'Choix'):null;},applyCoachChoice(state,choice={}){return this.applyToState(state,choice,{source:'Coach'});},applyEventChoice(state,choice={}){return this.applyToState(state,choice,{source:'Événement'});},applyMatchChoice(player,choice={}){return applyInternal(player,choice,'Match');},getTemporaryModifier(player,stat){ensure(player);return player.temporaryEffects.filter(e=>e.stat===stat).reduce((s,e)=>s+num(e.value),0);},getActiveModifiers(player){ensure(player);return player.temporaryEffects.reduce((r,e)=>{r[e.stat]=(r[e.stat]||0)+num(e.value);return r;},{});},advanceMatch(player){ensure(player);const expired=[];player.temporaryEffects=player.temporaryEffects.filter(e=>{e.remainingMatches=num(e.remainingMatches,e.duration)-1;if(e.remainingMatches<=0){expired.push(e);return false;}return true;});return expired;},preview(choice={}){const c=normalize(choice);return{title:c.title||'Conséquences',message:c.message||null,effects:Object.entries(c.permanent).filter(([k,v])=>EMOTIONAL.has(k)&&num(v)).map(([stat,delta])=>({type:'emotional',stat,label:LABELS[stat]||stat,delta:num(delta),direction:num(delta)>0?'positive':'negative'}))};},sanitize(choice={}){const copy=JSON.parse(JSON.stringify(choice));const p=copy.permanent||copy.stats||{};for(const k of Object.keys(p))if(EMOTIONAL.has(k))p[k]=clamp(num(p[k]),-3,3);else delete p[k];delete copy.xp;delete copy.experience;return copy;}};
export default ConsequenceSystem;
