// potentialSystem.js
// Le potentiel vivant dépend uniquement des prestations de match et du bilan sportif.
// Aucun entraînement, dialogue, moral ou relation ne modifie directement le potentiel.
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
export const POTENTIAL_RULES={START_MIN:75,START_MAX:80,ABSOLUTE_MIN:69,CAREER_MAX:99,MIN_MATCHES_RELIABLE:12,MIN_MATCHES_EXCEPTIONAL:24,PEAK_MIN_AGE:15,PEAK_MAX_AGE:28,RETIREMENT_AVAILABLE_AGE:34,CAREER_END_AGE:42};
function initial(){const r=Math.random();if(r<.16)return 75;if(r<.34)return 76;if(r<.55)return 77;if(r<.75)return 78;if(r<.92)return 79;return 80;}
function peakAge(){const w=[10,9,9,9,9,9,9,9,8,8,7,6,5,3];let r=Math.random()*w.reduce((a,b)=>a+b,0);for(let i=0;i<w.length;i++){r-=w[i];if(r<=0)return 15+i;}return 28;}
export function createPotentialProfile(base=null){const x=clamp(Math.round(n(base,initial())),75,80);return{base:x,current:x,min:Math.max(69,x-15),max:Math.min(99,x+15),exceptionalMax:99,peakAge:peakAge(),peakStrength:Number((.9+Math.random()*.2).toFixed(2)),seasonPerformance:{weightedRating:0,matches:0},history:[]};}
function ensure(player){if(!player)return null;if(!player.potentialProfile){const legacy=Number(player.potential);player.potentialProfile=createPotentialProfile(Number.isFinite(legacy)?legacy:null);if(Number.isFinite(legacy))player.potentialProfile.current=clamp(Math.round(legacy),69,99);}const p=player.potentialProfile;p.base=clamp(Math.round(n(p.base,78)),75,80);p.min=Math.max(69,p.base-15);p.max=Math.min(99,p.base+15);p.exceptionalMax=99;p.current=clamp(Math.round(n(p.current,player.potential??p.base)),p.min,99);p.seasonPerformance||={weightedRating:0,matches:0};p.history||=[];player.potential=p.current;return p;}
function seasonChange(player,report={}){const p=ensure(player),matches=Math.max(0,Math.round(n(report.matches))),rating=n(report.averageRating);if(!p||matches<12||rating<=0)return 0;if(rating<6)return matches>=16?-1:0;if(rating<6.9)return 0;const threshold=p.current<85?6.9:p.current<90?7.05:p.current<95?7.2:7.35;if(rating<threshold)return 0;if(rating>=7.8&&matches>=24){const chance=p.current<85?.1:p.current<90?.06:p.current<95?.025:.008;if(Math.random()<chance)return 2;}return 1;}
export const PotentialSystem={RULES:POTENTIAL_RULES,createProfile(base=null){return createPotentialProfile(base);},ensure(player){return ensure(player);},addMomentum(){return 0;},calculateSeasonMomentum(){return 0;},momentumToPotentialChange(){return 0;},exceptionalUpgradeChance(){return 0;},recordTraining(){},recordConsequenceChanges(){},recordMatch(player,summary={},matches=0){const p=ensure(player),games=Math.max(0,n(matches)),rating=n(summary.rating??summary.averageRating);if(!p||!games||rating<=0)return;p.seasonPerformance.weightedRating+=rating*games;p.seasonPerformance.matches+=games;},getPeakMultiplier(player){const p=ensure(player);if(!p)return 1;const d=Math.abs(n(player.age,14)-n(p.peakAge,22));return d===0?1.05:d<=2?1.02:1;},getPeakState(player){const p=ensure(player);if(!p)return'stable';const d=Math.abs(n(player.age,14)-n(p.peakAge,22));return d===0?'pic':d<=2?'fenetre_explosion':d<=5?'approche':'stable';},finalizeSeason(player,report={}){const p=ensure(player);if(!p)return null;const matches=Math.max(0,Math.round(n(report.matches,p.seasonPerformance.matches)));const avg=p.seasonPerformance.matches>0?p.seasonPerformance.weightedRating/p.seasonPerformance.matches:0;const rating=n(report.averageRating,avg),before=p.current,change=seasonChange(player,{matches,averageRating:rating});p.current=clamp(before+change,p.min,99);player.potential=p.current;const result={season:report.seasonLabel||null,age:player.age,before,after:p.current,change,matches,averageRating:Number(rating.toFixed(2)),goals:Math.max(0,n(report.goals)),assists:Math.max(0,n(report.assists)),performanceDriven:true};p.history.push(result);if(p.history.length>20)p.history.shift();p.seasonPerformance={weightedRating:0,matches:0};return result;},advanceAge(player){if(!player)return;const p=ensure(player);player.age=Math.min(42,n(player.age,14)+1);if(p)player.potential=p.current;}};
export default PotentialSystem;
