import { VIEWPORT, PITCH, FEEL_RULES, createPlayerFeelState, stepPlayerFeel, mannequinPose } from "./playerFeelModelV04.js";

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),hud=document.querySelector('#hud-detail');
const moveRoot=document.querySelector('#move-joystick'),moveKnob=document.querySelector('#move-stick'),rapidButton=document.querySelector('#rapid');
const CAMERA_VIEW=Object.freeze({rotation:-8*Math.PI/180,verticalScale:.86});
let state=createPlayerFeelState(),accumulator=0,previous=performance.now();

function bindStick(root,knob){const stick={x:0,y:0,pointer:null};const paint=()=>knob.style.transform=`translate(calc(-50% + ${stick.x*28}px),calc(-50% + ${stick.y*28}px))`;const sample=e=>{const r=root.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/(r.width*.34),y=(e.clientY-r.top-r.height/2)/(r.height*.34);const m=Math.hypot(x,y);if(m>1){x/=m;y/=m;}if(Math.hypot(x,y)<.06){x=0;y=0;}stick.x=x;stick.y=y;paint();};const release=e=>{if(e.pointerId!==stick.pointer)return;stick.pointer=null;stick.x=0;stick.y=0;paint();};root.addEventListener('pointerdown',e=>{e.preventDefault();stick.pointer=e.pointerId;root.setPointerCapture?.(e.pointerId);sample(e);});root.addEventListener('pointermove',e=>{if(e.pointerId===stick.pointer)sample(e);});root.addEventListener('pointerup',release);root.addEventListener('pointercancel',release);root.addEventListener('lostpointercapture',release);stick.reset=()=>{stick.x=stick.y=0;stick.pointer=null;paint();};return stick;}
const moveStick=bindStick(moveRoot,moveKnob),rapid={held:false,pointer:null};
rapidButton.addEventListener('pointerdown',e=>{e.preventDefault();rapid.pointer=e.pointerId;rapid.held=true;rapidButton.classList.add('active');rapidButton.setPointerCapture?.(e.pointerId);});
function releaseRapid(e){if(e.pointerId!==rapid.pointer)return;rapid.held=false;rapid.pointer=null;rapidButton.classList.remove('active');}
rapidButton.addEventListener('pointerup',releaseRapid);rapidButton.addEventListener('pointercancel',releaseRapid);rapidButton.addEventListener('lostpointercapture',releaseRapid);
document.querySelector('#restart').addEventListener('click',()=>{state=createPlayerFeelState();moveStick.reset();rapid.held=false;rapidButton.classList.remove('active');});

function drawPitch(){ctx.fillStyle='#163d2e';ctx.fillRect(0,0,PITCH.width,PITCH.height);for(let x=0;x<PITCH.width;x+=110){ctx.fillStyle=Math.floor(x/110)%2?'#194735':'#17412f';ctx.fillRect(x,0,110,PITCH.height);}ctx.strokeStyle='rgba(243,246,239,.55)';ctx.lineWidth=3;ctx.strokeRect(PITCH.inset,PITCH.inset,PITCH.width-PITCH.inset*2,PITCH.height-PITCH.inset*2);ctx.beginPath();ctx.moveTo(PITCH.width/2,PITCH.inset);ctx.lineTo(PITCH.width/2,PITCH.height-PITCH.inset);ctx.stroke();ctx.beginPath();ctx.arc(PITCH.width/2,PITCH.height/2,92,0,Math.PI*2);ctx.stroke();}
function limb(a,b,w,c){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
function joint(p,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();}
function drawPlayer(){const pose=mannequinPose(state),p=state.player,left=pose.plantedFoot==='left',right=pose.plantedFoot==='right';ctx.save();ctx.globalAlpha=.2;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(p.x+5,p.y+8,27,13,p.facing,0,Math.PI*2);ctx.fill();ctx.restore();
limb(pose.leftShoulder,pose.leftElbow,7,'#d7aa84');limb(pose.leftElbow,pose.leftHand,6,'#d7aa84');limb(pose.rightShoulder,pose.rightElbow,7,'#d7aa84');limb(pose.rightElbow,pose.rightHand,6,'#d7aa84');joint(pose.leftHand,4.2,'#d7aa84');joint(pose.rightHand,4.2,'#d7aa84');
limb(pose.hip,pose.leftKnee,9,'#e8e6df');limb(pose.leftKnee,pose.leftFoot,8,'#d6d4cd');limb(pose.hip,pose.rightKnee,9,'#e8e6df');limb(pose.rightKnee,pose.rightFoot,8,'#d6d4cd');joint(pose.leftFoot,left?7:5.5,left?'#e7af3f':'#f0eee8');joint(pose.rightFoot,right?7:5.5,right?'#e7af3f':'#f0eee8');limb(pose.hip,pose.torso,10,'#0d1218');
ctx.save();ctx.translate(pose.torso.x,pose.torso.y);ctx.rotate(p.facing);ctx.fillStyle='#10161d';ctx.strokeStyle='#f1efe8';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-14,-10,29,20,8);ctx.fill();ctx.stroke();ctx.fillStyle='#e7af3f';ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('8',1,0);ctx.restore();joint(pose.head,8.5,'#d7aa84');
if(p.mode==='plant'){ctx.strokeStyle='rgba(231,175,63,.78)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pose.plantAnchor?.x??p.x,pose.plantAnchor?.y??p.y,18,0,Math.PI*2);ctx.stroke();}}
function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,VIEWPORT.width,VIEWPORT.height);ctx.save();ctx.translate(VIEWPORT.width/2,VIEWPORT.height/2);ctx.rotate(CAMERA_VIEW.rotation);ctx.scale(1,CAMERA_VIEW.verticalScale);ctx.translate(-state.camera.x,-state.camera.y);drawPitch();drawPlayer();ctx.restore();const p=state.player;hud.textContent=`V0.4 · caméra inclinée · ${Math.round(p.speed)} u/s · buste ${p.torsoLeanDegrees.toFixed(1)}° · ${p.mode}`;}
function frame(now){const elapsed=Math.min(.08,(now-previous)/1000);previous=now;accumulator=Math.min(accumulator+elapsed,FEEL_RULES.fixedStep*4);while(accumulator>=FEEL_RULES.fixedStep){state=stepPlayerFeel(state,{moveX:moveStick.x,moveY:moveStick.y,rapidHeld:rapid.held},FEEL_RULES.fixedStep);accumulator-=FEEL_RULES.fixedStep;}render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
