export const CONTENT_FAMILIES = Object.freeze({
  CAREER_SCENE: 'career_scene',
  DIALOGUE: 'dialogue',
  INNER_VOICE: 'inner_voice',
  MATCH_DECISION: 'match_decision',
  WORLD_REACTION: 'world_reaction',
  LANDMARK: 'landmark',
});

const entry = (value) => Object.freeze({
  minAge: 13,
  maxAge: 40,
  careerStages: [],
  contexts: [],
  emotionalStates: [],
  requiredFacts: [],
  excludedFacts: [],
  tags: [],
  rarity: 'common',
  ...value,
});

export const STREET_TO_PRO_CONTENT = Object.freeze([
  entry({ id: 'scene_youth_bus_after_loss', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 13, maxAge: 17, careerStages: ['academy', 'youth'], contexts: ['after_match', 'loss'], emotionalStates: ['frustrated', 'quiet'], text: "Dans le bus, personne ne parle vraiment. Ton sac est entre tes chaussures et tu repasses encore l'action que tu aurais dû mieux jouer.", tags: ['youth', 'after-match', 'intimacy'] }),
  entry({ id: 'scene_youth_school_morning_after_big_game', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 13, maxAge: 17, careerStages: ['academy', 'youth'], contexts: ['school', 'after_match'], requiredFacts: ['notableYouthPerformance'], text: "Le lendemain matin, les cours reprennent comme si rien ne s'était passé. Deux élèves se retournent pourtant quand tu entres dans la salle.", tags: ['youth', 'school', 'recognition'] }),
  entry({ id: 'scene_first_team_training_silence', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 16, careerStages: ['reserve', 'professional'], contexts: ['training', 'first_team'], requiredFacts: ['firstTeamTraining'], text: "Le rythme est plus sec, les consignes plus courtes. Ici, personne ne ralentit pour te laisser comprendre.", tags: ['first-team', 'training', 'pressure'], rarity: 'uncommon' }),
  entry({ id: 'scene_bench_after_warmup', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 15, contexts: ['matchday', 'bench'], emotionalStates: ['frustrated', 'impatient'], text: "Tu termines ton échauffement et tu reviens t'asseoir. Les crampons sont prêts. Pour l'instant, le coach ne t'appelle pas.", tags: ['bench', 'coach', 'waiting'] }),
  entry({ id: 'scene_home_injury_evening', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 13, contexts: ['home', 'injury'], requiredFacts: ['injured'], text: "Le sac d'entraînement reste dans l'entrée. Ce soir, tu regardes les autres jouer sans pouvoir faire autre chose que compter les jours.", tags: ['injury', 'home', 'absence'] }),
  entry({ id: 'scene_transfer_hotel_first_night', family: CONTENT_FAMILIES.CAREER_SCENE, minAge: 17, careerStages: ['professional'], contexts: ['transfer', 'arrival'], requiredFacts: ['completedTransfer'], text: "La chambre d'hôtel est silencieuse. Sur la chaise, il y a déjà les couleurs de ton nouveau club. Demain, tout recommence.", tags: ['transfer', 'arrival', 'new-club'], rarity: 'uncommon' }),

  entry({ id: 'dialogue_formative_coach_patience', family: CONTENT_FAMILIES.DIALOGUE, minAge: 13, maxAge: 18, careerStages: ['academy', 'youth'], contexts: ['coach', 'development'], speaker: 'coach', relationBands: ['trusted', 'close'], text: "Je sais que tu veux aller vite. Moi, je veux que tu sois encore là quand les autres auront arrêté de progresser.", tags: ['coach', 'development', 'bond'] }),
  entry({ id: 'dialogue_coach_bench_tension', family: CONTENT_FAMILIES.DIALOGUE, minAge: 15, contexts: ['coach', 'bench'], speaker: 'coach', relationBands: ['tense', 'neutral'], text: "Tu veux jouer, je le sais. Mais aujourd'hui, ce que j'attends de toi, c'est ta réaction avant ta prochaine chance.", tags: ['coach', 'bench', 'tension'] }),
  entry({ id: 'dialogue_parent_after_bad_match', family: CONTENT_FAMILIES.DIALOGUE, minAge: 13, maxAge: 18, contexts: ['family', 'after_match', 'bad_performance'], speaker: 'parent', text: "Tu peux être déçu. Mais ne fais pas comme si un mauvais match effaçait tout le travail d'avant.", tags: ['family', 'support', 'youth'] }),
  entry({ id: 'dialogue_teammate_first_start', family: CONTENT_FAMILIES.DIALOGUE, minAge: 15, contexts: ['locker_room', 'first_start'], requiredFacts: ['firstStart'], speaker: 'teammate', text: "Ne change rien parce que ton nom est sur la feuille. Fais juste ce qui t'a amené jusque-là.", tags: ['teammate', 'first-start', 'locker-room'], rarity: 'uncommon' }),
  entry({ id: 'dialogue_agent_first_interest', family: CONTENT_FAMILIES.DIALOGUE, minAge: 16, contexts: ['agent', 'transfer_interest'], requiredFacts: ['clubInterest'], speaker: 'agent', text: "Ils se renseignent. Ce n'est pas une offre, pas encore. Le pire serait de commencer à jouer pour eux au lieu de jouer pour toi.", tags: ['agent', 'transfer', 'interest'] }),
  entry({ id: 'dialogue_journalist_breakthrough', family: CONTENT_FAMILIES.DIALOGUE, minAge: 16, careerStages: ['professional'], contexts: ['media', 'interview'], requiredFacts: ['firstProAppearance'], speaker: 'journalist', text: "Il y a quelques semaines, peu de gens connaissaient ton nom. Qu'est-ce qui a changé pour toi depuis que tout le monde te regarde ?", tags: ['media', 'breakthrough', 'pressure'] }),

  entry({ id: 'inner_bad_match_denial', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 13, contexts: ['after_match', 'bad_performance'], emotionalStates: ['disappointed', 'frustrated'], text: "J'ai dit que ça allait. Mais je sais très bien que j'ai raté mon match.", tags: ['self-criticism', 'after-match'] }),
  entry({ id: 'inner_not_in_starting_xi', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 14, contexts: ['matchday', 'bench'], emotionalStates: ['hurt', 'frustrated', 'impatient'], text: "Le coach n'a même pas regardé dans ma direction quand il a annoncé le onze.", tags: ['bench', 'coach', 'rejection'] }),
  entry({ id: 'inner_two_goals_attention', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 13, contexts: ['after_match', 'good_performance'], requiredFacts: ['scoredBrace'], emotionalStates: ['proud', 'surprised'], text: "Deux buts et tout le monde me parle différemment. C'est bizarre comme ça va vite.", tags: ['success', 'recognition'] }),
  entry({ id: 'inner_parent_patience_bench', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 13, maxAge: 18, contexts: ['bench', 'family'], emotionalStates: ['impatient', 'frustrated'], text: "Papa dit que je dois être patient. Facile à dire quand c'est pas toi qui regardes les autres jouer.", tags: ['family', 'bench', 'youth'] }),
  entry({ id: 'inner_social_post_reread', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 13, contexts: ['media', 'social'], requiredFacts: ['publicMention'], text: "J'ai vu mon nom passer sur leur compte. J'ai fait semblant de m'en foutre. J'ai regardé quatre fois.", tags: ['social-media', 'recognition', 'vulnerability'] }),
  entry({ id: 'inner_good_not_enough', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 15, contexts: ['career', 'competition'], emotionalStates: ['lucid', 'frustrated'], text: "Je commence à comprendre un truc : être bon ne suffit pas toujours.", tags: ['career', 'competition', 'maturity'] }),
  entry({ id: 'inner_youth_first_team_training', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 15, maxAge: 18, careerStages: ['academy', 'youth', 'reserve'], contexts: ['training', 'first_team'], requiredFacts: ['firstTeamTraining'], emotionalStates: ['nervous', 'excited'], text: "J'essaie de faire comme si c'était un entraînement normal. Mon cœur, lui, n'a pas reçu le message.", tags: ['first-team', 'youth', 'nerves'], rarity: 'uncommon' }),
  entry({ id: 'inner_pro_bad_run', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 18, careerStages: ['professional'], contexts: ['career', 'bad_form'], requiredFacts: ['poorRunOfForm'], emotionalStates: ['doubt', 'frustrated'], text: "Avant, je pensais qu'une mauvaise période, ça se réglait au match suivant. Là, j'apprends à vivre dedans.", tags: ['professional', 'bad-form', 'doubt'] }),
  entry({ id: 'inner_injury_return_fear', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 14, contexts: ['injury', 'return'], requiredFacts: ['returningFromInjury'], emotionalStates: ['nervous', 'determined'], text: "Tout le monde me demande si je suis prêt. Je crois que oui. Je sais juste pas encore si mon corps y croit aussi.", tags: ['injury', 'return', 'fear'], rarity: 'uncommon' }),
  entry({ id: 'inner_first_contract_signature', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 16, contexts: ['contract', 'landmark'], requiredFacts: ['firstProfessionalContract'], emotionalStates: ['proud', 'overwhelmed'], text: "J'ai signé mon nom comme d'habitude. Sauf que cette fois, rien n'était habituel.", tags: ['contract', 'first', 'landmark'], rarity: 'rare' }),
  entry({ id: 'inner_transfer_departure', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 16, contexts: ['transfer', 'departure'], requiredFacts: ['completedTransfer'], emotionalStates: ['excited', 'nostalgic'], text: "Je voulais que ça arrive. Maintenant que c'est fait, je regarde une dernière fois un vestiaire que je pensais connaître par cœur.", tags: ['transfer', 'departure', 'ambivalence'], rarity: 'rare' }),
  entry({ id: 'inner_media_pressure_pro', family: CONTENT_FAMILIES.INNER_VOICE, minAge: 17, careerStages: ['professional'], contexts: ['media', 'pressure'], requiredFacts: ['firstProAppearance'], text: "Quand personne ne parlait de moi, je voulais être vu. Maintenant, j'apprends ce que ça coûte d'être regardé.", tags: ['media', 'professional', 'pressure'] }),

  entry({ id: 'decision_youth_risky_dribble', family: CONTENT_FAMILIES.MATCH_DECISION, minAge: 13, maxAge: 18, careerStages: ['academy', 'youth'], contexts: ['match', 'wide_area', 'one_v_one'], prompt: "Ton latéral hésite à sortir. Tu reçois près de la ligne, avec quelques mètres pour provoquer.", choices: [{ id: 'attack', label: 'Le fixer et tenter de passer' }, { id: 'combine', label: 'Chercher le une-deux' }, { id: 'secure', label: 'Revenir et garder le ballon' }], tags: ['match', 'youth', 'choice'] }),
  entry({ id: 'decision_pro_late_cross_or_hold', family: CONTENT_FAMILIES.MATCH_DECISION, minAge: 17, careerStages: ['professional'], contexts: ['match', 'late_game', 'leading'], prompt: "Tu arrives dans les trente derniers mètres. Ton équipe mène et deux partenaires attaquent la surface.", choices: [{ id: 'cross', label: 'Mettre le ballon dans la surface' }, { id: 'corner', label: 'Gagner du temps près du corner' }, { id: 'recycle', label: 'Rejouer derrière pour garder le contrôle' }], tags: ['match', 'professional', 'game-management'] }),
  entry({ id: 'decision_after_mistake_response', family: CONTENT_FAMILIES.MATCH_DECISION, minAge: 13, contexts: ['match', 'after_mistake'], prompt: "Tu viens de perdre un ballon dangereux. Le jeu continue et l'adversaire ressort de ta zone.", choices: [{ id: 'chase', label: 'Sprinter pour réparer immédiatement' }, { id: 'reset', label: 'Reprendre ta position et rester lucide' }, { id: 'demand', label: 'Réclamer tout de suite le prochain ballon' }], tags: ['match', 'mistake', 'mentality'] }),
  entry({ id: 'decision_first_start_early_touch', family: CONTENT_FAMILIES.MATCH_DECISION, minAge: 15, contexts: ['match', 'first_start', 'opening_minutes'], requiredFacts: ['firstStart'], prompt: "Première titularisation. Ton premier ballon arrive vite, dos au jeu, avec un adversaire déjà dans ton dos.", choices: [{ id: 'simple', label: 'Jouer simple en une touche' }, { id: 'turn', label: 'Tenter de te retourner' }, { id: 'draw_foul', label: 'Protéger et chercher le contact' }], tags: ['match', 'first-start', 'pressure'], rarity: 'rare' }),

  entry({ id: 'world_social_youth_local_buzz', family: CONTENT_FAMILIES.WORLD_REACTION, minAge: 13, maxAge: 18, careerStages: ['academy', 'youth'], contexts: ['social', 'after_match'], requiredFacts: ['notableYouthPerformance'], source: 'local_supporter', text: "On parle beaucoup de lui cette semaine. Qu'on le laisse jouer et grandir tranquille.", tags: ['social', 'youth', 'local'] }),
  entry({ id: 'world_social_pro_breakthrough_hype', family: CONTENT_FAMILIES.WORLD_REACTION, minAge: 16, careerStages: ['professional'], contexts: ['social', 'after_match'], requiredFacts: ['firstProAppearance', 'goodPerformance'], source: 'supporter', text: "Il n'a pas joué comme quelqu'un qui découvrait ce niveau. À revoir très vite.", tags: ['social', 'professional', 'breakthrough'] }),
  entry({ id: 'world_media_bad_form_scrutiny', family: CONTENT_FAMILIES.WORLD_REACTION, minAge: 17, careerStages: ['professional'], contexts: ['media', 'bad_form'], requiredFacts: ['poorRunOfForm', 'firstProAppearance'], source: 'press', text: "La période est plus compliquée. Le talent n'est pas remis en cause, mais sa réponse dans les prochaines semaines sera observée.", tags: ['media', 'bad-form', 'scrutiny'] }),
  entry({ id: 'world_teammate_goal_praise', family: CONTENT_FAMILIES.WORLD_REACTION, minAge: 13, contexts: ['locker_room', 'after_match'], requiredFacts: ['scoredImportantGoal'], source: 'teammate', text: "Ce soir, c'est lui qui nous sort de là. Demain on le chambrera, mais là il peut profiter.", tags: ['locker-room', 'goal', 'teammate'] }),
  entry({ id: 'world_supporter_transfer_departure', family: CONTENT_FAMILIES.WORLD_REACTION, minAge: 16, contexts: ['social', 'transfer'], requiredFacts: ['completedTransfer'], source: 'supporter', text: "Ça fait bizarre de le voir partir. On savait que ça pouvait arriver, mais pas que ça ferait cet effet-là.", tags: ['social', 'transfer', 'supporter'], rarity: 'uncommon' }),

  entry({ id: 'landmark_first_pro_contract', family: CONTENT_FAMILIES.LANDMARK, minAge: 16, contexts: ['contract'], requiredFacts: ['firstProfessionalContract'], title: 'Premier contrat professionnel', text: "Le document est signé. Pour la première fois, le football n'est plus seulement ce que tu poursuis : c'est officiellement ton métier.", tags: ['contract', 'first', 'career'], rarity: 'rare' }),
  entry({ id: 'landmark_first_start', family: CONTENT_FAMILIES.LANDMARK, minAge: 15, contexts: ['matchday'], requiredFacts: ['firstStart'], title: 'Première titularisation', text: "Cette fois, ton nom n'est pas là pour attendre. Tu commences le match.", tags: ['match', 'first-start', 'career'], rarity: 'rare' }),
  entry({ id: 'landmark_first_goal', family: CONTENT_FAMILIES.LANDMARK, minAge: 13, contexts: ['after_match'], requiredFacts: ['firstGoal'], title: 'Premier but', text: "Tu as déjà imaginé ce moment. Pas ce bruit-là, pas cette seconde précise. Celui-ci, personne ne pourra te le refaire une deuxième fois.", tags: ['goal', 'first', 'career'], rarity: 'rare' }),
  entry({ id: 'landmark_first_transfer', family: CONTENT_FAMILIES.LANDMARK, minAge: 16, contexts: ['transfer'], requiredFacts: ['firstTransfer'], title: 'Premier transfert', text: "Un club devient un souvenir, un autre devient ton présent. Pour la première fois, ta carrière change d'adresse.", tags: ['transfer', 'first', 'career'], rarity: 'rare' }),
  entry({ id: 'landmark_return_from_injury', family: CONTENT_FAMILIES.LANDMARK, minAge: 14, contexts: ['injury', 'return'], requiredFacts: ['returningFromInjury'], title: 'Retour', text: "La dernière fois que tu as quitté le terrain, tu ne savais pas quand tu reviendrais. Aujourd'hui, tu remets les crampons pour de vrai.", tags: ['injury', 'return', 'career'], rarity: 'rare' }),
  entry({ id: 'landmark_first_captaincy', family: CONTENT_FAMILIES.LANDMARK, minAge: 18, careerStages: ['professional'], contexts: ['matchday', 'leadership'], requiredFacts: ['firstCaptaincy'], title: 'Le brassard', text: "Le morceau de tissu ne change pas ton jeu. Mais quand tu le passes autour du bras, tu comprends que les autres vont aussi regarder ta réaction.", tags: ['captaincy', 'leadership', 'career'], rarity: 'rare' }),
]);

export const CONTENT_BY_FAMILY = Object.freeze(
  Object.values(CONTENT_FAMILIES).reduce((acc, family) => {
    acc[family] = Object.freeze(STREET_TO_PRO_CONTENT.filter((item) => item.family === family));
    return acc;
  }, {}),
);
