export const FIELD=Object.freeze({w:960,h:540,inset:34,goalX:930,goalTop:198,goalBottom:342});
export const PHYSICS=Object.freeze({playerSpeed:248,controlRadius:43,dribbleDistance:31,minShotSpeed:430,maxShotSpeed:820,friction:.986});
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
export function normalizeVector(x=0,y=0){const l=Math.hypot(x,y);return l?{x:x/l,y:y/l,length:l}:{x:0,y:0,length:0};}
export function shotSpeedFromPower(power=0){const p=clamp(Number(power)||0,0,1);return PHYSICS.minShotSpeed+(PHYSICS.maxShotSpeed-PHYSICS.minShotSpeed)*p;}
export function createFootball2DState(){return{status:"playing",goals:0,lastEvent:null,possession:true,player:{x:260,y:FIELD.h/2,facingX:1,facingY:0,vx:0,vy:0},ball:{x:296,y:FIELD.h/2,vx:0,vy:0}};}
function inGoal(y){return y>=FIELD.goalTop&&y<=FIELD.goalBottom;}
function boundBall(ball){const b={...ball};if(b.y<FIELD.inset+7){b.y=FIELD.inset+7;b.vy=Math.abs(b.vy)*.55;}if(b.y>FIELD.h-FIELD.inset-7){b.y=FIELD.h-FIELD.inset-7;b.vy=-Math.abs(b.vy)*.55;}if(b.x<FIELD.inset+7){b.x=FIELD.inset+7;b.vx=Math.abs(b.vx)*.55;}if(b.x>FIELD.goalX&&!inGoal(b.y)){b.x=FIELD.goalX;b.vx=-Math.abs(b.vx)*.5;}return b;}
export function stepFootball2D(state,input={},dt=1/60){const t=clamp(Number(dt)||0,0,.05);const move=normalizeVector(input.moveX??0,input.moveY??0);const p={...state.player};const before={...state.ball};let b={...state.ball};let possession=false;let lastEvent=null;p.vx=move.x*PHYSICS.playerSpeed;p.vy=move.y*PHYSICS.playerSpeed;p.x=clamp(p.x+p.vx*t,FIELD.inset+18,FIELD.w-FIELD.inset-18);p.y=clamp(p.y+p.vy*t,FIELD.inset+18,FIELD.h-FIELD.inset-18);if(move.length>.05){p.facingX=move.x;p.facingY=move.y;}const dist=Math.hypot(b.x-p.x,b.y-p.y);const speed=Math.hypot(b.vx,b.vy);if(input.shootReleased&&dist<=PHYSICS.controlRadius&&speed<360){const s=shotSpeedFromPower(input.shootPower);b.vx=p.facingX*s;b.vy=p.facingY*s;b.x+=p.facingX*8;b.y+=p.facingY*8;lastEvent="shot";}else{b.x+=b.vx*t;b.y+=b.vy*t;const f=Math.pow(PHYSICS.friction,t*60);b.vx*=f;b.vy*=f;if(Math.hypot(b.vx,b.vy)<5){b.vx=0;b.vy=0;}const d=Math.hypot(b.x-p.x,b.y-p.y);if(d<=PHYSICS.controlRadius&&Math.hypot(b.vx,b.vy)<230){const tx=p.x+p.facingX*PHYSICS.dribbleDistance;const ty=p.y+p.facingY*PHYSICS.dribbleDistance;const follow=1-Math.exp(-11*t);b.x+=(tx-b.x)*follow;b.y+=(ty-b.y)*follow;b.vx+=p.vx*.12;b.vy+=p.vy*.12;possession=true;}}b=boundBall(b);if(before.x<FIELD.goalX&&b.x>=FIELD.goalX&&inGoal(b.y)){return{...state,status:"goal",goals:state.goals+1,lastEvent:"goal",player:p,ball:b,possession:false};}return{...state,status:"playing",lastEvent,player:p,ball:b,possession};}
export function resetFootball2DAfterGoal(state){const fresh=createFootball2DState();return{...fresh,goals:state.goals};}
