export const FIELD=Object.freeze({w:960,h:540,inset:34,goalX:930,goalTop:198,goalBottom:342});
export const PHYSICS=Object.freeze({playerSpeed:248,controlRadius:48,dribbleDistance:32,minShotSpeed:430,maxShotSpeed:820,friction:.986,controlFollow:15,recoverySpeed:260});
export const DEFAULT_FEEL_TUNING=Object.freeze({playerSpeed:1,ballControl:1,shotPower:1});
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
export function normalizeFeelTuning(input={}){return{playerSpeed:clamp(Number(input.playerSpeed)||1,.8,1.2),ballControl:clamp(Number(input.ballControl)||1,.7,1.3),shotPower:clamp(Number(input.shotPower)||1,.8,1.2)}}
export function normalizeVector(x=0,y=0){const l=Math.hypot(x,y);return l?{x:x/l,y:y/l,length:l}:{x:0,y:0,length:0};}
export function shotSpeedFromPower(power=0,tuning=DEFAULT_FEEL_TUNING){const p=clamp(Number(power)||0,0,1),feel=normalizeFeelTuning(tuning);return(PHYSICS.minShotSpeed+(PHYSICS.maxShotSpeed-PHYSICS.minShotSpeed)*p)*feel.shotPower;}
export function createFootball2DState(){return{status:"playing",goals:0,lastEvent:null,possession:true,player:{x:260,y:FIELD.h/2,facingX:1,facingY:0,vx:0,vy:0},ball:{x:296,y:FIELD.h/2,vx:0,vy:0}};}
function inGoal(y){return y>=FIELD.goalTop&&y<=FIELD.goalBottom;}
function boundBall(ball){const b={...ball};if(b.y<FIELD.inset+7){b.y=FIELD.inset+7;b.vy=Math.abs(b.vy)*.55;}if(b.y>FIELD.h-FIELD.inset-7){b.y=FIELD.h-FIELD.inset-7;b.vy=-Math.abs(b.vy)*.55;}if(b.x<FIELD.inset+7){b.x=FIELD.inset+7;b.vx=Math.abs(b.vx)*.55;}if(b.x>FIELD.goalX&&!inGoal(b.y)){b.x=FIELD.goalX;b.vx=-Math.abs(b.vx)*.5;}return b;}
export function stepFootball2D(state,input={},dt=1/60,tuning=DEFAULT_FEEL_TUNING){const feel=normalizeFeelTuning(tuning),t=clamp(Number(dt)||0,0,.05),move=normalizeVector(input.moveX??0,input.moveY??0),p={...state.player},before={...state.ball};let b={...state.ball},possession=false,lastEvent=null;p.vx=move.x*PHYSICS.playerSpeed*feel.playerSpeed;p.vy=move.y*PHYSICS.playerSpeed*feel.playerSpeed;p.x=clamp(p.x+p.vx*t,FIELD.inset+18,FIELD.w-FIELD.inset-18);p.y=clamp(p.y+p.vy*t,FIELD.inset+18,FIELD.h-FIELD.inset-18);if(move.length>.05){p.facingX=move.x;p.facingY=move.y;}const dist=Math.hypot(b.x-p.x,b.y-p.y),speed=Math.hypot(b.vx,b.vy),controlling=state.possession||(dist<=PHYSICS.controlRadius&&speed<=PHYSICS.recoverySpeed);if(input.shootReleased&&controlling){const s=shotSpeedFromPower(input.shootPower,feel);b.vx=p.facingX*s;b.vy=p.facingY*s;b.x+=p.facingX*8;b.y+=p.facingY*8;lastEvent="shot";}else if(controlling){const touchDistance=PHYSICS.dribbleDistance*(1+(1-feel.ballControl)*.35),tx=p.x+p.facingX*touchDistance,ty=p.y+p.facingY*touchDistance,follow=1-Math.exp(-(PHYSICS.controlFollow*feel.ballControl)*t);b.x+=(tx-b.x)*follow;b.y+=(ty-b.y)*follow;b.vx=p.vx*.45;b.vy=p.vy*.45;possession=Math.hypot(b.x-p.x,b.y-p.y)<=PHYSICS.controlRadius*1.35;}else{b.x+=b.vx*t;b.y+=b.vy*t;const f=Math.pow(PHYSICS.friction,t*60);b.vx*=f;b.vy*=f;if(Math.hypot(b.vx,b.vy)<5){b.vx=0;b.vy=0;}const d=Math.hypot(b.x-p.x,b.y-p.y);if(d<=PHYSICS.controlRadius&&Math.hypot(b.vx,b.vy)<=PHYSICS.recoverySpeed)possession=true;}b=boundBall(b);if(before.x<FIELD.goalX&&b.x>=FIELD.goalX&&inGoal(b.y)){return{...state,status:"goal",goals:state.goals+1,lastEvent:"goal",player:p,ball:b,possession:false};}return{...state,status:"playing",lastEvent,player:p,ball:b,possession};}
export function resetFootball2DAfterGoal(state){const fresh=createFootball2DState();return{...fresh,goals:state.goals};}
