// Street to Pro — 60 occasions de jeu réservées aux AG / AD.
// Elles racontent le métier d'ailier : 1v1, débordement, rentrée intérieure, appels, centres, transitions et repli.

const c=(text,style,impacts={},gesture=null)=>({text,style,impacts,gesture});
const w=(id,title,description,choices,meta={})=>({id,title,description,choices,positions:['AG','AD'],weight:3,...meta});

export const WINGER_PLAY_OPPORTUNITIES=Object.freeze([
// 01-10 — Duel avec le latéral adverse
w('WNG-001','Ton latéral adverse t’attend arrêté','Tu reçois près de la ligne avec de l’espace pour prendre de la vitesse. Ton vis-à-vis reste bas sur ses appuis et attend ton premier geste.',[
 c('Jouer simple en retrait et repartir','safe',{ratingBonus:.1,passAccuracy:.11},'Remise-replacement'),c('Le provoquer puis déborder','technical',{ratingBonus:.18,duelBonus:.1,fatigueRisk:1,technicalRisk:.12},'Débordement'),c('Rentrer intérieur sur ton premier contrôle','risky',{ratingBonus:.2,duelBonus:.09,assistChance:.04,technicalRisk:.16},'Crochet intérieur')]),
w('WNG-002','Il te ferme complètement la ligne','Ton défenseur direct te montre volontairement l’intérieur et bloque le couloir extérieur.',[
 c('Revenir vers ton milieu','safe',{ratingBonus:.1,passAccuracy:.11},'Retour intérieur'),c('Accepter l’intérieur et combiner','technical',{ratingBonus:.17,passAccuracy:.09,assistChance:.04,technicalRisk:.09},'Combinaison intérieure'),c('Forcer quand même le débordement extérieur','risky',{ratingBonus:.19,duelBonus:.11,fatigueRisk:1,technicalRisk:.18},'Débordement forcé')]),
w('WNG-003','Il te montre la ligne de touche','Ton vis-à-vis ferme ton pied intérieur et t’oblige presque à longer la ligne.',[
 c('Conserver et attendre le soutien du latéral','safe',{ratingBonus:.11,passAccuracy:.1},'Attente du soutien'),c('Accélérer le long de la ligne','technical',{ratingBonus:.18,duelBonus:.1,fatigueRisk:2,technicalRisk:.12},'Accélération extérieure'),c('Tenter le double contact pour rentrer','risky',{ratingBonus:.21,duelBonus:.12,technicalRisk:.19},'Double contact intérieur')]),
w('WNG-004','Ton premier crochet ne l’a pas fait bouger','Le défenseur reste devant toi après ta première feinte. Il semble avoir lu ton geste préféré.',[
 c('Remettre derrière et changer le duel','safe',{ratingBonus:.1,passAccuracy:.1},'Remise'),c('Changer de rythme plutôt que de geste','technical',{ratingBonus:.18,duelBonus:.09,fatigueRisk:1,technicalRisk:.1},'Changement de rythme'),c('Tenter le petit pont','risky',{ratingBonus:.22,duelBonus:.13,technicalRisk:.22},'Petit pont')]),
w('WNG-005','Il recule depuis deux duels','Ton adversaire direct ne vient plus au contact aussi vite. Il protège désormais la profondeur et te laisse avancer.',[
 c('Avancer sans forcer jusqu’à attirer','safe',{ratingBonus:.12,duelBonus:.04},'Conduite patiente'),c('Fixer puis servir ton latéral lancé','technical',{ratingBonus:.18,assistChance:.05,passAccuracy:.09,technicalRisk:.08},'Fixation-décalage'),c('Déclencher une accélération pour l’enfoncer','risky',{ratingBonus:.2,duelBonus:.12,fatigueRisk:2,technicalRisk:.14},'Accélération frontale')],{requiresDuelAdvantage:true}),
w('WNG-006','Il te colle dès la réception','Ton latéral adverse refuse de te laisser te retourner et vient au contact avant même ton premier contrôle.',[
 c('Remettre en une touche','safe',{ratingBonus:.1,passAccuracy:.12},'Remise une touche'),c('Orienter ton contrôle dans son dos','technical',{ratingBonus:.19,duelBonus:.09,technicalRisk:.13},'Contrôle orienté'),c('Utiliser ton corps puis partir côté ligne','risky',{ratingBonus:.18,duelBonus:.11,fatigueRisk:1,technicalRisk:.16},'Protection-départ')]),
w('WNG-007','Le latéral est déjà averti','Ton adversaire direct joue avec un carton jaune et hésite davantage à engager fort le duel.',[
 c('Faire circuler sans chercher la faute','safe',{ratingBonus:.11,passAccuracy:.1},'Jeu simple'),c('Le provoquer balle au pied pour le faire reculer','technical',{ratingBonus:.18,duelBonus:.09,technicalRisk:.1},'Provocation contrôlée'),c('Attaquer franchement son côté pour provoquer un second carton','cunning',{ratingBonus:.19,duelBonus:.1,cardRisk:.02,technicalRisk:.16},'Provocation du duel')],{requiresOpponentYellow:true}),
w('WNG-008','Un deuxième défenseur vient fermer','Ton duel attire un milieu adverse qui vient créer un deux contre un près de la ligne.',[
 c('Revenir rapidement vers l’arrière','safe',{ratingBonus:.11,passAccuracy:.12},'Sortie de pression'),c('Trouver ton latéral dans l’espace libéré','technical',{ratingBonus:.19,passAccuracy:.1,teamBoost:.04,technicalRisk:.09},'Passe au latéral'),c('Tenter de passer entre les deux','risky',{ratingBonus:.22,duelBonus:.14,technicalRisk:.24},'Percée entre deux')]),
w('WNG-009','Il t’attend sur ton mauvais pied','Ton défenseur t’oriente volontairement vers ton pied faible à chaque réception.',[
 c('Revenir intérieur pour jouer simple','safe',{ratingBonus:.1,passAccuracy:.11},'Recyclage intérieur'),c('Utiliser ton pied faible pour centrer tôt','technical',{ratingBonus:.18,assistChance:.06,technicalRisk:.13},'Centre pied faible'),c('Feinter le pied faible puis repartir sur ton fort','risky',{ratingBonus:.2,duelBonus:.11,technicalRisk:.17},'Feinte de pied faible')]),
w('WNG-010','Le duel devient personnel','Après plusieurs contacts et provocations, ton adversaire direct vient encore te chercher dès que tu touches le ballon.',[
 c('L’ignorer et jouer à une touche','safe',{ratingBonus:.12,passAccuracy:.11,teamBoost:.03},'Jeu sans duel'),c('Le fixer puis lâcher au bon moment','technical',{ratingBonus:.19,duelBonus:.07,passAccuracy:.08,technicalRisk:.09},'Fixation froide'),c('Le provoquer encore en un contre un','risky',{ratingBonus:.21,duelBonus:.13,technicalRisk:.19},'Duel assumé')],{requiresRivalry:true}),

// 11-20 — Combinaisons avec le latéral et le milieu
w('WNG-011','Ton latéral dédouble dans ton dos','Tu reçois sur l’aile et ton latéral part immédiatement à pleine vitesse à l’extérieur.',[
 c('Le servir dans sa course','safe',{ratingBonus:.15,passAccuracy:.1,assistChance:.04},'Passe de dédoublement'),c('Feinter la passe puis rentrer intérieur','technical',{ratingBonus:.19,duelBonus:.08,technicalRisk:.11},'Feinte de dédoublement'),c('Garder le ballon et partir toi-même en duel','risky',{ratingBonus:.18,duelBonus:.11,technicalRisk:.16},'Duel individuel')]),
w('WNG-012','Ton latéral passe à l’intérieur','Au lieu de dédoubler, ton latéral attaque le demi-espace et attire un défenseur avec lui.',[
 c('Lui donner dans les pieds','safe',{ratingBonus:.14,passAccuracy:.11},'Passe intérieure'),c('Utiliser son appel pour prendre la ligne','technical',{ratingBonus:.18,duelBonus:.08,technicalRisk:.1},'Appel-leurre'),c('Chercher directement l’attaquant dans la surface','risky',{ratingBonus:.2,assistChance:.08,technicalRisk:.17},'Centre précoce')]),
w('WNG-013','Le MOC vient créer un triangle','Ton milieu offensif se rapproche de toi pendant que ton latéral reste haut. Trois options apparaissent en quelques secondes.',[
 c('Jouer le une-deux avec le MOC','safe',{ratingBonus:.16,passAccuracy:.1,assistChance:.04},'Une-deux'),c('Fixer puis décaler le latéral','technical',{ratingBonus:.18,passAccuracy:.09,teamBoost:.04,technicalRisk:.08},'Fixation-décalage'),c('Tenter la passe entre deux vers l’attaquant','risky',{ratingBonus:.21,assistChance:.09,technicalRisk:.18},'Passe intérieure')]),
w('WNG-014','Ton latéral te demande de rester large','Il te fait signe de ne pas rentrer intérieur pour garder la largeur et étirer leur bloc.',[
 c('Rester large et faire circuler','safe',{ratingBonus:.12,passAccuracy:.11,teamBoost:.04},'Largeur tenue'),c('Attendre puis attaquer le dos du latéral','technical',{ratingBonus:.18,duelBonus:.07,fatigueRisk:1,technicalRisk:.09},'Appel différé'),c('Ignorer la consigne et rentrer entre les lignes','risky',{ratingBonus:.17,assistChance:.05,technicalRisk:.14},'Rentrée intérieure')]),
w('WNG-015','Ton milieu te trouve dans le demi-espace','Tu reçois légèrement à l’intérieur de l’aile, entre le latéral et le milieu adverse.',[
 c('Remettre en une touche au milieu','safe',{ratingBonus:.12,passAccuracy:.12},'Remise intérieure'),c('Te retourner vers la surface','technical',{ratingBonus:.19,duelBonus:.07,assistChance:.04,technicalRisk:.11},'Demi-tour'),c('Glisser directement une passe dans le dos du latéral','risky',{ratingBonus:.21,assistChance:.09,technicalRisk:.17},'Passe de rupture')]),
w('WNG-016','Ton latéral est bloqué derrière toi','Tu as le ballon mais ton partenaire ne peut plus dédoubler. Le couloir commence à se refermer.',[
 c('Revenir vers le milieu','safe',{ratingBonus:.1,passAccuracy:.12},'Recyclage'),c('Attirer puis remettre au latéral libéré','technical',{ratingBonus:.17,passAccuracy:.1,technicalRisk:.08},'Fixation-remise'),c('Accélérer dans l’axe','risky',{ratingBonus:.19,duelBonus:.09,fatigueRisk:1,technicalRisk:.15},'Percée intérieure')]),
w('WNG-017','Le relais revient dans ta course','Après avoir donné au milieu, il te remet immédiatement le ballon derrière le latéral adverse.',[
 c('Contrôler avant de poursuivre','safe',{ratingBonus:.14,duelBonus:.04},'Contrôle de course'),c('Centrer du premier temps','technical',{ratingBonus:.19,assistChance:.08,technicalRisk:.13},'Centre première intention'),c('Piquer directement vers la surface','risky',{ratingBonus:.2,duelBonus:.1,goalChance:.03,technicalRisk:.16},'Percée dans la surface')]),
w('WNG-018','Le milieu adverse suit ton latéral','Son déplacement libère quelques mètres autour de toi dans le demi-espace.',[
 c('Garder la largeur et avancer','safe',{ratingBonus:.12,duelBonus:.03},'Conduite large'),c('Rentrer dans le demi-espace libéré','technical',{ratingBonus:.19,assistChance:.05,technicalRisk:.1},'Rentrée demi-espace'),c('Chercher tout de suite la transversale opposée','risky',{ratingBonus:.18,passAccuracy:.06,technicalRisk:.16},'Renversement depuis l’aile')]),
w('WNG-019','Le une-deux est possible près de la surface','Ton latéral est assez proche pour combiner alors que ton défenseur direct se concentre entièrement sur toi.',[
 c('Jouer le une-deux simple','safe',{ratingBonus:.15,passAccuracy:.1,assistChance:.04},'Une-deux latéral'),c('Feinter le une-deux et partir intérieur','technical',{ratingBonus:.19,duelBonus:.09,technicalRisk:.12},'Feinte de combinaison'),c('Tenter la talonnade dans la course du latéral','risky',{ratingBonus:.22,assistChance:.07,technicalRisk:.2},'Talonnade')]),
w('WNG-020','Le MOC te demande le ballon dans les pieds','Tu peux servir l’intérieur, continuer sur ton duel ou attendre le dédoublement.',[
 c('Servir le MOC et repartir','safe',{ratingBonus:.14,passAccuracy:.11},'Passe-remise'),c('Fixer puis trouver son appel suivant','technical',{ratingBonus:.19,assistChance:.06,technicalRisk:.1},'Fixation-passe'),c('Ignorer l’appui et attaquer ton défenseur','risky',{ratingBonus:.18,duelBonus:.11,technicalRisk:.17},'Un contre un')]),

// 21-30 — Centres et création depuis le couloir
w('WNG-021','Tu as un mètre pour centrer','Le défenseur revient mais tu as juste assez d’espace pour mettre le ballon dans la surface.',[
 c('Centrer fort au premier poteau','safe',{ratingBonus:.15,assistChance:.07,technicalRisk:.08},'Centre tendu'),c('Lever la tête et viser le second poteau','technical',{ratingBonus:.19,assistChance:.09,technicalRisk:.11},'Centre second poteau'),c('Feinter le centre et rentrer','risky',{ratingBonus:.2,duelBonus:.1,goalChance:.03,technicalRisk:.16},'Feinte de centre')]),
w('WNG-022','Le point de penalty est libre','Ton attaquant coupe au premier poteau et libère une zone centrale derrière lui.',[
 c('Mettre le ballon dans la zone libérée','safe',{ratingBonus:.16,assistChance:.08},'Centre en retrait'),c('Attendre une demi-seconde pour ajuster','technical',{ratingBonus:.19,assistChance:.1,technicalRisk:.09},'Centre retardé'),c('Tenter la passe extérieure du pied','risky',{ratingBonus:.22,assistChance:.11,technicalRisk:.18},'Extérieur du pied')]),
w('WNG-023','Deux partenaires attaquent le premier poteau','Le cœur de la surface est encombré mais le second poteau reste moins surveillé.',[
 c('Centrer au second poteau','safe',{ratingBonus:.16,assistChance:.08},'Centre second poteau'),c('Couper ton centre en retrait','technical',{ratingBonus:.19,assistChance:.1,technicalRisk:.1},'Centre en retrait'),c('Tenter un centre très fort entre gardien et défense','risky',{ratingBonus:.21,assistChance:.11,technicalRisk:.17},'Centre zone de vérité')]),
w('WNG-024','Personne n’attaque encore la surface','Tu as de l’espace sur l’aile mais tes partenaires sont encore loin du but.',[
 c('Temporiser pour les attendre','safe',{ratingBonus:.12,teamBoost:.04},'Temporisation'),c('Revenir intérieur pour conserver','technical',{ratingBonus:.14,passAccuracy:.1},'Recyclage intérieur'),c('Centrer tôt dans l’espace malgré tout','risky',{ratingBonus:.17,assistChance:.05,technicalRisk:.15},'Centre précoce')]),
w('WNG-025','Le gardien anticipe le centre','Il fait déjà un pas vers son premier poteau alors que tu approches de la ligne de fond.',[
 c('Centrer en retrait loin de lui','safe',{ratingBonus:.17,assistChance:.09},'Centre en retrait'),c('Lever le ballon au second poteau','technical',{ratingBonus:.19,assistChance:.1,technicalRisk:.11},'Centre lobé'),c('Tenter directement le petit filet','risky',{ratingBonus:.22,goalChance:.08,technicalRisk:.2},'Frappe angle fermé')]),
w('WNG-026','Le centre est bloqué une première fois','Le ballon te revient immédiatement après le contre du défenseur. Il est encore en déséquilibre.',[
 c('Rejouer en retrait','safe',{ratingBonus:.11,passAccuracy:.1},'Remise arrière'),c('Changer d’angle avant de recentrer','technical',{ratingBonus:.19,assistChance:.08,technicalRisk:.1},'Second centre'),c('Attaquer l’espace laissé par le contre','risky',{ratingBonus:.2,duelBonus:.1,technicalRisk:.16},'Percée après contre')]),
w('WNG-027','Tu arrives lancé sur la ligne de fond','Tu as pris de vitesse ton défenseur et tu approches de la limite du terrain.',[
 c('Centrer fort en retrait','safe',{ratingBonus:.17,assistChance:.09},'Centre en retrait'),c('Freiner pour lever la tête','technical',{ratingBonus:.19,assistChance:.1,technicalRisk:.09},'Centre ajusté'),c('Tenter de rentrer toi-même dans les six mètres','risky',{ratingBonus:.21,duelBonus:.1,goalChance:.04,technicalRisk:.17},'Percée ligne de fond')]),
w('WNG-028','Ton attaquant te montre le second poteau','Il ralentit sa course et te fait un signe clair vers la zone opposée.',[
 c('Suivre son appel','safe',{ratingBonus:.16,assistChance:.08},'Centre second poteau'),c('Feinter ce centre puis jouer en retrait','technical',{ratingBonus:.19,assistChance:.09,technicalRisk:.1},'Feinte de centre'),c('Chercher le but directement','risky',{ratingBonus:.21,goalChance:.07,technicalRisk:.19},'Centre-tir')]),
w('WNG-029','Un défenseur coupe toutes les trajectoires hautes','Chaque centre aérien est repoussé depuis plusieurs minutes.',[
 c('Jouer au sol vers l’entrée de la surface','safe',{ratingBonus:.15,assistChance:.07,passAccuracy:.08},'Passe au sol'),c('Centrer fort à mi-hauteur','technical',{ratingBonus:.19,assistChance:.09,technicalRisk:.12},'Centre mi-hauteur'),c('Tenter le centre extérieur derrière lui','risky',{ratingBonus:.21,assistChance:.1,technicalRisk:.18},'Centre extérieur')]),
w('WNG-030','Le latéral adverse protège le centre','Il t’accorde presque l’intérieur pour empêcher tout ballon dans la surface.',[
 c('Revenir vers ton milieu','safe',{ratingBonus:.11,passAccuracy:.11},'Recyclage'),c('Rentrer pour chercher la passe intérieure','technical',{ratingBonus:.18,assistChance:.06,technicalRisk:.1},'Passe intérieure'),c('Attaquer la surface balle au pied','risky',{ratingBonus:.2,duelBonus:.1,goalChance:.04,technicalRisk:.17},'Percée intérieure')]),

// 31-40 — Appels, transitions et profondeur
w('WNG-031','Le ballon est récupéré et tu as cinquante mètres','Ton équipe récupère bas. Devant toi, le couloir est presque totalement vide.',[
 c('Partir immédiatement dans la profondeur','safe',{ratingBonus:.16,fatigueRisk:2,duelBonus:.04},'Appel profond'),c('Rentrer intérieur pour offrir une passe plus courte','technical',{ratingBonus:.15,teamBoost:.04},'Appel intérieur'),c('Attendre puis partir au dernier moment','risky',{ratingBonus:.19,assistChance:.04,technicalRisk:.08},'Appel retardé')]),
w('WNG-032','Ton défenseur te perd de vue','Il regarde le ballon et tourne brièvement la tête loin de toi.',[
 c('Attaquer son dos immédiatement','safe',{ratingBonus:.17,duelBonus:.06,fatigueRisk:1},'Appel dans le dos'),c('Faire un faux appel puis revenir dans les pieds','technical',{ratingBonus:.18,passAccuracy:.07,technicalRisk:.07},'Contre-appel'),c('Croiser ta course dans l’axe','risky',{ratingBonus:.19,goalChance:.03,technicalRisk:.11},'Course croisée')]),
w('WNG-033','Le contre part à trois','Tu accompagnes une transition avec l’attaquant et le milieu axial.',[
 c('Rester large pour étirer','safe',{ratingBonus:.14,teamBoost:.04},'Largeur en transition'),c('Rentrer entre latéral et central','technical',{ratingBonus:.19,assistChance:.06,technicalRisk:.08},'Course demi-espace'),c('Prendre la profondeur plein axe','risky',{ratingBonus:.2,goalChance:.05,fatigueRisk:2,technicalRisk:.12},'Course axiale')]),
w('WNG-034','Le porteur lève la tête','Ton milieu a du temps pour jouer long et cherche déjà ton déplacement.',[
 c('Partir droit dans le dos','safe',{ratingBonus:.16,fatigueRisk:1},'Appel vertical'),c('Faire un appel courbe pour rester en jeu','technical',{ratingBonus:.19,duelBonus:.04,technicalRisk:.06},'Appel courbe'),c('Partir très tôt pour prendre un maximum d’avance','risky',{ratingBonus:.17,technicalRisk:.13},'Appel limite hors-jeu')]),
w('WNG-035','Le ballon change brutalement de côté','Après plusieurs passes courtes à gauche, le jeu est renversé vers ton aile.',[
 c('Contrôler et sécuriser','safe',{ratingBonus:.13,passAccuracy:.09},'Contrôle large'),c('Attaquer immédiatement le latéral isolé','technical',{ratingBonus:.19,duelBonus:.1,technicalRisk:.12},'Duel après renversement'),c('Jouer directement vers la surface sans contrôle','risky',{ratingBonus:.2,assistChance:.07,technicalRisk:.18},'Centre première intention')]),
w('WNG-036','Le latéral adverse est monté très haut','À la récupération, il reste loin derrière toi et son couloir est totalement libre.',[
 c('Partir dans son dos','safe',{ratingBonus:.17,fatigueRisk:2},'Contre dans le couloir'),c('Rentrer intérieur pour forcer le central à sortir','technical',{ratingBonus:.19,duelBonus:.06,technicalRisk:.1},'Transition intérieure'),c('Demander immédiatement le ballon long','risky',{ratingBonus:.2,assistChance:.03,technicalRisk:.13},'Appel long')]),
w('WNG-037','Tu as déjà sprinté plusieurs fois','Une nouvelle transition démarre mais tes jambes commencent à peser.',[
 c('Accompagner sans sprinter à fond','safe',{ratingBonus:.12,fatigueRisk:0},'Course contrôlée'),c('Choisir le bon moment pour accélérer','technical',{ratingBonus:.18,fatigueRisk:1,technicalRisk:.07},'Accélération choisie'),c('Partir encore à pleine vitesse','risky',{ratingBonus:.18,fatigueRisk:3,technicalRisk:.12},'Sprint total')],{requiresFatigue:true}),
w('WNG-038','Tu pars presque au niveau du dernier défenseur','La passe peut arriver à tout moment et la ligne de hors-jeu est très haute.',[
 c('Retarder légèrement ton appel','safe',{ratingBonus:.14,technicalRisk:.04},'Appel retardé'),c('Courber ta course vers l’extérieur','technical',{ratingBonus:.18,duelBonus:.03,technicalRisk:.06},'Course courbe'),c('Jouer la limite et partir immédiatement','risky',{ratingBonus:.19,technicalRisk:.14},'Appel limite')]),
w('WNG-039','Le contre ralentit près de la surface','La défense a eu le temps de revenir et ton avantage de vitesse disparaît.',[
 c('Conserver et attendre les soutiens','safe',{ratingBonus:.12,passAccuracy:.1},'Transition stabilisée'),c('Fixer le latéral avant de jouer intérieur','technical',{ratingBonus:.18,assistChance:.05,technicalRisk:.09},'Fixation transition'),c('Forcer encore le duel extérieur','risky',{ratingBonus:.19,duelBonus:.1,technicalRisk:.17},'Duel tardif')]),
w('WNG-040','Ton équipe est menée en fin de match','Chaque récupération donne l’impression qu’il faut attaquer plus vite, mais les espaces restent dangereux.',[
 c('Jouer vite mais garder une solution de soutien','safe',{ratingBonus:.14,passAccuracy:.09,teamBoost:.04},'Transition maîtrisée'),c('Prendre immédiatement la profondeur','technical',{ratingBonus:.19,fatigueRisk:1,assistChance:.04,technicalRisk:.09},'Appel urgent'),c('Porter seul le contre le plus loin possible','risky',{ratingBonus:.2,duelBonus:.09,fatigueRisk:3,technicalRisk:.17},'Rush de fin de match')],{requiresTrailing:true,minMinute:70}),

// 41-50 — Rentrée intérieure, finition indirecte et création
w('WNG-041','Tu reçois sur ton pied fort à l’intérieur','Ton contrôle t’ouvre immédiatement l’axe et le latéral hésite entre sortir ou protéger la profondeur.',[
 c('Décaler le milieu qui arrive','safe',{ratingBonus:.14,passAccuracy:.1,assistChance:.03},'Décalage intérieur'),c('Fixer puis glisser la passe dans le dos','technical',{ratingBonus:.2,assistChance:.09,technicalRisk:.11},'Passe de rupture'),c('Continuer balle au pied vers la surface','risky',{ratingBonus:.19,duelBonus:.09,goalChance:.04,technicalRisk:.15},'Conduite intérieure')]),
w('WNG-042','Le central vient fermer ton intérieur','En rentrant depuis l’aile, tu forces un défenseur central à quitter sa ligne.',[
 c('Remettre au MOC libre','safe',{ratingBonus:.15,passAccuracy:.1},'Remise intérieure'),c('Servir immédiatement l’attaquant dans l’espace libéré','technical',{ratingBonus:.21,assistChance:.1,technicalRisk:.12},'Passe dans le dos du central'),c('Tenter de passer entre latéral et central','risky',{ratingBonus:.22,duelBonus:.12,technicalRisk:.21},'Percée entre deux')]),
w('WNG-043','Ton attaquant décroche vers toi','Il vient créer un appui court et entraîne son défenseur hors de la surface.',[
 c('Jouer dans ses pieds','safe',{ratingBonus:.13,passAccuracy:.11},'Appui attaquant'),c('Jouer avec lui puis prendre sa profondeur','technical',{ratingBonus:.19,assistChance:.05,goalChance:.02,technicalRisk:.09},'Une-deux intérieur'),c('Utiliser son mouvement comme leurre et conduire','risky',{ratingBonus:.2,duelBonus:.09,technicalRisk:.15},'Conduite dans l’axe')]),
w('WNG-044','Le demi-espace est complètement libre','Personne ne suit ton déplacement intérieur pendant quelques secondes.',[
 c('Recevoir puis jouer simple','safe',{ratingBonus:.14,passAccuracy:.11},'Réception demi-espace'),c('Lever la tête et chercher la dernière passe','technical',{ratingBonus:.2,assistChance:.09,technicalRisk:.1},'Création demi-espace'),c('Attaquer directement la défense balle au pied','risky',{ratingBonus:.2,duelBonus:.1,technicalRisk:.17},'Percée demi-espace')]),
w('WNG-045','Le défenseur protège ton crochet intérieur','Il semble désormais attendre exactement ton mouvement préféré vers l’axe.',[
 c('Revenir jouer simple','safe',{ratingBonus:.1,passAccuracy:.11},'Recyclage'),c('Feinter l’intérieur puis déborder','technical',{ratingBonus:.2,duelBonus:.11,technicalRisk:.13},'Contre-pied extérieur'),c('Tenter quand même le crochet intérieur','risky',{ratingBonus:.18,duelBonus:.1,technicalRisk:.2},'Crochet attendu')]),
w('WNG-046','Tu arrives face au jeu à vingt-cinq mètres','Le ballon revient vers toi après une longue possession et personne ne sort immédiatement.',[
 c('Écarter à nouveau vers le latéral','safe',{ratingBonus:.12,passAccuracy:.11},'Écartement'),c('Glisser une passe entre les lignes','technical',{ratingBonus:.19,assistChance:.08,technicalRisk:.11},'Passe intérieure'),c('Porter le ballon vers l’axe pour provoquer','risky',{ratingBonus:.19,duelBonus:.08,fatigueRisk:1,technicalRisk:.15},'Conduite diagonale')]),
w('WNG-047','Le MOC attire deux joueurs','Son positionnement central libère ton couloir intérieur pour quelques secondes.',[
 c('Rester large pour maintenir l’espace','safe',{ratingBonus:.12,teamBoost:.04},'Largeur'),c('Attaquer le demi-espace libéré','technical',{ratingBonus:.19,assistChance:.05,technicalRisk:.08},'Course intérieure'),c('Plonger directement dans la surface','risky',{ratingBonus:.2,goalChance:.05,fatigueRisk:1,technicalRisk:.12},'Appel surface')]),
w('WNG-048','Tu changes d’aile en plein match','Le coach te fait basculer de l’autre côté, face à un nouveau latéral.',[
 c('Commencer simple pour lire son comportement','safe',{ratingBonus:.11,passAccuracy:.1},'Observation du duel'),c('Le tester rapidement intérieur puis extérieur','technical',{ratingBonus:.18,duelBonus:.08,technicalRisk:.11},'Test du nouveau latéral'),c('L’attaquer immédiatement en un contre un','risky',{ratingBonus:.19,duelBonus:.11,technicalRisk:.17},'Premier duel direct')],{requiresSideSwitch:true}),
w('WNG-049','Tu viens de gagner deux duels de suite','Ton défenseur direct commence à défendre plus bas et un milieu vient régulièrement l’aider.',[
 c('Utiliser l’attention pour libérer ton latéral','safe',{ratingBonus:.15,passAccuracy:.09,teamBoost:.05},'Décalage du latéral'),c('Fixer les deux avant de jouer intérieur','technical',{ratingBonus:.21,assistChance:.07,technicalRisk:.11},'Fixation double'),c('Continuer à les provoquer ensemble','risky',{ratingBonus:.23,duelBonus:.14,technicalRisk:.22},'Duel deux contre un')],{requiresDuelAdvantage:true}),
w('WNG-050','Tu n’as presque pas touché le ballon depuis dix minutes','Le jeu passe constamment de l’autre côté et ta prochaine réception peut être importante pour retrouver du rythme.',[
 c('Faire un premier geste simple','safe',{ratingBonus:.11,passAccuracy:.11},'Remise simple'),c('Prendre quelques mètres balle au pied','technical',{ratingBonus:.16,duelBonus:.05,technicalRisk:.08},'Conduite de reprise'),c('Chercher immédiatement le duel','risky',{ratingBonus:.18,duelBonus:.1,technicalRisk:.17},'Duel de relance')],{requiresLowInvolvement:true}),

// 51-60 — Repli, pressing et moments de pression
w('WNG-051','Ton latéral est monté et vous perdez le ballon','Le couloir derrière toi est vide. L’adversaire cherche immédiatement à lancer la transition dans cette zone.',[
 c('Sprinter pour fermer le couloir','safe',{ratingBonus:.15,duelBonus:.04,fatigueRisk:2,opponentThreat:-.04},'Repli immédiat'),c('Fermer l’intérieur et guider vers la ligne','technical',{ratingBonus:.18,duelBonus:.07,opponentThreat:-.05,technicalRisk:.06},'Orientation défensive'),c('Contre-presser directement le porteur','risky',{ratingBonus:.19,duelBonus:.1,fatigueRisk:2,opponentThreat:-.05,cardRisk:.01,technicalRisk:.13},'Contre-pressing')]),
w('WNG-052','Le latéral adverse monte dans ton dos','Tu vois son appel partir pendant que votre bloc défensif coulisse lentement.',[
 c('Le suivre jusqu’au bout','safe',{ratingBonus:.14,fatigueRisk:2,opponentThreat:-.04},'Suivi du latéral'),c('Passer le marquage à ton propre latéral et fermer l’intérieur','technical',{ratingBonus:.17,teamBoost:.04,opponentThreat:-.04},'Transmission du marquage'),c('Rester haut pour préparer le contre','risky',{ratingBonus:.12,assistChance:.03,opponentThreat:.05,technicalRisk:.1},'Position haute')]),
w('WNG-053','Le ballon est perdu à deux mètres de toi','Tu peux tenter de le récupérer immédiatement ou te replacer.',[
 c('Te replacer dans le bloc','safe',{ratingBonus:.12,opponentThreat:-.03},'Repli'),c('Fermer la première passe avant de presser','technical',{ratingBonus:.18,duelBonus:.06,opponentThreat:-.05},'Pressing orienté'),c('Te jeter immédiatement sur le porteur','risky',{ratingBonus:.18,duelBonus:.1,fatigueRisk:1,cardRisk:.01,technicalRisk:.15},'Pressing agressif')]),
w('WNG-054','Votre pressing enferme leur latéral','Il reçoit dos au jeu près de la ligne avec peu de solutions autour de lui.',[
 c('Fermer la passe intérieure','safe',{ratingBonus:.14,opponentThreat:-.04},'Fermeture intérieure'),c('Presser en angle pour l’enfermer','technical',{ratingBonus:.19,duelBonus:.08,opponentThreat:-.05,technicalRisk:.07},'Pressing en angle'),c('Tenter de lui voler directement le ballon','risky',{ratingBonus:.2,duelBonus:.11,opponentThreat:-.05,technicalRisk:.14},'Interception agressive')]),
w('WNG-055','Tu es épuisé mais il faut encore défendre','La fin de match approche et ton latéral adverse continue de monter à chaque possession.',[
 c('Rester compact et économiser tes courses','safe',{ratingBonus:.12,fatigueRisk:0,opponentThreat:-.02},'Bloc compact'),c('Choisir uniquement les courses dangereuses','technical',{ratingBonus:.17,fatigueRisk:1,opponentThreat:-.04},'Gestion des efforts'),c('Continuer à sprinter sur chaque montée','risky',{ratingBonus:.18,fatigueRisk:3,opponentThreat:-.05,technicalRisk:.09},'Repli total')],{requiresFatigue:true,minMinute:70}),
w('WNG-056','Vous menez d’un but à cinq minutes de la fin','Ton latéral te demande de l’aider davantage défensivement tandis que des espaces existent encore en contre.',[
 c('Rester bas et protéger le couloir','safe',{ratingBonus:.15,opponentThreat:-.05},'Protection du couloir'),c('Défendre puis repartir seulement si l’espace est clair','technical',{ratingBonus:.18,assistChance:.03,opponentThreat:-.04,technicalRisk:.06},'Gestion de fin de match'),c('Rester haut pour chercher le but du break','risky',{ratingBonus:.14,goalChance:.03,assistChance:.04,opponentThreat:.05,technicalRisk:.12},'Position de contre')],{requiresLead:true,minMinute:84}),
w('WNG-057','Vous êtes menés et ton latéral te demande encore de défendre','Il reste peu de temps et chaque seconde passée bas t’éloigne du but adverse.',[
 c('Faire quand même le repli demandé','safe',{ratingBonus:.13,opponentThreat:-.04},'Repli discipliné'),c('Fermer l’intérieur puis repartir vite','technical',{ratingBonus:.18,assistChance:.03,opponentThreat:-.03,technicalRisk:.07},'Repli court'),c('Rester haut et assumer le risque','risky',{ratingBonus:.16,goalChance:.04,assistChance:.04,opponentThreat:.06,technicalRisk:.13},'Ailier haut')],{requiresTrailing:true,minMinute:75}),
w('WNG-058','Le coach te demande d’attaquer ton défenseur à chaque ballon','La consigne est claire depuis le bord du terrain : il veut que tu provoques davantage.',[
 c('Choisir seulement les bons duels','safe',{ratingBonus:.13,duelBonus:.04},'Duel sélectionné'),c('L’attaquer dès que tu peux recevoir lancé','technical',{ratingBonus:.19,duelBonus:.1,fatigueRisk:1,technicalRisk:.1},'Provocation ciblée'),c('Chercher le un contre un à chaque réception','risky',{ratingBonus:.2,duelBonus:.13,fatigueRisk:2,technicalRisk:.19},'Provocation systématique')],{requiresCoachSignal:true}),
w('WNG-059','La prolongation étire complètement les couloirs','Les blocs sont fatigués et les distances entre latéral, milieu et central deviennent énormes.',[
 c('Conserver le ballon pour faire souffler ton équipe','safe',{ratingBonus:.14,passAccuracy:.1,fatigueRisk:0},'Conservation en prolongation'),c('Choisir une seule accélération au bon moment','technical',{ratingBonus:.2,duelBonus:.08,fatigueRisk:1,technicalRisk:.09},'Accélération choisie'),c('Attaquer chaque espace malgré la fatigue','risky',{ratingBonus:.21,duelBonus:.11,fatigueRisk:3,technicalRisk:.17},'Percussion prolongation')],{requiresExtraTime:true,requiresFatigue:true}),
w('WNG-060','Une dernière réception sur ton aile','Le temps est presque écoulé. Tu reçois encore une fois face à ton défenseur avec des partenaires qui attaquent la surface.',[
 c('Mettre immédiatement un centre propre','safe',{ratingBonus:.17,assistChance:.08,technicalRisk:.08},'Dernier centre'),c('Fixer une dernière fois avant de centrer','technical',{ratingBonus:.21,assistChance:.1,duelBonus:.05,technicalRisk:.12},'Fixation finale'),c('Tenter de l’éliminer pour créer une situation parfaite','risky',{ratingBonus:.23,duelBonus:.12,assistChance:.08,technicalRisk:.2},'Dernier duel')],{minMinute:88})
]);

function hash(seed){let h=2166136261;for(const ch of String(seed||'winger-play')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function normalizedPosition(position=''){const p=String(position||'').toUpperCase();return ['AG','LW'].includes(p)?'AG':['AD','RW'].includes(p)?'AD':p;}
function allowed(item,ctx={}){
 const p=normalizedPosition(ctx.position);if(!item.positions.includes(p))return false;
 if(item.minMinute&&Number(ctx.minute||0)<item.minMinute)return false;
 if(item.requiresLead&&!(Number(ctx.scoreFor)>Number(ctx.scoreAgainst)))return false;
 if(item.requiresTrailing&&!(Number(ctx.scoreFor)<Number(ctx.scoreAgainst)))return false;
 if(item.requiresFatigue&&Number(ctx.fatigue||0)<55)return false;
 if(item.requiresExtraTime&&ctx.extraTime!==true)return false;
 if(item.requiresOpponentYellow&&ctx.opponentYellow!==true)return false;
 if(item.requiresRivalry&&ctx.rivalry!==true)return false;
 if(item.requiresSideSwitch&&ctx.sideSwitch!==true)return false;
 if(item.requiresLowInvolvement&&ctx.lowInvolvement!==true)return false;
 if(item.requiresCoachSignal&&ctx.coachSignal!==true)return false;
 if(item.requiresDuelAdvantage){const w=Number(ctx.directOpponent?.playerDuelsWon||0),l=Number(ctx.directOpponent?.opponentDuelsWon||0);if(!(w>=1&&w>l))return false;}
 return true;
}
export function selectWingerPlayOpportunity(ctx={}){
 const p=normalizedPosition(ctx.position);if(!['AG','AD'].includes(p))return null;
 const pool=WINGER_PLAY_OPPORTUNITIES.filter(item=>allowed(item,{...ctx,position:p}));if(!pool.length)return null;
 return pool[hash(`${ctx.seed||'winger'}:${ctx.index||0}:${ctx.minute||0}`)%pool.length];
}
export function buildWingerPlayDecision(item,{minute=0}={}){if(!item)return null;return{opportunityId:item.id,title:`${minute}' · ${item.title}`,description:item.description,choices:item.choices.map(x=>({...x,opportunityId:item.id})),isWingerPlayOpportunity:true};}
export function countWingerPlayOpportunities(){return WINGER_PLAY_OPPORTUNITIES.length;}
export default {WINGER_PLAY_OPPORTUNITIES,selectWingerPlayOpportunity,buildWingerPlayDecision,countWingerPlayOpportunities};
