// domain/training/trainingManager.js
const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
export const TECHNIQUES = { FRAPPE_ENROULEE: { name: 'Frappe enroulée', description: 'Option de frappe placée.' }, FINITION_PREMIERE_INTENTION: { name: 'Finition première intention', description: 'Option de finition rapide.' }, APPEL_PROFONDEUR: { name: 'Appel en profondeur', description: 'Option d’appel derrière la défense.' }, PREMIER_CONTROLE: { name: 'Premier contrôle', description: 'Contrôle sous pression plus sûr.' }, PASSE_PROFONDE: { name: 'Passe en profondeur', description: 'Option de passe verticale.' }, CENTRE_TENDU: { name: 'Centre tendu', description: 'Option de centre rapide.' }, DRIBBLE_INTERIEUR: { name: 'Dribble intérieur', description: 'Option de conduite intérieure.' }, INTERCEPTION: { name: 'Lecture des trajectoires', description: 'Option d’interception.' } };
const FOCUS_TYPES = { TECHNIQUE: { name: 'Atelier technique', description: 'Travaille un geste technique.', fitnessCost: 3, techniques: ['PREMIER_CONTROLE', 'PASSE_PROFONDE', 'DRIBBLE_INTERIEUR'] }, FINITION: { name: 'Atelier finition', description: 'Travaille la finition.', fitnessCost: 5, techniques: ['FRAPPE_ENROULEE', 'FINITION_PREMIERE_INTENTION'] }, DEPLACEMENT: { name: 'Atelier déplacements', description: 'Travaille les appels.', fitnessCost: 4, techniques: ['APPEL_PROFONDEUR'] }, DEFENSE: { name: 'Atelier défense', description: 'Travaille la lecture défensive.', fitnessCost: 4, techniques: ['INTERCEPTION'] }, COACH: { name: 'Consigne du coach', description: 'Prépare une consigne pour les prochains matchs.', fitnessCost: 2, techniques: [] }, RECUPERATION: { name: 'Récupération', description: 'Récupère de la forme.', fitnessCost: -15, techniques: [] }, REPOS: { name: 'Repos', description: 'Récupération complète.', fitnessCost: -20, techniques: [] } };
function ensure(player) { player.techniques ||= {}; player.coachInstructions ||= []; player.trainingHistory ||= []; return player; }
function learn(player, key) { const technique = TECHNIQUES[key]; if (!technique) return null; const level = clamp((player.techniques[key] || 0) + 1, 0, 3); player.techniques[key] = level; return { key, name: technique.name, level, maxLevel: 3, description: technique.description }; }
export const TrainingManager = { FOCUS_TYPES, TECHNIQUES, getEffect(key) { return FOCUS_TYPES[key] || FOCUS_TYPES.TECHNIQUE; }, applyTraining(player, focusKey = 'TECHNIQUE') { if (!player) return null; ensure(player); const effect = this.getEffect(focusKey); const before = clamp(num(player.fitness, 80), 0, 100); player.fitness = clamp(before - effect.fitnessCost, 0, 100); let learned = null; const available = effect.techniques.filter(key => (player.techniques[key] || 0) < 3); if (available.length) { available.sort((a, b) => (player.techniques[a] || 0) - (player.techniques[b] || 0)); learned = learn(player, available[0]); } let instruction = null; if (focusKey === 'COACH') { const list = ['Joue simple et limite les pertes de balle.', 'Attaque la profondeur dès que l’espace apparaît.', 'Prends davantage de responsabilités dans les 30 derniers mètres.', 'Reste discipliné et protège ta zone.']; instruction = list[Math.floor(Math.random() * list.length)]; player.coachInstructions.push({ text: instruction, remainingMatches: 2, source: 'Coach' }); if (player.coachInstructions.length > 4) player.coachInstructions.shift(); } const report = { name: effect.name, description: effect.description, fitnessCost: effect.fitnessCost, fitnessBefore: before, fitness: player.fitness, learnedTechnique: learned, coachInstruction: instruction, overall: player.overall, progressionResult: null }; player.trainingHistory.push({ date: Date.now(), focus: focusKey, fitnessBefore: before, fitnessAfter: player.fitness, technique: learned?.key || null, instruction }); if (player.trainingHistory.length > 30) player.trainingHistory.shift(); return report; } };
export default TrainingManager;
