// domain/player/playerSystem.js
// Modèle joueur canonique : une seule source de vérité.
import { PotentialSystem } from '../../potentialSystem.js';
export const FOOTBALL_ATTRIBUTES=['vitesse','acceleration','endurance','puissance','finition','tir','passe','controle','dribble','vision','placement','defense'];
export const MENTAL_ATTRIBUTES=['concentration','sangFroid','decision','regularite','resistancePression'];
const clamp=(v,min=1,max=99)=>Math.min(max,Math.max(min,Math.round(Number(v)||0)));const avg=a=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const ORIGINS={CENTRE_FORMATION:{d:{vitesse:5,acceleration:4,endurance:8,puissance:8,finition:2,tir:2,passe:12,controle:0,dribble:-5,vision:8,placement:10,defense:10}},CLUB_AMATEUR:{d:{vitesse:8,acceleration:7,endurance:5,puissance:5,finition:-2,tir:-2,passe:-8,controle:4,dribble:10,vision:-5,placement:-4,defense:-5}},FUTSAL:{d:{vitesse:5,acceleration:8,endurance:-4,puissance:-10,finition:6,tir:6,passe:12,controle:15,dribble:22,vision:12,placement:3,defense:-8}},STREET:{d:{vitesse:12,acceleration:14,endurance:-3,puissance:-8,finition:5,tir:5,passe:-12,controle:10,dribble:25,vision:2,placement:-8,defense:-15}},ATHLETE:{d:{vitesse:15,acceleration:14,endurance:15,puissance:18,finition:-12,tir:-12,passe:-10,controle:-5,dribble:-15,vision:-3,placement:0,defense:-3}},DEBUTANT_TARDIF:{d:{vitesse:10,acceleration:8,endurance:8,puissance:8,finition:-10,tir:-10,passe:-15,controle:-10,dribble:-18,vision:-5,placement:-10,defense:-10}},FILS_DE_PRO:{d:{vitesse:3,acceleration:3,endurance:2,puissance:2,finition:8,tir:8,passe:10,controle:7,dribble:8,vision:8,placement:7,defense:5}}};
const ROLE_WEIGHTS={attacker:{finition:.25,tir:.12,dribble:.14,vitesse:.10,acceleration:.08,controle:.08,vision:.07,placement:.10,endurance:.02,puissance:.02,passe:.02},midfielder:{passe:.18,vision:.16,controle:.13,dribble:.11,endurance:.09,placement:.10,defense:.07,tir:.06,vitesse:.04,acceleration:.03,finition:.03},defender:{defense:.22,placement:.15,puissance:.13,endurance:.11,vitesse:.08,acceleration:.06,passe:.10,controle:.06,vision:.04,tir:.02,finition:.01},goalkeeper:{defense:.24,placement:.18,puissance:.12,endurance:.08,passe:.08,vision:.08,controle:.05,vitesse:.05,acceleration:.04,tir:.02,finition:.01}};
function roleOf(position){const p=String(position||'').toUpperCase();if(['GK','GB','G'].includes(p))return'goalkeeper';if(['DC','CB','DD','DG','RB','LB','D','LAT'].includes(p))return'defender';if(['MC','CM','MOC','CAM','MD','MG','M','MDEF','MOFF'].includes(p))return'midfielder';return'attacker';}
function normalizeOrigin(origin){return ORIGINS[origin]?origin:'CENTRE_FORMATION';}
export function ensure(player){if(!player)return null;if(!player.attributes)player.attributes={};for(const k of FOOTBALL_ATTRIBUTES)player.attributes[k]=clamp(player.attributes[k]??50);if(!player.mental)player.mental={};if(!player.hidden)player.hidden={};player.hidden.consistency=clamp(player.hidden.consistency??12,1,16);for(const k of MENTAL_ATTRIBUTES)player.mental[k]=clamp(player.mental[k]??50);player.mental.regularite=clamp(player.mental.regularite??player.hidden.consistency*5.5);player.potentialProfile ||= PotentialSystem.createProfile(player.potential);player.potential=player.potentialProfile.current;player.overall=calculateOverall(player);return player;}
export function get(player,key,fallback=50){ensure(player);if(FOOTBALL_ATTRIBUTES.includes(key))return clamp(player.attributes[key]??fallback);if(MENTAL_ATTRIBUTES.includes(key))return clamp(player.mental[key]??fallback);return clamp(fallback);}
export function calculateOverall(player){if(!player.attributes)player.attributes={};for(const k of FOOTBALL_ATTRIBUTES)player.attributes[k]=clamp(player.attributes[k]??50);const weights=ROLE_WEIGHTS[roleOf(player.position)];return clamp(Object.entries(weights).reduce((s,[k,w])=>s+(player.attributes[k]??50)*w,0));}
export function createPlayer({firstname='Joueur',lastname='Inconnu',nationality='France',position='BU',origin='CENTRE_FORMATION',age=14}={}){const o=ORIGINS[normalizeOrigin(origin)];const potentialProfile=PotentialSystem.createProfile();const player={id:Date.now()+rand(0,999999),firstname,lastname,nationality,country:nationality,position,age:Math.max(14,Number(age)||14),origin:normalizeOrigin(origin),attributes:{},mental:{},hidden:{consistency:rand(8,16),bigMatchPlayer:rand(8,16),injuryProneness:rand(4,12)},potentialProfile,potential:potentialProfile.current,overall:0,morale:80,fitness:90,stats:{matchesPlayed:0,goals:0,assists:0,successfulPasses:0,tackles:0,cleanSheets:0,yellowCards:0,averageRating:0},xp:0,canRetire:false,careerEnded:false};for(const key of FOOTBALL_ATTRIBUTES)player.attributes[key]=clamp(40+(o.d[key]||0)+rand(-4,4));player.mental={concentration:clamp(55+(o.d.placement||0)*.25+rand(-6,6)),sangFroid:clamp(52+(o.d.finition||0)*.15+rand(-6,6)),decision:clamp(50+(o.d.vision||0)*.3+rand(-6,6)),regularite:clamp(player.hidden.consistency*5.5),resistancePression:50};player.mental.resistancePression=clamp(avg([player.mental.concentration,player.mental.sangFroid,player.mental.regularite]));player.overall=calculateOverall(player);return player;}
function ageFactor(age){if(age<=17)return .9;if(age<=21)return 1;if(age<=25)return .9;if(age<=28)return .75;if(age<=31)return .6;if(age<=34)return .4;return .2;}
export function applyProgression(player,{rating=0,xp=0,goals=0,assists=0,type='match',ageTick=false}={}){ensure(player);const effectiveRating=Number(rating)||((Number(xp)>0)?(Number(xp)-70)/40:0);let quality=type==='match'?Math.max(0,effectiveRating-6.8)/1.2:type==='finSaison'?Math.max(0,effectiveRating-6.9)/1.4:0;quality+=Math.min(.8,Number(goals)||0)*.1+Math.min(.8,Number(assists)||0)*.06;const points=quality*.12*ageFactor(player.age);if(points>0){const weights=ROLE_WEIGHTS[roleOf(player.position)];for(const [key,w] of Object.entries(weights).sort((a,b)=>b[1]-a[1]).slice(0,6)){const gain=points*w*player.mental.regularite/100;if(gain>.015)player.attributes[key]=clamp(player.attributes[key]+gain);}}if(ageTick){player.age+=1;if(player.age>=31){player.attributes.vitesse=clamp(player.attributes.vitesse-(player.age-30)*.15);player.attributes.acceleration=clamp(player.attributes.acceleration-(player.age-30)*.15);player.attributes.endurance=clamp(player.attributes.endurance-(player.age-30)*.12);}}player.overall=calculateOverall(player);return player;}
export function describe(player){ensure(player);return{football:{...player.attributes},mental:{...player.mental},overall:player.overall,potential:player.potential};}
export default{FOOTBALL_ATTRIBUTES,MENTAL_ATTRIBUTES,createPlayer,ensure,get,calculateOverall,applyProgression,describe};
