// domain/competition/europeanCompetitionSystem.js
// Qualification, calendrier et parcours européen.

import { WorldSystem } from '../world/worldSystem.js';
import { COMPETITIONS, MONTH_INFO, seasonLabel } from './competitionCatalog.js';

function clubEuropeanStrength(club) { return Number(club?.strength || 50) + Number(club?.prestige || 0) * 2; }
export function getEuropeanQualification(player, competition) { if (!player || Number(player.age) < 18 || Number(player.clubLevel) !== 1) return { championsLeague: false, europaLeague: false, rank: null }; const clubs = WorldSystem.getClubs(competition.id), playerClub = WorldSystem.getClub(player.clubId || player.club); if (!playerClub || !clubs.length) return { championsLeague: false, europaLeague: false, rank: null }; const ranking = [...clubs].sort((a, b) => clubEuropeanStrength(b) - clubEuropeanStrength(a)); const rank = ranking.findIndex(c => c.id === playerClub.id) + 1; return { championsLeague: rank >= 1 && rank <= 4, europaLeague: rank >= 5 && rank <= 6, rank }; }
export function europeanPool(player) { const ids = Object.values(COMPETITIONS).filter(c => c.type === 'league' && c.level === 1).map(c => c.id), playerClub = WorldSystem.getClub(player?.clubId || player?.club); return ids.flatMap(id => WorldSystem.getClubs(id)).filter(c => c?.id && c.id !== playerClub?.id).sort((a, b) => clubEuropeanStrength(b) - clubEuropeanStrength(a)); }
export function buildEuropeanLeague(player, seasonYear, random, qualification) { if (!qualification.championsLeague && !qualification.europaLeague) return []; const competition = qualification.championsLeague ? COMPETITIONS.CHAMPIONS_LEAGUE : COMPETITIONS.EUROPA_LEAGUE, pool = europeanPool(player), playerClub = WorldSystem.getClub(player?.clubId || player?.club), months = [9, 9, 10, 10, 11, 12, 1, 1], opponents = []; let cursor = 0; while (opponents.length < 8 && cursor < pool.length) { const club = pool[cursor++]; if (!opponents.some(opponent => opponent.id === club.id)) opponents.push(club); } return opponents.map((opponent, index) => { const home = index % 2 === 0, month = months[index], info = MONTH_INFO[month]; return { id: `${seasonYear}-${month}-${competition.id}-${index + 1}`, competitionId: competition.id, competitionName: competition.name, type: competition.type, month, monthLabel: info.label, seasonYear, matchday: index + 1, venue: home ? 'Domicile' : 'Extérieur', opponent: opponent.name, importance: index >= 6 ? 'major' : 'important', status: 'scheduled', played: false, competitionType: 'continental', phase: 'league_phase', playerClubId: playerClub?.id || player?.clubId || null, opponentClubId: opponent.id, homeClubId: home ? playerClub?.id : opponent.id, awayClubId: home ? opponent.id : playerClub?.id, homeClub: home ? playerClub?.name : opponent.name, awayClub: home ? opponent.name : playerClub?.name, europeanSlot: qualification.championsLeague ? 'UCL' : 'UEL', europeanRound: 'Phase de ligue' }; }); }
export function createEuropeanTournament(player, seasonYear, qualification, seed) { if (!qualification.championsLeague && !qualification.europaLeague) return null; const pool = europeanPool(player).slice(0, 35), playerClub = WorldSystem.getClub(player?.clubId || player?.club), clubs = [playerClub, ...pool].filter(Boolean).slice(0, 36); const standings = clubs.map((club, index) => ({ clubId: club.id, club: club.name, played: 0, points: 0, goalsFor: 0, goalsAgainst: 0, strength: clubEuropeanStrength(club), rank: index + 1 })); const playerRow = standings.find(row => row.clubId === playerClub?.id); if (playerRow) { playerRow.rank = 1; playerRow.points = 0; } standings.sort((a, b) => b.strength - a.strength || String(a.club).localeCompare(String(b.club))); standings.forEach((row, index) => { row.rank = index + 1; }); return { version: 1, seasonYear, seasonLabel: seasonLabel(seasonYear), competition: qualification.championsLeague ? 'CHAMPIONS_LEAGUE' : 'EUROPA_LEAGUE', slot: qualification.championsLeague ? 'UCL' : 'UEL', phase: 'league_phase', leagueMatchesPlayed: 0, leaguePoints: 0, leagueGoalsFor: 0, leagueGoalsAgainst: 0, rank: null, qualified: false, eliminated: false, currentRound: null, standings, fixtures: [], history: [], seed }; }
function makeKnockoutFixture(tournament, player, round, month, opponent, index) { const playerClub = WorldSystem.getClub(player?.clubId || player?.club), home = index % 2 === 0, competition = COMPETITIONS[tournament.competition]; return { id: `${tournament.seasonYear}-${round}-${tournament.slot}-${index + 1}`, competitionId: competition.id, competitionName: competition.name, type: 'continental', competitionType: 'continental', phase: 'knockout', round, month, monthLabel: MONTH_INFO[month].label, seasonYear: tournament.seasonYear, matchday: index + 1, importance: 'major', status: 'scheduled', played: false, playerClubId: playerClub?.id || player?.clubId || null, opponentClubId: opponent?.id || null, opponent: opponent?.name || 'Adversaire européen', venue: home ? 'Domicile' : 'Extérieur', homeClubId: home ? playerClub?.id : opponent?.id, awayClubId: home ? opponent?.id : playerClub?.id, homeClub: home ? playerClub?.name : opponent?.name, awayClub: home ? opponent?.name : playerClub?.name, europeanSlot: tournament.slot, europeanRound: round }; }
export function prepareKnockoutRoute(state) { const tournament = state?.europeanTournament, player = state?.player; if (!tournament || tournament.eliminated || tournament.currentRound) return null; const playerClub = WorldSystem.getClub(player?.clubId || player?.club), row = tournament.standings?.find(item => item.clubId === player?.clubId || item.clubId === playerClub?.id); if (!row) return null; const rank = Number(tournament.rank || row.rank || 18); tournament.rank = rank; if (rank > 24) { tournament.eliminated = true; tournament.phase = 'eliminated'; return null; } const pool = europeanPool(player).filter(club => club.id !== player?.clubId), opponent = pool[Math.min(pool.length - 1, Math.max(0, rank - 1))]; const round = rank <= 8 ? 'Huitièmes de finale' : 'Barrages', month = rank <= 8 ? 3 : 2; tournament.currentRound = round; tournament.phase = 'knockout'; const fixture = makeKnockoutFixture(tournament, player, round, month, opponent, 0); tournament.fixtures = [fixture]; return fixture; }
export function advanceEuropeanRound(state, match) { const tournament = state?.europeanTournament, player = state?.player; if (!tournament || tournament.eliminated) return null; const order = ['Barrages', 'Huitièmes de finale', 'Quarts de finale', 'Demi-finales', 'Finale'], index = order.indexOf(match.round); if (index < 0) return null; if (index === order.length - 1) { tournament.phase = 'winner'; tournament.currentRound = null; tournament.history.push({ round: 'Finale', result: 'Vainqueur', seasonYear: tournament.seasonYear }); return null; } const next = order[index + 1], months = { Barrages: 2, 'Huitièmes de finale': 3, 'Quarts de finale': 4, 'Demi-finales': 4, Finale: 5 }, pool = europeanPool(player).filter(club => club.id !== player?.clubId), opponent = pool[(tournament.history.length + Math.max(0, index)) % Math.max(1, pool.length)]; tournament.currentRound = next; const fixture = makeKnockoutFixture(tournament, player, next, months[next], opponent, tournament.history.length); tournament.fixtures.push(fixture); tournament.history.push({ round: match.round, result: 'Qualification', seasonYear: tournament.seasonYear }); return fixture; }
