// domain/competition/seasonScheduleBuilder.js
// Construction déterministe des calendriers jeunesse et senior.

import { WorldSystem } from '../world/worldSystem.js';
import { SEASON_MONTHS, MONTH_INFO } from './competitionCatalog.js';

function hashSeed(input) { let h = 2166136261; for (let i = 0; i < String(input).length; i += 1) { h ^= String(input).charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
function seededRandom(seed) { let value = seed >>> 0; return () => { value += 0x6D2B79F5; let t = value; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
function distributeExact(total, weights, random) { const result = Object.fromEntries(SEASON_MONTHS.map(month => [month, 0])); if (total <= 0) return result; const raw = SEASON_MONTHS.map(month => ({ month, weight: Math.max(0.001, Number(weights[month] || 0.1)) })).map(item => ({ ...item, exact: total * item.weight })); let assigned = 0; raw.forEach(item => { result[item.month] = Math.floor(item.exact); assigned += result[item.month]; }); raw.sort((a, b) => { const fraction = (b.exact - Math.floor(b.exact)) - (a.exact - Math.floor(a.exact)); return fraction || random() - 0.5; }); for (let i = 0; i < total - assigned; i += 1) result[raw[i % raw.length].month] += 1; return result; }
function createMatch({ competition, month, index, seasonYear, random, importance = 'normal' }) { const info = MONTH_INFO[month]; return { id: `${seasonYear}-${month}-${competition.id}-${index + 1}`, competitionId: competition.id, competitionName: competition.name, type: competition.type, month, monthLabel: info.label, seasonYear, matchday: index + 1, venue: random() >= 0.5 ? 'Domicile' : 'Extérieur', opponent: competition.type === 'league' ? 'Adversaire de championnat' : competition.name, importance, status: 'scheduled', played: false }; }
function importanceFor(month, index, total, random) { if (month === 5) return 'major'; if (index === total - 1 && total >= 30) return 'important'; if (random() < 0.12) return 'important'; return 'normal'; }
function buildYouthSchedule(player, seasonYear, random) { const age = Number(player?.age) || 14, category = age <= 15 ? 'U15' : age === 16 ? 'U16' : 'U17/U19', totals = { U15: 22, U16: 26, 'U17/U19': 30 }, total = totals[category] || 22, monthly = distributeExact(total, { 8: .09, 9: .10, 10: .11, 11: .11, 12: .08, 1: .09, 2: .11, 3: .11, 4: .11, 5: .09 }, random), matches = []; for (const month of SEASON_MONTHS) for (let i = 0; i < monthly[month]; i += 1) matches.push(createMatch({ competition: { id: `YOUTH_${category.replace('/', '_')}`, name: `${category} Formation`, type: 'youth' }, month, index: matches.length, seasonYear, random, importance: importanceFor(month, i, monthly[month], random) })); return { category, totalLeagueMatches: total, matches, extras: [] }; }
function buildSeniorSchedule(player, seasonYear, random, competition, buildEuropeanLeague, getEuropeanQualification) { const monthly = distributeExact(competition.matches, { 8: .08, 9: .10, 10: .11, 11: .10, 12: .07, 1: .10, 2: .11, 3: .10, 4: .12, 5: .11 }, random); const clubs = WorldSystem.getClubs(competition.id), playerClub = WorldSystem.getClub(player?.clubId || player?.club), opponents = clubs.filter(c => !playerClub || c.id !== playerClub.id), matches = []; let cursor = 0; for (const month of SEASON_MONTHS) for (let i = 0; i < monthly[month]; i += 1) { const opponent = opponents.length ? opponents[cursor++ % opponents.length] : null; const match = createMatch({ competition, month, index: matches.length, seasonYear, random, importance: importanceFor(month, i, monthly[month], random) }); match.leagueId = competition.id; match.playerClubId = playerClub?.id || player?.clubId || null; match.opponent = opponent?.name || 'Adversaire de championnat'; match.opponentClubId = opponent?.id || null; match.homeClubId = match.venue === 'Domicile' ? match.playerClubId : match.opponentClubId; match.awayClubId = match.venue === 'Domicile' ? match.opponentClubId : match.playerClubId; matches.push(match); }
    const qualification = getEuropeanQualification(player, competition); player.inEurope = qualification.championsLeague || qualification.europaLeague; player.europeanCompetition = qualification.championsLeague ? 'CHAMPIONS_LEAGUE' : qualification.europaLeague ? 'EUROPA_LEAGUE' : null; player.europeanRank = qualification.rank; const extras = buildEuropeanLeague(player, seasonYear, random, qualification); return { category: 'Senior', totalLeagueMatches: competition.matches, matches: [...matches, ...extras], extras, europeanQualification: qualification }; }
export function createSeasonSchedule(player, seasonYear, getSeniorCompetition, buildEuropeanLeague, getEuropeanQualification) { const seed = hashSeed(`${seasonYear}|${player?.club || ''}|${player?.country || ''}|${player?.age || 14}|${player?.position || ''}`), random = seededRandom(seed); if ((Number(player?.age) || 14) < 18) { const youth = buildYouthSchedule(player, seasonYear, random); return { seed, category: youth.category, matches: youth.matches }; } const senior = buildSeniorSchedule(player, seasonYear, random, getSeniorCompetition(player), buildEuropeanLeague, getEuropeanQualification); return { seed, category: senior.category, matches: senior.matches }; }
export function sortMatches(matches) { const order = new Map(SEASON_MONTHS.map((month, index) => [month, index])); return [...matches].sort((a, b) => { const monthDiff = (order.get(a.month) ?? 99) - (order.get(b.month) ?? 99); if (monthDiff !== 0) return monthDiff; if (a.type !== b.type) return a.type === 'league' ? -1 : 1; return String(a.id).localeCompare(String(b.id)); }); }
