function tier({age,level,competition}={}){const a=Number(age||0),text=String(level||competition||'').toLowerCase();if((a&&a<=15)||/u15/.test(text))return'u15';if((a&&a<=18)||/u17|u18|formation|academy|jeune/.test(text))return'youth';if(/regional|régional|national|semi|amateur/.test(text))return'semi';return'pro';}
function reactionText(context={}){const t=tier(context);if(t==='u15')return'Derrière la main courante, quelques voix familières explosent avant même que tes coéquipiers ne te rattrapent.';if(t==='youth')return'Le banc se lève d’un bloc. Sur le bord du terrain, les familles et les observateurs réagissent presque en même temps.';if(t==='semi')return'La petite tribune se lève et le banc traverse presque sa zone avant de se retenir.';return'Le bruit tombe sur la pelouse d’un seul coup. Pendant quelques secondes, tu n’entends plus rien de distinct.';}
function scoreMeaning({score,home=true,minute}={}){if(!score)return'';const own=Number(score[home?'home':'away']||0),opp=Number(score[home?'away':'home']||0),m=Number(minute||0);if(m>=85&&own>opp)return' Ce but ressemble soudain à celui qui peut fermer le match.';if(m>=80&&own===opp)return' Il ne reste presque plus de temps pour en trouver un autre.';if(own===opp)return' Tout est à refaire.';if(own>opp)return' Ton équipe passe devant.';return' L’écart se réduit.';}
export function goalNarration({scorer='Ton joueur',minute,gesture=null,homeTeam='Ton équipe',awayTeam='Adversaire',score,age=null,level=null,competition=null,home=true,firstCareerGoal=false,formerClub=false}={}){
 if(!score||!Number.isFinite(Number(minute)))return null;
 const how=gesture?`${gesture}. `:'';const reaction=reactionText({age,level,competition});const meaning=scoreMeaning({score,home,minute});
 let memory='';if(firstCareerGoal)memory=' Tu le sais avant même de repartir vers le centre : celui-là, tu ne l’oublieras jamais.';else if(formerClub)memory=' Ton premier réflexe est de partir célébrer, puis ton regard croise des visages que tu connais trop bien.';
 return{title:`BUT · ${scorer}`,text:`${how}${Number(minute)}e minute. Le ballon franchit la ligne et le score passe à ${Number(score.home)||0}–${Number(score.away)||0}. ${reaction}${meaning}${memory}`,scoreLine:`${homeTeam} ${Number(score.home)||0} – ${Number(score.away)||0} ${awayTeam}`};
}
export default goalNarration;
