// Street to Pro — 60 occasions de jeu réservées aux MC / MOC.
// Elles racontent le métier de milieu : tempo, orientation, création, pressing, conservation et prise de risque.

const c=(text,style,impacts={},gesture=null)=>({text,style,impacts,gesture});
const m=(id,title,description,choices,meta={})=>({id,title,description,choices,positions:['MC','MOC'],weight:3,...meta});

export const MIDFIELD_PLAY_OPPORTUNITIES=Object.freeze([
// 01-10 — Construction et première relance
m('MID-001','Tu viens chercher entre les centraux','Ton équipe ressort sous pression. Tu décroches très bas pour offrir une première solution alors que deux adversaires ferment l’axe.',[
 c('Jouer en une touche vers le latéral libre','safe',{ratingBonus:.12,passAccuracy:.12,teamBoost:.05},'Sortie en une touche'),c('Te retourner malgré le pressing','technical',{ratingBonus:.18,passAccuracy:.07,duelBonus:.05,technicalRisk:.12},'Demi-tour sous pression'),c('Allonger directement derrière leur bloc','risky',{ratingBonus:.16,assistChance:.05,passAccuracy:.05,technicalRisk:.16},'Renversement long')]),
m('MID-002','Le gardien te donne le premier ballon','Ton gardien cherche une relance courte et te sert face à ton propre but. Un adversaire accélère immédiatement sur toi.',[
 c('Remettre au gardien et bouger','safe',{ratingBonus:.1,passAccuracy:.12},'Remise gardien'),c('Sortir du pressing par le contrôle orienté','technical',{ratingBonus:.19,duelBonus:.07,technicalRisk:.13},'Contrôle orienté'),c('Casser la ligne par une passe verticale','risky',{ratingBonus:.2,passAccuracy:.08,assistChance:.04,technicalRisk:.15},'Passe verticale')]),
m('MID-003','Le latéral est enfermé près de la ligne','Ton latéral reçoit dos au jeu avec deux adversaires autour de lui. Tu peux venir sécuriser ou chercher à sortir directement de la zone.',[
 c('Offrir une remise courte derrière lui','safe',{ratingBonus:.11,passAccuracy:.11,teamBoost:.04},'Soutien court'),c('Faire un troisième homme avec l’ailier','technical',{ratingBonus:.18,passAccuracy:.1,assistChance:.04,technicalRisk:.09},'Troisième homme'),c('Changer immédiatement de côté','risky',{ratingBonus:.19,passAccuracy:.08,technicalRisk:.13},'Renversement')]),
m('MID-004','Le six adverse vient te chercher','Le milieu défensif adverse quitte sa zone pour te presser jusque dans ton camp, laissant un espace derrière lui.',[
 c('Jouer simple et le faire courir','safe',{ratingBonus:.11,passAccuracy:.12},'Passe simple'),c('L’attirer puis servir dans son dos','technical',{ratingBonus:.2,passAccuracy:.1,assistChance:.05,technicalRisk:.1},'Passe dans le dos du six'),c('Le provoquer balle au pied','risky',{ratingBonus:.18,duelBonus:.1,fatigueRisk:1,technicalRisk:.16},'Provocation axiale')]),
m('MID-005','La relance est bloquée dans l’axe','Toutes les passes courtes sont fermées et les défenseurs hésitent. Tu dois décider comment redonner de l’air à la possession.',[
 c('Revenir offrir une solution de sécurité','safe',{ratingBonus:.1,passAccuracy:.12},'Décrochage de sécurité'),c('Te déplacer dans le demi-espace','technical',{ratingBonus:.16,teamBoost:.06,technicalRisk:.05},'Déplacement demi-espace'),c('Demander le ballon sous pression pour casser la ligne','risky',{ratingBonus:.2,duelBonus:.08,passAccuracy:.07,technicalRisk:.15},'Réception sous pression')]),
m('MID-006','Une passe molle arrive vers toi','Le ballon manque de vitesse et un adversaire pense pouvoir jaillir devant toi pour l’intercepter.',[
 c('Venir au ballon et sécuriser','safe',{ratingBonus:.11,passAccuracy:.1},'Attaque du ballon'),c('Laisser passer entre tes jambes pour éliminer le presseur','technical',{ratingBonus:.21,duelBonus:.1,technicalRisk:.18},'Feinte de corps'),c('Dévier en une touche vers l’avant','risky',{ratingBonus:.18,passAccuracy:.07,assistChance:.04,technicalRisk:.14},'Déviation une touche')]),
m('MID-007','Tu reçois avec un joueur dans ton dos','Tu sens immédiatement le contact du milieu adverse dans ton dos alors que ton équipe cherche à progresser.',[
 c('Protéger puis remettre derrière','safe',{ratingBonus:.1,passAccuracy:.1,duelBonus:.03},'Protection-remise'),c('Te retourner sur ton premier contrôle','technical',{ratingBonus:.19,duelBonus:.09,technicalRisk:.14},'Contrôle retourné'),c('Jouer une talonnade vers le partenaire lancé','risky',{ratingBonus:.2,assistChance:.05,technicalRisk:.19},'Talonnade de sortie')]),
m('MID-008','Deux lignes adverses sont très proches','Le bloc adverse est compact. Il n’y a presque aucune passe verticale propre entre leur milieu et leur défense.',[
 c('Faire circuler et attendre le déplacement','safe',{ratingBonus:.11,passAccuracy:.12,teamBoost:.04},'Circulation patiente'),c('Fixer un joueur avant de décaler','technical',{ratingBonus:.18,passAccuracy:.09,teamBoost:.06,technicalRisk:.08},'Fixation-décalage'),c('Forcer une passe entre les lignes','risky',{ratingBonus:.21,assistChance:.06,passAccuracy:.05,technicalRisk:.19},'Passe cassant deux lignes')]),
m('MID-009','La défense te demande de redescendre','Tes centraux s’écartent et te font signe de venir construire l’action depuis leur hauteur.',[
 c('Descendre organiser proprement la relance','safe',{ratingBonus:.12,passAccuracy:.12,teamBoost:.05},'Organisation basse'),c('Faire semblant de descendre puis repartir entre les lignes','technical',{ratingBonus:.18,teamBoost:.06,technicalRisk:.08},'Double déplacement'),c('Refuser et rester haut pour attirer ton marqueur','risky',{ratingBonus:.15,assistChance:.04,technicalRisk:.1},'Fixation haute')]),
m('MID-010','Le pressing adverse arrive par vagues','À chaque passe en retrait, trois adversaires avancent ensemble. Tu vois une fenêtre très courte pour sortir de leur pression.',[
 c('Jouer en sécurité vers le côté faible','safe',{ratingBonus:.12,passAccuracy:.12},'Sortie côté faible'),c('Trouver le troisième homme en une touche','technical',{ratingBonus:.2,passAccuracy:.1,technicalRisk:.11},'Troisième homme une touche'),c('Conduire dans l’espace avant qu’il se ferme','risky',{ratingBonus:.18,duelBonus:.07,fatigueRisk:1,technicalRisk:.15},'Conduite de sortie')]),

// 11-20 — Tempo, orientation et contrôle du rythme
m('MID-011','Le match va trop vite','Les deux équipes perdent le ballon en quelques secondes depuis plusieurs minutes. Tu peux tenter de reprendre le contrôle du rythme.',[
 c('Calmer avec deux passes simples','safe',{ratingBonus:.12,passAccuracy:.13,teamBoost:.05},'Tempo ralenti'),c('Garder le ballon une seconde de plus pour attirer','technical',{ratingBonus:.17,duelBonus:.04,passAccuracy:.1,technicalRisk:.08},'Fixation du tempo'),c('Accélérer encore pour profiter du désordre','risky',{ratingBonus:.17,assistChance:.05,fatigueRisk:1,technicalRisk:.13},'Accélération du jeu')]),
m('MID-012','Ton ailier est isolé côté opposé','Toute la défense vient de coulisser du même côté. Ton ailier opposé a plusieurs mètres devant lui.',[
 c('Renverser immédiatement le jeu','safe',{ratingBonus:.17,passAccuracy:.11,assistChance:.04},'Renversement'),c('Fixer encore un adversaire avant de renverser','technical',{ratingBonus:.21,passAccuracy:.1,technicalRisk:.1},'Fixation-renversement'),c('Chercher directement une passe longue dans sa course','risky',{ratingBonus:.22,assistChance:.08,technicalRisk:.16},'Transversale dans la course')]),
m('MID-013','Tu as dix mètres devant toi','Personne ne vient immédiatement sur toi au milieu. Le bloc adverse recule et te laisse porter le ballon.',[
 c('Avancer balle au pied sans te précipiter','safe',{ratingBonus:.13,fatigueRisk:1,duelBonus:.03},'Conduite contrôlée'),c('Attirer un milieu avant de libérer un partenaire','technical',{ratingBonus:.19,passAccuracy:.09,teamBoost:.05,technicalRisk:.07},'Fixation axiale'),c('Tenter la passe qui casse toute la ligne','risky',{ratingBonus:.22,assistChance:.08,technicalRisk:.17},'Passe laser')]),
m('MID-014','Ton équipe mène et s’emballe','Malgré l’avantage, plusieurs partenaires continuent de se projeter en même temps et laissent de grands espaces derrière.',[
 c('Faire tourner pour calmer le match','safe',{ratingBonus:.13,passAccuracy:.13,teamBoost:.05},'Gestion du score'),c('Continuer à attaquer mais avec une passe sûre','technical',{ratingBonus:.15,passAccuracy:.1,assistChance:.03},'Attaque contrôlée'),c('Profiter du déséquilibre pour tuer le match','risky',{ratingBonus:.18,assistChance:.07,technicalRisk:.14},'Passe de rupture')],{requiresLead:true}),
m('MID-015','Ton équipe est menée et le ballon circule trop lentement','Chaque passe latérale fait perdre quelques secondes alors qu’il faut provoquer davantage.',[
 c('Accélérer les transmissions sans forcer','safe',{ratingBonus:.14,passAccuracy:.11,teamBoost:.05},'Circulation accélérée'),c('Prendre plus de risques entre les lignes','technical',{ratingBonus:.19,assistChance:.07,technicalRisk:.12},'Jeu vertical'),c('Porter toi-même le ballon jusqu’au dernier tiers','risky',{ratingBonus:.19,duelBonus:.07,fatigueRisk:2,technicalRisk:.15},'Percée axiale')],{requiresTrailing:true}),
m('MID-016','Le bloc adverse ne sort plus','Les adversaires restent très bas et te laissent presque organiser à volonté devant eux.',[
 c('Faire circuler jusqu’à déplacer le bloc','safe',{ratingBonus:.13,passAccuracy:.13},'Patience devant bloc bas'),c('Jouer une passe courte puis attaquer l’intervalle','technical',{ratingBonus:.19,assistChance:.05,technicalRisk:.1},'Passe et déplacement'),c('Tenter une ouverture immédiate dans la surface','risky',{ratingBonus:.2,assistChance:.09,technicalRisk:.18},'Ouverture forcée')]),
m('MID-017','Ton attaquant décroche très loin','Le numéro neuf quitte la ligne défensive pour venir demander dans les pieds. Son mouvement crée un trou derrière lui.',[
 c('Lui donner dans les pieds','safe',{ratingBonus:.12,passAccuracy:.12},'Passe au neuf'),c('Utiliser son appel comme leurre et jouer derrière','technical',{ratingBonus:.21,assistChance:.08,technicalRisk:.11},'Passe derrière le décrochage'),c('Prendre sa zone et te projeter toi-même','risky',{ratingBonus:.18,goalChance:.04,fatigueRisk:2,technicalRisk:.12},'Projection du milieu')]),
m('MID-018','Le ballon revient toujours vers toi','Depuis plusieurs minutes, tes partenaires te cherchent presque systématiquement pour orienter chaque possession.',[
 c('Continuer à jouer simple','safe',{ratingBonus:.13,passAccuracy:.13,teamBoost:.04},'Maîtrise du tempo'),c('Changer volontairement le rythme sur la prochaine réception','technical',{ratingBonus:.18,passAccuracy:.1,teamBoost:.05,technicalRisk:.08},'Changement de rythme'),c('Tenter la passe décisive que tu retiens depuis plusieurs actions','risky',{ratingBonus:.22,assistChance:.1,technicalRisk:.19},'Passe décisive tentée')]),
m('MID-019','Le match est devenu physique au milieu','Les contacts se multiplient et chaque réception dos au jeu devient un duel.',[
 c('Jouer en une touche pour éviter les contacts','safe',{ratingBonus:.12,passAccuracy:.12},'Jeu une touche'),c('Utiliser ton corps pour protéger et orienter','technical',{ratingBonus:.17,duelBonus:.08,technicalRisk:.09},'Protection orientée'),c('Répondre en conduisant directement dans le duel','risky',{ratingBonus:.17,duelBonus:.12,fatigueRisk:2,cardRisk:.01,technicalRisk:.16},'Duel axial')]),
m('MID-020','Une minute de possession sans progression','Ton équipe garde le ballon mais n’avance plus. Les adversaires semblent parfaitement installés.',[
 c('Continuer à déplacer patiemment le bloc','safe',{ratingBonus:.11,passAccuracy:.12},'Patience collective'),c('Changer de hauteur pour recevoir plus haut','technical',{ratingBonus:.17,teamBoost:.05,technicalRisk:.07},'Changement de hauteur'),c('Forcer une passe verticale pour provoquer quelque chose','risky',{ratingBonus:.21,assistChance:.07,technicalRisk:.18},'Passe verticale forcée')]),

// 21-30 — Entre les lignes et création
m('MID-021','Tu reçois entre les lignes','Tu trouves enfin quelques mètres entre le milieu et la défense adverse. En te retournant, tu peux voir toute la dernière ligne.',[
 c('Décaler immédiatement le joueur libre','safe',{ratingBonus:.15,passAccuracy:.11,assistChance:.04},'Décalage entre les lignes'),c('Te retourner et fixer le central','technical',{ratingBonus:.21,duelBonus:.06,assistChance:.06,technicalRisk:.11},'Fixation entre les lignes'),c('Glisser directement la passe dans le dos','risky',{ratingBonus:.23,assistChance:.11,technicalRisk:.18},'Passe dans la profondeur')]),
m('MID-022','Deux appels partent en même temps','Un attaquant vient dans les pieds pendant qu’un ailier plonge dans le dos de la défense.',[
 c('Servir l’attaquant dans les pieds','safe',{ratingBonus:.13,passAccuracy:.12},'Passe dans les pieds'),c('Masquer ton intention puis jouer l’ailier','technical',{ratingBonus:.21,assistChance:.08,technicalRisk:.12},'Passe masquée'),c('Ignorer les deux et conduire dans l’axe','risky',{ratingBonus:.18,duelBonus:.07,fatigueRisk:1,technicalRisk:.14},'Conduite centrale')]),
m('MID-023','Le défenseur central sort sur toi','Tu as reçu entre les lignes et un central décide de quitter sa défense pour venir t’empêcher de te retourner.',[
 c('Remettre en une touche derrière toi','safe',{ratingBonus:.12,passAccuracy:.12},'Remise une touche'),c('Le fixer jusqu’au dernier moment puis servir son dos','technical',{ratingBonus:.23,assistChance:.1,technicalRisk:.13},'Fixation du central'),c('Tenter de l’éliminer sur ton contrôle','risky',{ratingBonus:.2,duelBonus:.11,goalChance:.03,technicalRisk:.19},'Contrôle éliminatoire')]),
m('MID-024','Ton attaquant est dos au but dans la surface','Le ballon peut entrer dans les pieds de ton numéro neuf, mais deux défenseurs sont proches de lui.',[
 c('Lui donner proprement pour une remise','safe',{ratingBonus:.14,passAccuracy:.12,assistChance:.03},'Passe au point d’appui'),c('Jouer à côté de lui pour le troisième homme','technical',{ratingBonus:.2,assistChance:.08,technicalRisk:.1},'Troisième homme offensif'),c('Lever le ballon derrière les défenseurs','risky',{ratingBonus:.22,assistChance:.1,technicalRisk:.18},'Ballon piqué')]),
m('MID-025','Le demi-espace s’ouvre à gauche','Le latéral adverse hésite entre sortir sur toi et rester avec ton ailier. Quelques mètres s’ouvrent dans son dos.',[
 c('Décaler l’ailier dans les pieds','safe',{ratingBonus:.13,passAccuracy:.11},'Décalage ailier'),c('Attaquer le demi-espace puis remettre','technical',{ratingBonus:.19,assistChance:.06,fatigueRisk:1,technicalRisk:.1},'Occupation demi-espace'),c('Piquer la passe directement dans le dos du latéral','risky',{ratingBonus:.22,assistChance:.1,technicalRisk:.17},'Passe piquée demi-espace')]),
m('MID-026','Tu as reçu face au jeu à vingt-cinq mètres','Personne ne te presse encore franchement. La défense hésite entre avancer et protéger sa surface.',[
 c('Donner sur le côté et continuer ton déplacement','safe',{ratingBonus:.13,passAccuracy:.11},'Passe et déplacement'),c('Fixer puis jouer dans l’intervalle','technical',{ratingBonus:.21,assistChance:.08,technicalRisk:.11},'Fixation-passe'),c('Tenter une frappe lointaine pour les faire sortir','risky',{ratingBonus:.18,goalChance:.08,technicalRisk:.18},'Frappe de loin')]),
m('MID-027','Le couloir intérieur est libre une seconde','Un mouvement de ton ailier emmène deux défenseurs vers la ligne et libère une fenêtre plein axe.',[
 c('Entrer dans l’espace puis jouer simple','safe',{ratingBonus:.15,passAccuracy:.1,fatigueRisk:1},'Occupation intérieure'),c('Recevoir orienté vers le but','technical',{ratingBonus:.2,assistChance:.06,technicalRisk:.1},'Réception orientée'),c('Demander la passe verticale immédiatement','risky',{ratingBonus:.2,goalChance:.03,assistChance:.07,technicalRisk:.15},'Appel vertical')]),
m('MID-028','Un partenaire fait un appel croisé','Son déplacement emmène le défenseur central loin de sa zone habituelle et ouvre un passage derrière lui.',[
 c('Conserver et attendre que l’espace s’agrandisse','safe',{ratingBonus:.12,passAccuracy:.11},'Temporisation créative'),c('Servir l’appel croisé au bon tempo','technical',{ratingBonus:.22,assistChance:.1,technicalRisk:.12},'Passe sur appel croisé'),c('Utiliser l’appel comme leurre et frapper','risky',{ratingBonus:.19,goalChance:.07,technicalRisk:.17},'Frappe après leurre')]),
m('MID-029','Tu peux jouer le une-deux plein axe','Un coéquipier proche te regarde et comprend immédiatement que l’espace derrière son défenseur peut être attaqué.',[
 c('Jouer le une-deux simple','safe',{ratingBonus:.15,passAccuracy:.1,assistChance:.04},'Une-deux axial'),c('Feinter le retour puis jouer ailleurs','technical',{ratingBonus:.2,passAccuracy:.1,technicalRisk:.11},'Fausse combinaison'),c('Demander le retour dans la surface','risky',{ratingBonus:.21,goalChance:.05,assistChance:.05,fatigueRisk:1,technicalRisk:.15},'Projection après une-deux')]),
m('MID-030','Le ballon arrive derrière ton pied d’appui','La passe n’est pas parfaite mais tu es entre les lignes. Un mauvais contrôle peut tuer l’action.',[
 c('Assurer le contrôle et repartir derrière','safe',{ratingBonus:.11,passAccuracy:.1},'Contrôle de sécurité'),c('Utiliser l’extérieur pour orienter vers l’avant','technical',{ratingBonus:.2,technicalRisk:.13,assistChance:.05},'Contrôle extérieur'),c('Laisser filer pour éliminer le joueur derrière toi','risky',{ratingBonus:.22,duelBonus:.09,technicalRisk:.19},'Laisser passer')]),

// 31-40 — Derniers trente mètres
m('MID-031','Le bloc s’ouvre devant la surface','Tu arrives lancé dans les trente derniers mètres. Trois solutions se dessinent presque en même temps.',[
 c('Décaler le joueur le plus libre','safe',{ratingBonus:.15,passAccuracy:.11,assistChance:.05},'Décalage final'),c('Fixer un défenseur puis glisser la passe','technical',{ratingBonus:.22,assistChance:.1,technicalRisk:.12},'Dernière passe après fixation'),c('Continuer balle au pied jusqu’à la surface','risky',{ratingBonus:.19,goalChance:.05,duelBonus:.08,fatigueRisk:1,technicalRisk:.16},'Conduite vers surface')]),
m('MID-032','Ton ailier rentre à l’intérieur','Son déplacement attire le latéral dans l’axe et libère complètement le couloir extérieur.',[
 c('Servir le latéral qui dédouble','safe',{ratingBonus:.15,passAccuracy:.11,assistChance:.05},'Passe au dédoublement'),c('Jouer avec l’ailier en remise courte','technical',{ratingBonus:.19,assistChance:.06,technicalRisk:.09},'Combinaison intérieure'),c('Profiter du déplacement pour frapper plein axe','risky',{ratingBonus:.18,goalChance:.07,technicalRisk:.16},'Frappe axiale')]),
m('MID-033','Une passe décisive est possible mais étroite','Ton attaquant part entre deux défenseurs. La fenêtre existe, mais seulement pour une fraction de seconde.',[
 c('Attendre une option plus sûre','safe',{ratingBonus:.1,passAccuracy:.11},'Patience'),c('Glisser la passe dans le bon tempo','technical',{ratingBonus:.23,assistChance:.12,technicalRisk:.13},'Passe décisive au tempo'),c('Tenter l’extérieur du pied sans ouvrir ton corps','risky',{ratingBonus:.25,assistChance:.13,technicalRisk:.21},'Extérieur décisif')]),
m('MID-034','Tu arrives en deuxième rideau','Un centre est repoussé à l’entrée de la surface et le ballon vient directement dans ta zone.',[
 c('Contrôler puis remettre sur un côté','safe',{ratingBonus:.12,passAccuracy:.11},'Recyclage deuxième ballon'),c('Frapper après un contrôle orienté','technical',{ratingBonus:.19,goalChance:.07,technicalRisk:.12},'Frappe deuxième rideau'),c('Reprendre de volée sans contrôle','risky',{ratingBonus:.22,goalChance:.09,technicalRisk:.21},'Volée du milieu')]),
m('MID-035','Le gardien masque la passe au sol','Ton attaquant est libre mais le gardien avance suffisamment pour fermer la trajectoire classique.',[
 c('Décaler sur le côté pour conserver l’action','safe',{ratingBonus:.13,passAccuracy:.1},'Décalage de sécurité'),c('Piquer le ballon par-dessus la sortie','technical',{ratingBonus:.23,assistChance:.11,technicalRisk:.15},'Passe piquée'),c('Feinter la passe et tenter ta chance','risky',{ratingBonus:.2,goalChance:.08,technicalRisk:.18},'Feinte-puis-frappe')]),
m('MID-036','Le défenseur protège la passe vers ton neuf','Il lit clairement ton intention et ferme l’axe de passe principal.',[
 c('Repartir latéralement','safe',{ratingBonus:.11,passAccuracy:.11},'Recyclage latéral'),c('Masquer la passe puis trouver l’ailier opposé','technical',{ratingBonus:.21,assistChance:.08,technicalRisk:.11},'Passe masquée opposée'),c('Tenter quand même la passe entre ses jambes','risky',{ratingBonus:.23,assistChance:.1,technicalRisk:.21},'Petit pont de passe')]),
m('MID-037','Tu peux lancer le latéral dans ton dos','Le défenseur te regarde et oublie une seconde le joueur qui dédouble derrière toi.',[
 c('Servir immédiatement le dédoublement','safe',{ratingBonus:.15,passAccuracy:.12,assistChance:.04},'Passe au latéral'),c('Attendre qu’il soit totalement lancé','technical',{ratingBonus:.19,assistChance:.08,technicalRisk:.08},'Passe temporisée'),c('Feinter la passe puis rentrer dans l’axe','risky',{ratingBonus:.19,duelBonus:.07,goalChance:.04,technicalRisk:.16},'Feinte et conduite')]),
m('MID-038','Ton attaquant te remet en retrait','Tu reçois à l’entrée de la surface après un point d’appui propre. La défense ressort vite sur toi.',[
 c('Rejouer immédiatement sur un côté','safe',{ratingBonus:.13,passAccuracy:.11},'Remise latérale'),c('Contrôler orienté puis chercher la passe finale','technical',{ratingBonus:.21,assistChance:.09,technicalRisk:.12},'Contrôle créatif'),c('Frapper avant le retour du milieu','risky',{ratingBonus:.2,goalChance:.08,technicalRisk:.18},'Frappe entrée de surface')]),
m('MID-039','Le dernier défenseur hésite sur deux appels','Deux partenaires attaquent simultanément des zones opposées et le dernier défenseur ne sait plus qui suivre.',[
 c('Servir l’appel le plus simple','safe',{ratingBonus:.16,assistChance:.07,passAccuracy:.11},'Passe simple dans l’appel'),c('Attendre son choix puis jouer l’autre zone','technical',{ratingBonus:.24,assistChance:.12,technicalRisk:.13},'Passe après lecture'),c('Conduire pour le forcer à sortir sur toi','risky',{ratingBonus:.2,duelBonus:.06,assistChance:.07,technicalRisk:.15},'Fixation du dernier défenseur')]),
m('MID-040','Tu peux faire basculer l’action en une touche','La passe arrive vite, mais tu as déjà vu l’appel avant même de recevoir.',[
 c('Contrôler pour assurer','safe',{ratingBonus:.12,passAccuracy:.11},'Contrôle assuré'),c('Jouer en une touche dans l’appel','technical',{ratingBonus:.23,assistChance:.11,technicalRisk:.13},'Passe première intention'),c('Tenter une déviation aveugle dans la course','risky',{ratingBonus:.25,assistChance:.12,technicalRisk:.22},'Déviation aveugle')]),

// 41-50 — Transitions et pressing
m('MID-041','Tu récupères au milieu et le bloc est ouvert','Ton interception casse immédiatement leur première ligne. Trois adversaires sont encore devant le ballon, mais ils reculent.',[
 c('Assurer la première passe vers l’avant','safe',{ratingBonus:.15,passAccuracy:.11,counterAttack:.03},'Première passe de transition'),c('Porter jusqu’à fixer un défenseur','technical',{ratingBonus:.2,duelBonus:.06,counterAttack:.05,fatigueRisk:1,technicalRisk:.1},'Conduite de transition'),c('Chercher immédiatement la profondeur','risky',{ratingBonus:.22,assistChance:.1,counterAttack:.08,technicalRisk:.17},'Passe de contre')]),
m('MID-042','Tu perds le ballon dans l’axe','Ta passe est interceptée et l’adversaire peut partir en transition. Tu es le premier joueur capable de réagir.',[
 c('Revenir fermer l’axe','safe',{ratingBonus:.12,duelBonus:.06,opponentThreat:-.05,fatigueRisk:1},'Repli axial'),c('Presser immédiatement le porteur','technical',{ratingBonus:.17,duelBonus:.1,opponentThreat:-.07,fatigueRisk:2,cardRisk:.01},'Contre-pressing'),c('Tenter le tacle pour récupérer tout de suite','risky',{ratingBonus:.18,duelBonus:.13,opponentThreat:-.08,cardRisk:.05,technicalRisk:.15},'Tacle de récupération')]),
m('MID-043','Un partenaire perd le ballon près de toi','Le porteur adverse vient à peine de récupérer et n’a pas encore levé la tête.',[
 c('Fermer sa première passe','safe',{ratingBonus:.13,opponentThreat:-.05,teamBoost:.04},'Fermeture de ligne'),c('L’agresser immédiatement au pressing','technical',{ratingBonus:.18,duelBonus:.1,opponentThreat:-.07,fatigueRisk:2},'Pressing immédiat'),c('Anticiper sa passe suivante pour intercepter','risky',{ratingBonus:.2,duelBonus:.09,counterAttack:.05,technicalRisk:.13},'Interception anticipée')]),
m('MID-044','Le ballon ressort après votre corner','L’adversaire récupère et tente immédiatement de lancer une transition alors que plusieurs de tes partenaires sont encore dans la surface.',[
 c('Faire faute tactique loin du but','safe',{ratingBonus:.09,opponentThreat:-.07,cardRisk:.08},'Faute tactique'),c('Temporiser le porteur sans te jeter','technical',{ratingBonus:.18,duelBonus:.08,opponentThreat:-.08,fatigueRisk:1},'Défense en reculant'),c('Tenter de récupérer pour relancer une deuxième attaque','risky',{ratingBonus:.2,duelBonus:.12,counterAttack:.05,technicalRisk:.17},'Récupération haute')]),
m('MID-045','Tu reçois juste après une récupération collective','Tes partenaires ont gagné le ballon et te trouvent immédiatement. L’équipe adverse est encore désorganisée.',[
 c('Jouer la première passe simple vers l’avant','safe',{ratingBonus:.14,passAccuracy:.11,counterAttack:.04},'Passe de transition'),c('Te retourner et porter le ballon','technical',{ratingBonus:.18,duelBonus:.06,counterAttack:.05,technicalRisk:.1},'Conduite de transition'),c('Tenter directement la passe décisive','risky',{ratingBonus:.22,assistChance:.11,counterAttack:.08,technicalRisk:.18},'Passe décisive de transition')]),
m('MID-046','Le porteur adverse te tourne le dos','Il reçoit dos au jeu juste devant toi et ne sait pas encore où se trouvent ses partenaires.',[
 c('Rester au contact sans te jeter','safe',{ratingBonus:.12,duelBonus:.06,opponentThreat:-.04},'Pression contrôlée'),c('Passer devant lui au moment de sa touche','technical',{ratingBonus:.19,duelBonus:.11,counterAttack:.04,technicalRisk:.1},'Interception devant'),c('Le pousser à jouer vers la ligne puis doubler le pressing','risky',{ratingBonus:.18,teamBoost:.05,opponentThreat:-.06,fatigueRisk:2,technicalRisk:.11},'Piège de pressing')]),
m('MID-047','Le contre adverse démarre sur ton côté','Un attaquant reçoit lancé et ton latéral est encore haut. Tu dois couvrir plusieurs mètres très vite.',[
 c('Revenir protéger la zone du latéral','safe',{ratingBonus:.13,opponentThreat:-.06,fatigueRisk:2},'Couverture latérale'),c('Couper la ligne de passe intérieure','technical',{ratingBonus:.17,opponentThreat:-.08,duelBonus:.05},'Fermeture intérieure'),c('Sortir directement sur le porteur','risky',{ratingBonus:.17,duelBonus:.1,opponentThreat:-.07,fatigueRisk:2,cardRisk:.02,technicalRisk:.14},'Sortie agressive')]),
m('MID-048','Tu peux lancer un contre après un duel gagné','Le ballon t’arrive immédiatement après qu’un partenaire a remporté un duel aérien au milieu.',[
 c('Sécuriser la deuxième balle','safe',{ratingBonus:.13,passAccuracy:.1},'Deuxième ballon sécurisé'),c('Orienter dès le premier contrôle vers l’avant','technical',{ratingBonus:.19,counterAttack:.05,technicalRisk:.1},'Contrôle de transition'),c('Jouer directement au-dessus de la défense','risky',{ratingBonus:.22,assistChance:.09,counterAttack:.08,technicalRisk:.18},'Ouverture immédiate')]),
m('MID-049','Ton pressing déclenche une erreur','Le défenseur adverse joue une passe précipitée dans l’axe. Tu peux intervenir avant son milieu.',[
 c('Intercepter et assurer derrière','safe',{ratingBonus:.15,duelBonus:.08,passAccuracy:.09},'Interception simple'),c('Intercepter orienté vers le but','technical',{ratingBonus:.21,counterAttack:.06,technicalRisk:.11},'Interception orientée'),c('Dévier directement vers l’attaquant','risky',{ratingBonus:.22,assistChance:.08,counterAttack:.07,technicalRisk:.17},'Déviation de pressing')]),
m('MID-050','Vous êtes quatre contre quatre en transition','Le terrain est ouvert. Chaque décision peut créer une supériorité ou rendre le ballon immédiatement.',[
 c('Donner au partenaire le plus proche','safe',{ratingBonus:.13,passAccuracy:.11,counterAttack:.03},'Passe de transition sûre'),c('Fixer un adversaire avant de transmettre','technical',{ratingBonus:.2,assistChance:.07,counterAttack:.05,technicalRisk:.11},'Fixation en transition'),c('Tenter la passe qui élimine deux joueurs','risky',{ratingBonus:.23,assistChance:.11,counterAttack:.08,technicalRisk:.19},'Passe de rupture en contre')]),

// 51-60 — Pression, fatigue et moments décisifs
m('MID-051','Dernières minutes, il faut garder le ballon','Ton équipe mène et l’adversaire presse avec presque tous ses joueurs.',[
 c('Jouer vers le coin et faire remonter le bloc','safe',{ratingBonus:.13,passAccuracy:.11,teamBoost:.05},'Gestion de fin de match'),c('Conserver sous pression pour gagner du temps','technical',{ratingBonus:.18,duelBonus:.07,technicalRisk:.1},'Conservation sous pression'),c('Chercher la passe qui tue définitivement le match','risky',{ratingBonus:.21,assistChance:.1,technicalRisk:.17},'Passe de fin de match')],{requiresLead:true,minMinute:78}),
m('MID-052','Dernières minutes, il faut créer quelque chose','Ton équipe est menée et chaque récupération doit devenir une attaque presque immédiatement.',[
 c('Accélérer le jeu par une passe verticale simple','safe',{ratingBonus:.15,passAccuracy:.1,teamBoost:.04},'Verticalité immédiate'),c('Prendre le ballon et casser une ligne toi-même','technical',{ratingBonus:.2,duelBonus:.08,fatigueRisk:2,technicalRisk:.13},'Percée tardive'),c('Tenter la passe décisive dès la première touche','risky',{ratingBonus:.24,assistChance:.12,technicalRisk:.2},'Passe désespérée')],{requiresTrailing:true,minMinute:78}),
m('MID-053','Tes jambes sont lourdes mais le jeu passe par toi','La fatigue monte et pourtant tes partenaires continuent de te chercher pour organiser les possessions.',[
 c('Réduire le nombre de touches','safe',{ratingBonus:.12,passAccuracy:.11,fatigueRisk:-1},'Jeu simplifié'),c('Choisir tes courses et accélérer seulement au bon moment','technical',{ratingBonus:.17,teamBoost:.04,fatigueRisk:0},'Gestion de l’effort'),c('Continuer à jouer à haute intensité','risky',{ratingBonus:.18,assistChance:.05,fatigueRisk:3,technicalRisk:.14},'Intensité maintenue')],{requiresFatigue:true}),
m('MID-054','Le coach te demande de prendre le match en main','Depuis le bord du terrain, il te fait signe de demander davantage le ballon et d’imposer le rythme.',[
 c('Multiplier les solutions simples','safe',{ratingBonus:.13,passAccuracy:.12,teamBoost:.05},'Prise de contrôle sobre'),c('Orienter chaque possession vers l’avant','technical',{ratingBonus:.19,passAccuracy:.09,assistChance:.05,technicalRisk:.08},'Direction du jeu'),c('Chercher systématiquement la passe qui fait mal','risky',{ratingBonus:.21,assistChance:.1,technicalRisk:.18},'Création agressive')],{requiresCoachSignal:true}),
m('MID-055','Ton adversaire direct commence à te coller','Après plusieurs bonnes séquences, il ne te laisse presque plus recevoir librement entre les lignes.',[
 c('Décrocher pour le faire sortir de sa zone','safe',{ratingBonus:.14,teamBoost:.04},'Décrochage'),c('Multiplier les changements de direction avant de recevoir','technical',{ratingBonus:.19,duelBonus:.07,fatigueRisk:1,technicalRisk:.08},'Démarquage intérieur'),c('Demander le ballon dans ses pieds pour le provoquer','risky',{ratingBonus:.2,duelBonus:.11,technicalRisk:.16},'Duel de réception')]),
m('MID-056','Tu viens de rater une passe importante','L’action précédente reste dans ta tête, mais le ballon revient presque immédiatement vers toi.',[
 c('Faire simple sur la suivante','safe',{ratingBonus:.11,passAccuracy:.12},'Passe de relance mentale'),c('Reprendre le même type de passe avec plus de précision','technical',{ratingBonus:.19,passAccuracy:.1,technicalRisk:.11},'Réponse technique'),c('Tenter encore plus difficile pour effacer l’erreur','risky',{ratingBonus:.17,assistChance:.09,technicalRisk:.22},'Réaction d’orgueil')],{requiresPreviousMistake:true}),
m('MID-057','Tu viens de réussir deux passes qui cassent des lignes','L’adversaire commence à reculer dès que tu reçois. Tu sens qu’il hésite désormais à sortir sur toi.',[
 c('Continuer à exploiter simplement l’espace','safe',{ratingBonus:.14,passAccuracy:.12},'Maîtrise installée'),c('Attirer encore plus avant de libérer le ballon','technical',{ratingBonus:.2,assistChance:.07,technicalRisk:.09},'Fixation confiante'),c('Chercher la passe la plus ambitieuse du match','risky',{ratingBonus:.23,assistChance:.12,technicalRisk:.2},'Passe signature')],{requiresPlaymakingMomentum:true}),
m('MID-058','Le score est nul et le match se ferme','Plus personne ne veut vraiment se découvrir. Chaque ballon au milieu devient plus important que le précédent.',[
 c('Garder le contrôle et ne rien offrir','safe',{ratingBonus:.13,passAccuracy:.12},'Contrôle du nul'),c('Changer de rythme sur une seule séquence','technical',{ratingBonus:.19,assistChance:.06,technicalRisk:.1},'Accélération choisie'),c('Tenter de casser le match par une passe très risquée','risky',{ratingBonus:.22,assistChance:.11,technicalRisk:.2},'Passe pour faire basculer')],{requiresDraw:true,minMinute:65}),
m('MID-059','Prolongation, chaque ballon coûte','Les espaces existent encore mais les jambes répondent moins vite. Une perte de balle peut devenir beaucoup plus dangereuse qu’avant.',[
 c('Jouer à une touche et économiser les courses','safe',{ratingBonus:.13,passAccuracy:.11,fatigueRisk:-1},'Gestion prolongation'),c('Choisir un seul changement de rythme','technical',{ratingBonus:.18,teamBoost:.04,fatigueRisk:1,technicalRisk:.1},'Accélération ponctuelle'),c('Tenter la passe décisive malgré la fatigue','risky',{ratingBonus:.22,assistChance:.11,fatigueRisk:2,technicalRisk:.2},'Passe décisive en prolongation')],{extraTimeOnly:true,requiresFatigue:true}),
m('MID-060','Une dernière possession pour créer quelque chose','Le temps est presque écoulé. Tu reçois au milieu avec suffisamment d’espace pour décider de la dernière direction du match.',[
 c('Assurer une dernière attaque construite','safe',{ratingBonus:.14,passAccuracy:.11,teamBoost:.04},'Dernière construction'),c('Porter jusqu’à attirer un adversaire puis lâcher','technical',{ratingBonus:.2,assistChance:.08,fatigueRisk:1,technicalRisk:.12},'Dernière fixation'),c('Tenter immédiatement la passe qui peut tout décider','risky',{ratingBonus:.24,assistChance:.13,technicalRisk:.22},'Dernière passe')],{minMinute:88})
]);

function hash(seed,max){let h=2166136261;for(const x of String(seed||'midfield')){h^=x.charCodeAt(0);h=Math.imul(h,16777619);}return max?(h>>>0)%max:0;}
export function isExclusiveMidfieldPosition(position=''){return ['MC','CM','MOC','CAM'].includes(String(position||'').toUpperCase());}
function allows(item,cx){if(item.minMinute&&cx.minute<item.minMinute)return false;if(item.requiresLead&&!(cx.scoreFor>cx.scoreAgainst))return false;if(item.requiresTrailing&&!(cx.scoreFor<cx.scoreAgainst))return false;if(item.requiresDraw&&cx.scoreFor!==cx.scoreAgainst)return false;if(item.requiresFatigue&&Number(cx.fatigue||0)<55)return false;if(item.extraTimeOnly&&cx.extraTime!==true)return false;if(item.requiresCoachSignal&&cx.coachSignal!==true)return false;if(item.requiresPreviousMistake&&cx.previousMistake!==true)return false;if(item.requiresPlaymakingMomentum&&cx.playmakingMomentum!==true)return false;return true;}
export function selectMidfieldPlayOpportunity({seed,index=0,minute=0,position='',scoreFor=0,scoreAgainst=0,fatigue=0,extraTime=false,coachSignal=false,previousMistake=false,playmakingMomentum=false}={}){
 if(!isExclusiveMidfieldPosition(position))return null;
 const cx={minute,scoreFor,scoreAgainst,fatigue,extraTime,coachSignal,previousMistake,playmakingMomentum};
 const pool=MIDFIELD_PLAY_OPPORTUNITIES.filter(x=>allows(x,cx));if(!pool.length)return null;
 return pool[hash(`${seed}:${index}:${minute}:midfield`,pool.length)]||null;
}
export function buildMidfieldPlayDecision(item,{minute=0}={}){if(!item)return null;return{opportunityId:item.id,title:`${minute}' · ${item.title}`,description:item.description,choices:item.choices.map(x=>({...x,opportunityId:item.id,isMidfieldPlay:true}))};}
export default {MIDFIELD_PLAY_OPPORTUNITIES,isExclusiveMidfieldPosition,selectMidfieldPlayOpportunity,buildMidfieldPlayDecision};
