// Compose les étapes présentables d'un match jouable. Ce module ne modifie pas le State.

const scoreSnapshot = session => ({ home: Number(session?.score?.home) || 0, away: Number(session?.score?.away) || 0 });
const stableNumber = (seed, min, max) => {
    const text = String(seed || 'match'); let hash = 2166136261;
    for (let i=0;i<text.length;i++){ hash ^= text.charCodeAt(i); hash = Math.imul(hash,16777619); }
    return min + ((hash >>> 0) % Math.max(1, max-min+1));
};
function step(session, values = {}) { return { id:`${session.id}:${values.phase}`,phase:values.phase,kind:values.kind||'narration',label:values.label||'MATCH',progress:Number(values.progress)||0,minute:values.minute??null,title:values.title||'',text:values.text||'',team:session.team,opponent:session.opponent,competition:session.competition,home:session.home,score:scoreSnapshot(session),choices:values.choices||[],items:values.items||[],timedDecision:values.timedDecision||null,actionLabel:values.actionLabel||'Continuer' }; }

function careerTier(session={}) {
    const age=Number(session.playerAge||session.age||0), level=String(session.level||session.competition||'').toLowerCase();
    if ((age && age<=15)||/u15|moins de 15/.test(level)) return 'u15';
    if ((age && age<=18)||/u17|u18|formation|academy|jeune/.test(level)) return 'youth';
    if (/national|semi|amateur|regional|régional/.test(level)) return 'semi';
    return 'pro';
}
function attendance(session={}) {
    const tier=careerTier(session), special=session.type==='rival'||session.type==='final'||['important','exceptional'].includes(session.importance);
    const ranges={u15:special?[70,220]:[25,120],youth:special?[180,850]:[70,420],semi:special?[900,5200]:[250,2400],pro:special?[18000,62000]:[6500,39000]};
    let [min,max]=ranges[tier];
    const capacity=Number(session.stadiumCapacity||session.capacity||0); if(capacity>0) max=Math.min(max,capacity);
    min=Math.min(min,max); return stableNumber(`${session.id}:${session.opponent}:${session.importance}`,min,max);
}
function crowdText(session={}) {
    const count=attendance(session), tier=careerTier(session), formatted=count.toLocaleString('fr-FR');
    if(tier==='u15') return `${formatted} spectateurs entourent le terrain. La plupart sont des proches des joueurs.`;
    if(tier==='youth') return `${formatted} personnes suivent la rencontre. Quelques regards extérieurs se mêlent aux familles et aux habitués du club.`;
    if(tier==='semi') return `${formatted} spectateurs sont présents. Le bruit monte lorsque les deux équipes terminent leur échauffement.`;
    return `${formatted} spectateurs sont annoncés. À mesure que le coup d’envoi approche, le stade trouve sa voix.`;
}
function stakesText(session) {
    const crowd=crowdText(session);
    if(session.type==='final') return `${crowd} Une finale face à ${session.opponent}. L’attente se lit sur les visages jusque dans le tunnel.`;
    if(session.type==='rival') return `${crowd} Face à ${session.opponent}, les premiers duels semblent déjà avoir commencé pendant l’échauffement.`;
    if(session.importance==='important'||session.importance==='exceptional') return `${crowd} Ce rendez-vous contre ${session.opponent} peut peser lourd dans la dynamique de la saison.`;
    return crowd;
}
export function buildPreMatchStep(session){return step(session,{phase:'pre_match',label:'AVANT-MATCH',progress:4,title:`${session.team} · ${session.opponent}`,text:stakesText(session),actionLabel:'Entrer sur la pelouse'});}
export function buildKickoffStep(session){const youth=['u15','youth'].includes(careerTier(session));const venue=session.home?(youth?'Depuis la main courante, les premières voix accompagnent chaque duel.':'Ton public réagit aux premières prises de balle.'):(youth?'Quelques voix adverses se font déjà entendre au bord du terrain.':'Le public adverse réagit à chaque ballon récupéré par son équipe.');return step(session,{phase:'kickoff',label:'COUP D’ENVOI',progress:10,minute:0,title:'Les premières secondes',text:`${venue} Ton premier ballon arrive et le rythme du match s’impose immédiatement.`,actionLabel:'Continuer'});}
export function buildDecisionStep(session,decision,index){const total=Math.max(1,session.moments?.length||1);return step(session,{phase:`moment_${index+1}`,kind:'decision',label:`MOMENT ${index+1}/${total}`,progress:Math.round(18+((index+1)/(total+1))*62),minute:decision.minute,title:decision.title,text:decision.description,choices:decision.choices,timedDecision:decision.timedDecision||null,actionLabel:'Choisir'});}
export function buildConsequenceStep(session,event,index){return step(session,{phase:`consequence_${index+1}`,label:'CONSÉQUENCE',progress:Math.min(86,28+index*13),minute:event.minute,title:event.title||'La séquence bascule',text:event.text,actionLabel:'Continuer'});}
export function buildContinuationStep(session){const tg=session.score[session.home?'home':'away'],og=session.score[session.home?'away':'home'];const text=tg>og?`${session.opponent} avance ses lignes. Les espaces s’ouvrent, mais chaque perte peut désormais coûter cher.`:tg<og?`Ton équipe joue plus haut. Les appels se multiplient et le temps commence à donner du poids à chaque possession.`:`Le milieu se resserre. Personne ne prend vraiment le dessus et la prochaine accélération peut suffire.`;return step(session,{phase:'match_continues',label:'LE MATCH CONTINUE',progress:52,minute:session.moments?.[session.currentMoment]||48,title:tg===og?'Le match se tend':tg>og?'Ils doivent sortir':'Il faut trouver une ouverture',text,actionLabel:'Continuer'});}
const UNEXPECTED_CONTEXTS=[{id:'opponent_press',title:'Le pressing monte',text:'Leur première ligne avance d’un bloc. À chaque relance, tu as moins de temps pour contrôler et lever la tête.',effects:{rating:-.04,fatigue:2,opponentThreat:.16}},{id:'space_opens',title:'Un espace se dessine',text:'Leur milieu ne suit plus tous les décrochages. Entre les lignes, quelques mètres commencent à apparaître.',effects:{goal:.07,assist:.04,opponentThreat:-.03}},{id:'crowd_surge',title:'La tension monte',text:'Une décision arbitrale déclenche les réactions autour du terrain. Les duels deviennent plus nerveux.',effects:{rating:.05,fatigue:1,cards:.04,opponentThreat:.06}},{id:'coach_shift',title:'Le coach ajuste',text:'Depuis la ligne, le coach te fait signe de jouer plus haut et d’attaquer l’espace dès la récupération.',effects:{goal:.04,assist:.06,rating:.04,opponentThreat:.02}}];
export function createUnexpectedContext(session,roll=Math.random()){const i=Math.min(UNEXPECTED_CONTEXTS.length-1,Math.floor(Math.max(0,roll)*UNEXPECTED_CONTEXTS.length));return{...UNEXPECTED_CONTEXTS[i],effects:{...UNEXPECTED_CONTEXTS[i].effects}};}
export function buildUnexpectedStep(session,context){return step(session,{phase:'unexpected_event',label:'LE MATCH CHANGE',progress:61,minute:session.moments?.[session.currentMoment]||57,title:context.title,text:context.text,actionLabel:'Continuer'});}
export function buildFullTimeStep(session,result){const contribution=result.goals>1?`${result.goals} buts`:result.goals===1?'1 but':'';const assist=result.assists>1?`${result.assists} passes décisives`:result.assists===1?'1 passe décisive':'';const impact=[contribution,assist].filter(Boolean).join(' et ');const finalDecision=session.events.at(-1)?.text||'';return step(session,{phase:'full_time_sequence',label:'FIN DE MATCH',progress:90,minute:90,title:'Les dernières possessions',text:`${finalDecision} ${session.opponent} pousse une dernière fois.${impact?` Ton match porte déjà la trace de ${impact}.`:''}`.trim(),actionLabel:'Attendre le coup de sifflet'});}
export function buildFinalWhistleStep(session,result){const verdict=result.result==='win'?'C’est gagné.':result.result==='loss'?'C’est terminé. La défaite est là.':'Personne n’a réussi à faire la différence.';return step(session,{phase:'final_whistle',label:'COUP DE SIFFLET',progress:97,minute:90,title:`${result.teamGoals} – ${result.opponentGoals}`,text:`${verdict} Les premières secondes appartiennent aux regards, aux souffles courts et aux réactions autour de toi.`,actionLabel:'Voir les réactions'});}
export function buildPostMatchReactions(state,session,result){const coachName=state?.social?.coachData?.name||state?.social?.formativeCoach||'Le coach';const lockerText=result.result==='win'?(result.rating>=7.5?'Tes coéquipiers viennent te chercher dès l’entrée du vestiaire. Ils savent ce que tu viens d’apporter.':'Les discussions reprennent peu à peu dans le vestiaire. La fatigue laisse enfin de la place au résultat.'):result.result==='loss'?'Personne ne parle tout de suite. Chacun retrouve sa place et rejoue ses propres actions.':'Le groupe reste partagé. Quelques joueurs parlent déjà de ce qui aurait pu faire basculer le match.';const coachText=result.rating>=8?`${coachName} te félicite devant le groupe, puis baisse la voix : « Maintenant, il faut être capable de le refaire. »`:result.rating<5.8?`${coachName} ne te fait pas de discours. « Demain, on regarde ça ensemble. »`:`${coachName} s’arrête près de toi : « Il y a du bon. Et un détail qu’on va corriger. »`;const mediaText=result.goals>=2?`Les premières réactions retiennent ton ${result.goals===2?'doublé':result.goals===3?'triplé':`${result.goals} buts`}. Ton téléphone commence à vibrer.`:result.goals===1||result.assists>0?'Ton action décisive revient dans les premiers commentaires du match.':result.rating>=7.5?'Quelques observateurs soulignent ton activité même sans statistique décisive.':'Les réactions parlent surtout du résultat collectif.';return[{id:'locker-room',icon:'👕',label:'VESTIAIRE',text:lockerText},{id:'coach',icon:'🧠',label:'COACH',text:coachText},{id:'media',icon:'🎙️',label:'MÉDIAS',text:mediaText}];}
export function buildReactionsStep(session,reactions){return step(session,{phase:'reactions',kind:'reactions',label:'APRÈS-MATCH',progress:100,title:'Ce que le match laisse derrière lui',text:'Le score ne bougera plus. Ton statut, tes relations et la manière dont on regarde ta performance, eux, peuvent encore changer.',items:reactions,actionLabel:'Continuer la carrière'});}
export default {buildPreMatchStep,buildKickoffStep,buildDecisionStep,buildConsequenceStep,buildContinuationStep,createUnexpectedContext,buildUnexpectedStep,buildFullTimeStep,buildFinalWhistleStep,buildPostMatchReactions,buildReactionsStep};