// domain/match/interactiveMatchController.js
// Propriétaire unique de la session et de la machine de phases du match jouable.
import { PlayerLogic } from '../../player.js';
import { PotentialSystem } from '../player/potentialSystem.js';
import { ConsequenceSystem } from '../decision/consequenceSystem.js';
import { MatchChoiceManager } from './matchChoiceManager.js';
import { clamp,number,positionGroup,opponentName,isHomeMatch,competitionLabel,matchType,importanceFor,buildScore,reconcilePlayerContributions } from './matchHelpers.js';
import { createDirectOpponent,updateDirectOpponent,directOpponentChoiceSet } from './directOpponentSystem.js';
import { buildPreMatchStep,buildKickoffStep,buildDecisionStep,buildConsequenceStep,buildContinuationStep,createUnexpectedContext,buildUnexpectedStep,buildFullTimeStep,buildFinalWhistleStep,buildPostMatchReactions,buildReactionsStep } from './interactiveMatchNarrative.js';
const FLOW_VERSION=3;
const CONSEQUENCE_MAP={technique:'attributes.controle',physique:'attributes.puissance',vitesse:'attributes.vitesse',defense:'attributes.defense',mental:'mental',charisme:'reputation',discipline:'discipline',relationCoach:'relationCoach',vestiaire:'vestiaire'};
function choiceConsequences(choice={}){const source=choice.consequences||{},permanent={...(source.permanent||{}),...(source.emotional||{})};for(const[key,value]of Object.entries(choice.impacts?.stats||{})){const target=CONSEQUENCE_MAP[key];if(target&&Number.isFinite(Number(value))&&permanent[target]===undefined)permanent[target]=Number(value);}if(!Object.keys(permanent).length&&!Array.isArray(source.temporary)&&!Array.isArray(source.effects))return null;return{...source,permanent,temporary:[...(source.temporary||[]),...(source.effects||[])]};}
function mechanicalImpacts(choice={}){const impacts=choice.impacts||{};return{...(impacts.matchBonuses||{}),...impacts};}
function technicalRating(player={}){const a=player.attributes||{};return clamp((number(a.controle??a.dribble??a.technique??player.technique)||40)*.55+(number(a.dribble??a.controle??a.technique??player.technique)||40)*.45,1,99);}
function originId(player={}){return String(player.origin?.id||player.origin||'').toUpperCase();}
function techniqueChoices(player,session,moment){const tech=technicalRating(player),origin=originId(player),futsal=origin==='FUTSAL',street=origin==='STREET';const pressure=moment>=78||session.type==='final'||session.type==='rival';const pool=[];
 if(tech>=62&&(futsal||street||tech>=75))pool.push({text:'Éliminer dans un petit espace',gesture:'Changement d’appui',originOpportunity:futsal?'futsal':street?'street':null,impacts:{ratingBonus:.12,duelBonus:.12,goalChance:.035,fatigueRisk:2,technicalRisk:.08}});
 if(tech>=72&&(futsal||street))pool.push({text:'Tenter le petit pont',gesture:'Petit pont',originOpportunity:futsal?'futsal':'street',impacts:{ratingBonus:.16,duelBonus:.16,goalChance:.045,fatigueRisk:2,technicalRisk:.13}});
 if(tech>=80)pool.push({text:'Créer avec l’extérieur du pied',gesture:'Extérieur du pied',impacts:{ratingBonus:.15,assistChance:.075,goalChance:.025,technicalRisk:.09}});
 if(tech>=86&&pressure)pool.push({text:'Tenter le geste que personne n’attend',gesture:futsal?'Talonnade':street?'Double contact':'Geste acrobatique',originOpportunity:futsal?'futsal':street?'street':null,impacts:{ratingBonus:.2,goalChance:.075,assistChance:.04,fatigueRisk:3,technicalRisk:.18}});
 return pool;}
function decisionCount(match){const selection=match?.playerSelection,minutes=Math.max(1,number(match?.minutes??selection?.minutes??90)),type=matchType(match),importance=importanceFor(match);if(selection?.started===false)return clamp(Math.round(minutes/18),1,3);if(type==='final')return 4+Math.floor(Math.random()*3);if(type==='rival')return 3+Math.floor(Math.random()*3);if(importance==='exceptional')return 3+Math.floor(Math.random()*3);if(importance==='important')return 2+Math.floor(Math.random()*3);return 1+Math.floor(Math.random()*2);}
function playableDecisionMoments(match){const count=decisionCount(match),selection=match?.playerSelection,minutes=Math.max(1,number(match?.minutes??selection?.minutes??90)),start=selection?.started===false?Math.max(45,90-minutes):8,end=selection?.started===false?88:86;if(count===1)return[Math.round((start+end)/2)];const span=end-start;return Array.from({length:count},(_,i)=>Math.round(start+span*((i+1)/(count+1))));}
function pressureTimer(state,session,moment,index){const decisive=session.type==='final'||session.type==='rival'||session.importance==='exceptional';const late=moment>=76;const last=index===session.moments.length-1;if(!decisive||(!late&&!last))return null;const mental=number(state.player?.mental??state.player?.attributes?.mental??50),seconds=clamp(Math.round(5+(mental-50)/18),4,8);return{seconds,reason:session.type==='final'?'finale':session.type==='rival'?'rivalité':'moment décisif'};}
function decisionDescription(session,moment,index,fallback){if(index===0)return`À la ${moment}e minute, le duel qui se dessinait depuis le début du match devient enfin une vraie occasion. ${fallback||'Tu as une seconde pour choisir comment l’attaquer.'}`;const previous=session.events.at(-1)?.text||session.unexpectedContext?.text||'Le rapport de force a changé.';return`${previous} À la ${moment}e minute, une nouvelle fenêtre s’ouvre.`;}
function decisionTitle(session,moment,index){const direct=session.directOpponent||{},won=number(direct.playerDuelsWon),lost=number(direct.opponentDuelsWon),own=number(session.score?.[session.home?'home':'away']),opp=number(session.score?.[session.home?'away':'home']);if(index===0)return`${moment}' · Ton duel commence vraiment`;if(won>=2&&won>lost)return`${moment}' · Tu as créé la brèche`;if(lost>=2&&lost>won)return`${moment}' · Il vient encore te chercher`;if(moment>=70&&own===opp)return`${moment}' · Un geste peut faire basculer le match`;if(moment>=75&&own<opp)return`${moment}' · Il faut provoquer quelque chose`;return`${moment}' · Le rapport de force a changé`;}
function buildDecision(state,session,moment,index){const configured=MatchChoiceManager.getMatchDilemma(session.type,session.opponent,state.player?.position||state.player?.positionId)?.choices||[];const direct=directOpponentChoiceSet({playerPosition:state.player?.position||state.player?.positionId,minute:moment,opponent:session.directOpponent});const technical=techniqueChoices(state.player,session,moment);let raw=technical.length?[...direct.slice(0,3),...technical.slice(0,2),...configured.slice(0,1)]:[...direct,...configured.slice(0,1)];const seen=new Set();raw=raw.filter(c=>{const k=c.text||c.texte||c.label;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,5);const choices=raw.map(choice=>({...choice,text:choice.text||choice.texte||choice.label||'Choisir',impacts:mechanicalImpacts(choice),consequences:choiceConsequences(choice)}));return{id:`${session.id}:decision:${index+1}`,minute:moment,phase:moment<45?'Première période':'Seconde période',title:decisionTitle(session,moment,index),description:decisionDescription(session,moment,index,null),choices,timedDecision:pressureTimer(state,session,moment,index)};}
function playerTeamScore(s){return number(s.score[s.home?'home':'away']);}function opponentScore(s){return number(s.score[s.home?'away':'home']);}function setPlayerTeamScore(s,v){s.score[s.home?'home':'away']=Math.max(0,Math.floor(number(v)));}function setOpponentScore(s,v){s.score[s.home?'away':'home']=Math.max(0,Math.floor(number(v)));}
function applyEffects(s,e={}){s.modifiers.rating+=number(e.ratingBonus??e.rating);s.modifiers.goal+=number(e.goalChance??e.goal)+number(e.counterAttack)*.20;s.modifiers.assist+=number(e.assistChance??e.assist)+number(e.counterAttack)*.08;s.modifiers.duel+=number(e.duelBonus??e.duel);s.modifiers.fatigue+=number(e.fatigueRisk??e.fatigue);s.modifiers.cards+=number(e.cardRisk??e.cards);s.modifiers.opponentThreat+=number(e.opponentThreat);s.modifiers.rating+=number(e.passAccuracy)*.20+number(e.teamBoost)*.18;}
function resolveChoice(state,s,choiceIndex,decisionIndex){const d=s.decision,c=d?.choices?.[Number(choiceIndex)];if(!c)throw new Error('Choix de match invalide.');const consequence=c.consequences?ConsequenceSystem.applyToState(state,{...c,impacts:{},consequences:c.consequences},{source:'Match'}):null;applyEffects(s,c.impacts||{});const tech=technicalRating(state.player),risk=number(c.impacts?.technicalRisk),failed=risk>0&&Math.random()<clamp(risk-(tech-50)/260,.03,.32);const duel=number(c.impacts?.duelBonus)>0||/duel|éliminer|provoquer|petit pont|déborder|dribb|feinter/i.test(c.text||'');let event;if(failed)event={title:'Il lit ton geste',icon:'⚠️',text:`Ton vis-à-vis ne mord pas. ${c.gesture&&c.gesture!=='Changement d’appui'?`${c.gesture} ne passe pas et `:''}il récupère le demi-mètre que tu cherchais. Tu dois immédiatement te replacer.`};else{const roll=Math.random();if(roll<clamp(.16+number(c.impacts?.goalChance)*1.6,.12,.58))event={title:'Tu le mets en retard',icon:'⚡',text:'Ton premier geste le force à tourner les hanches. Une seconde zone s’ouvre devant toi et, cette fois, la défense doit courir vers son propre but.'};else if(roll<.42+number(c.impacts?.passAccuracy))event={title:'La ligne est cassée',icon:'🎯',text:'Tu attires ton vis-à-vis juste assez longtemps avant de lâcher le ballon. Ton partenaire reçoit face au jeu et l’action gagne immédiatement vingt mètres.'};else if(duel)event={title:'Le duel tourne pour toi',icon:'🛡️',text:'Tu restes sur tes appuis jusqu’au dernier instant. Ton adversaire direct doit se retourner et te poursuivre au lieu de t’attendre.'};else event={title:'Le choix ouvre la suite',icon:'🧠',text:consequence?.responseText||'Tu fais le geste juste sans forcer la suite. Le ballon ressort proprement et ton vis-à-vis doit recommencer son travail.'};}s.directOpponent=updateDirectOpponent(s.directOpponent,{success:failed?false:true,duel,choice:c.text});event={...event,minute:d.minute,decisionIndex,choice:c.text,gesture:c.gesture||null,directOpponent:true};s.decisions.push({minute:d.minute,phase:d.phase,choice:c.text,gesture:c.gesture||null,consequence:consequence?.queued||0,event:event.text});s.events.push(event);return event;}
function resolveTimeout(s){const d=s.decision,event={title:'Une seconde de trop',icon:'⏱️',text:'Tu vois l’ouverture, mais ton hésitation suffit. Ton vis-à-vis revient sur ses appuis et la fenêtre disparaît.',minute:d.minute,decisionIndex:s.currentMoment,choice:'Aucune décision — temps écoulé',timedOut:true};s.modifiers.rating-=.08;s.modifiers.opponentThreat+=.04;s.directOpponent=updateDirectOpponent(s.directOpponent,{success:false,duel:true,choice:'hésitation'});s.decisions.push({minute:d.minute,phase:d.phase,choice:event.choice,timedOut:true,event:event.text});s.events.push(event);return event;}
function simulateMiddlePhase(s){const teamChance=clamp(.30+s.modifiers.goal+s.modifiers.assist*.35,.12,.72),opponentChance=clamp(.28+s.modifiers.opponentThreat-s.modifiers.duel*.22,.08,.68);if(Math.random()<teamChance)setPlayerTeamScore(s,playerTeamScore(s)+1);if(Math.random()<opponentChance)setOpponentScore(s,opponentScore(s)+1);}
function generatedContribution(chance,max){let total=0;for(let i=0;i<max;i++)if(Math.random()<clamp(chance*(1-i*.18),.01,.72))total++;return total;}
function finalizeResult(state,s){const player=state.player,group=positionGroup(player.position),opponentStrength=number(s.match?.opponentStrength??s.match?.opponentOverall??50)||50,rating=Number(clamp(s.playerRatingBase+s.modifiers.rating+(Math.random()-.5)*1.05,4,10).toFixed(1)),goalChance=clamp(.04+number(player.attributes?.tir??40)/99*.16+s.modifiers.goal,.01,.72),assistChance=clamp(.06+number(player.attributes?.passe??40)/99*.18+s.modifiers.assist,.01,.68),generatedTeamGoals=Math.max(playerTeamScore(s),buildScore({player,rating,group,goalChance,opponentStrength})),generatedOpponentGoals=Math.max(opponentScore(s),Math.floor(Math.random()*Math.max(1,1+opponentStrength/58+s.modifiers.opponentThreat))),rawGoals=group==='goalkeeper'?0:generatedContribution(goalChance,group==='attacker'?4:2),rawAssists=generatedContribution(assistChance,2),contributions=reconcilePlayerContributions(generatedTeamGoals,rawGoals,rawAssists),selection=s.match?.playerSelection||{started:true,appearance:'starter',minutes:90},teamGoals=contributions.teamGoals,opponentGoals=Math.min(6,Math.max(0,generatedOpponentGoals)),yellowCards=Math.random()<clamp(s.modifiers.cards,0,.72)?1:0,fatigueCost=clamp(Math.round(s.modifiers.fatigue),-3,8);setPlayerTeamScore(s,teamGoals);setOpponentScore(s,opponentGoals);return{matchId:s.id,matchIndex:s.matchIndex,fixture:s.match,competitionId:s.match?.competitionId||null,competitionType:s.match?.competitionType||s.match?.type||null,competitionName:s.competition,phase:s.match?.phase||null,round:s.match?.round||s.match?.europeanRound||null,type:s.type,importance:s.importance,opponent:s.opponent,opponentStrength,home:s.home,venue:s.match?.venue||null,score:{...s.score},teamGoals,opponentGoals,result:teamGoals>opponentGoals?'win':teamGoals<opponentGoals?'loss':'draw',rating,goals:contributions.goals,assists:contributions.assists,tackles:group==='goalkeeper'?0:Math.max(1,Math.floor(2+Math.random()*6+s.modifiers.duel*8)),yellowCards,fatigueCost,cleanSheet:group==='goalkeeper'&&opponentGoals===0,played:true,playerPlayed:true,appearance:selection.appearance||(selection.started===false?'substitute':'starter'),started:selection.started!==false,minutesPlayed:number(s.match?.minutes??selection.minutes??90)||90,decisions:[...s.decisions],events:[...s.events],directOpponent:{...s.directOpponent},interactiveFlowVersion:FLOW_VERSION};}
function ensureDirectOpponent(s){if(s.directOpponent)return;s.directOpponent=createDirectOpponent({seed:s.match?.id||`${s.matchIndex||0}:${s.opponent||''}`,playerPosition:s.playerPosition,strength:s.match?.opponentStrength??s.match?.opponentOverall??50});}
function migrateActiveSession(s){s.flowVersion=FLOW_VERSION;s.team||='Ton équipe';s.modifiers||={rating:0,goal:0,assist:0,duel:0,fatigue:0,cards:0,opponentThreat:0};s.modifiers.opponentThreat||=0;s.moments=Array.isArray(s.moments)&&s.moments.length?s.moments:playableDecisionMoments(s.match);s.currentMoment=number(s.currentMoment);ensureDirectOpponent(s);if(!s.step){s.stage=s.decision?`moment_${s.currentMoment+1}`:'pre_match';s.step=s.decision?buildDecisionStep(s,s.decision,s.currentMoment):buildPreMatchStep(s);}return s;}
export function startInteractiveMatch(state,scheduledMatch,matchIndex=0){if(!state?.player)throw new Error('Impossible de démarrer un match sans joueur.');const moments=playableDecisionMoments(scheduledMatch),playerPosition=state.player.position||state.player.positionId||null,opponent=opponentName(scheduledMatch),s={id:`match-session-${Date.now()}-${matchIndex}`,flowVersion:FLOW_VERSION,matchIndex,match:scheduledMatch,type:matchType(scheduledMatch),importance:importanceFor(scheduledMatch),team:state.player.club||'Ton équipe',playerPosition,playerAge:state.player.age||null,opponent,home:isHomeMatch(scheduledMatch),competition:competitionLabel(scheduledMatch),moments,currentMoment:0,decisions:[],events:[],score:{home:0,away:0},modifiers:{rating:0,goal:0,assist:0,duel:0,fatigue:0,cards:0,opponentThreat:0},playerRatingBase:6.2+(number(state.player.overall)-50)*.035,stage:'pre_match',step:null,decision:null,result:null,reactions:[],finished:false,directOpponent:createDirectOpponent({seed:scheduledMatch?.id||`${matchIndex}:${opponent}`,playerPosition,strength:scheduledMatch?.opponentStrength??scheduledMatch?.opponentOverall??50})};s.step=buildPreMatchStep(s);return s;}
export function advanceInteractiveMatch(state,activeSession,action={}){if(!state?.player||!activeSession||activeSession.finished)throw new Error('Session de match invalide.');const s=migrateActiveSession(activeSession),choiceIndex=typeof action==='number'?action:action?.choiceIndex,timedOut=Boolean(action?.timedOut);if(s.step?.kind==='decision'&&!timedOut&&(choiceIndex===null||choiceIndex===undefined||!Number.isInteger(Number(choiceIndex))))return{finished:false,session:s,step:s.step,decision:s.decision,event:s.events.at(-1)||null};if(s.stage==='pre_match'){s.stage='kickoff';s.step=buildKickoffStep(s);}else if(s.stage==='kickoff'){s.stage='decision';s.decision=buildDecision(state,s,s.moments[0],0);s.step=buildDecisionStep(s,s.decision,0);}else if(s.stage==='decision'){const index=s.currentMoment,event=timedOut?resolveTimeout(s):resolveChoice(state,s,choiceIndex,index);s.stage='consequence';s.step=buildConsequenceStep(s,event,index);}else if(s.stage==='consequence'){simulateMiddlePhase(s);s.currentMoment+=1;if(s.currentMoment<s.moments.length){s.stage='match_continues';s.step=buildContinuationStep(s);}else{s.result=finalizeResult(state,s);s.result.postMatchReactions=buildPostMatchReactions(state,s,s.result);s.stage='full_time_sequence';s.decision=null;s.step=buildFullTimeStep(s,s.result);}}else if(s.stage==='match_continues'){s.unexpectedContext=createUnexpectedContext(s);applyEffects(s,s.unexpectedContext.effects);s.stage='unexpected_event';s.step=buildUnexpectedStep(s,s.unexpectedContext);}else if(s.stage==='unexpected_event'){s.stage='decision';s.decision=buildDecision(state,s,s.moments[s.currentMoment],s.currentMoment);s.step=buildDecisionStep(s,s.decision,s.currentMoment);}else if(s.stage==='full_time_sequence'){s.stage='final_whistle';s.step=buildFinalWhistleStep(s,s.result);}else if(s.stage==='final_whistle'){s.reactions=s.result?.postMatchReactions||buildPostMatchReactions(state,s,s.result);s.stage='reactions';s.step=buildReactionsStep(s,s.reactions);}else if(s.stage==='reactions'){s.stage='complete';s.step=null;s.finished=true;return{finished:true,session:s,result:s.result,events:s.events};}else throw new Error(`Phase de match inconnue : ${s.stage}`);return{finished:false,session:s,step:s.step,decision:s.step?.kind==='decision'?s.decision:null,event:s.events.at(-1)||null};}
export function resolveInteractiveDecision(state,session,choiceIndex){return advanceInteractiveMatch(state,session,{choiceIndex});}
export function commitInteractiveResult(state,result){const player=state?.player;if(!player||!result)return null;player.stats||={};const previous=number(player.stats.matchesPlayed),total=previous+1;player.stats.matchesPlayed=total;player.stats.starts=number(player.stats.starts)+(result.started===false?0:1);player.stats.subAppearances=number(player.stats.subAppearances)+(result.started===false?1:0);player.stats.minutesPlayed=number(player.stats.minutesPlayed)+number(result.minutesPlayed||90);player.stats.goals=number(player.stats.goals)+number(result.goals);player.stats.assists=number(player.stats.assists)+number(result.assists);player.stats.tackles=number(player.stats.tackles)+number(result.tackles);player.stats.yellowCards=number(player.stats.yellowCards)+number(result.yellowCards);if(result.cleanSheet)player.stats.cleanSheets=number(player.stats.cleanSheets)+1;player.stats.averageRating=Number((((number(player.stats.averageRating)*previous)+number(result.rating))/total).toFixed(1));player.morale=clamp(number(player.morale??50)+(result.rating>=7?2:result.rating<5.5?-2:0),0,100);const fitnessCost=Math.max(1,Math.round(number(result.minutesPlayed||90)/30)+number(result.fatigueCost));player.fitness=clamp(number(player.fitness??80)-fitnessCost,0,100);PotentialSystem.recordMatch(player,{rating:result.rating},1);PlayerLogic.applyProgression(player,{xp:Math.round(70+result.rating*40+result.goals*90+result.assists*60),type:'match'});return result;}
export const InteractiveMatchController=Object.freeze({startInteractiveMatch,advanceInteractiveMatch,resolveInteractiveDecision,commitInteractiveResult});export default InteractiveMatchController;
