import { directOpponentBeat } from './directOpponentSystem.js';

function careerTier({age,level,competition}={}){const a=Number(age||0),text=String(level||competition||'').toLowerCase();if((a&&a<=15)||/u ?15/.test(text))return'u15';if((a&&a<=18)||/u ?1[678]|formation|academy|jeune/.test(text))return'youth';if(/regional|régional|national|semi|amateur/.test(text))return'semi';return'pro';}
function scorePressure({score,home=true,minute}={}){if(!score)return null;const own=Number(score[home?'home':'away']||0),opp=Number(score[home?'away':'home']||0),m=Number(minute||0);if(m>=75&&own<opp)return'Le temps commence à compter autant que l’espace.';if(m>=80&&own>opp)return'Cette fois, perdre le ballon pourrait coûter plus cher que ne pas forcer l’action.';if(m>=70&&own===opp)return'Le score donne soudain plus de poids à chaque choix.';return null;}
function role(position=''){const value=String(position||'').toLowerCase();if(/gardien/.test(value))return'goalkeeper';if(/déf|def|latéral|lateral/.test(value))return'defender';if(/milieu|relayeur|meneur|\b6\b|\b8\b|\b10\b/.test(value))return'midfielder';if(/ailier/.test(value))return'winger';return'attacker';}
function attackingScene({minute,index,directOpponent,memory}={}){const m=Number(minute||0),won=Number(directOpponent?.playerDuelsWon||0);if(index>0&&won>=2)return`À la ${m}e, tu reçois lancé. Ton vis-à-vis recule maintenant avant même ton contrôle. Tu l’as déjà éliminé deux fois et il n’ose plus sortir franchement. Un coéquipier attaque l’intervalle et te crie « Là ! ». Devant toi, la surface commence à s’ouvrir.`;if(index>0&&Number(memory?.technicalFailures)>=2)return`À la ${m}e, tu récupères un ballon entre les lignes. Tes dernières tentatives n’ont pas abouti, mais cette fois ton vis-à-vis arrive avec une demi-seconde de retard. Un partenaire part immédiatement dans son dos. Tu peux forcer le duel, combiner ou attendre encore un déplacement.`;return`À la ${m}e, tu décroches pour recevoir puis te retournes dans le mouvement. Ton vis-à-vis doit pivoter, un second défenseur hésite à sortir et un coéquipier attaque déjà la profondeur. Pendant une seconde, trois solutions existent en même temps.`;}
function midfieldScene({minute,index,directOpponent}={}){const m=Number(minute||0),won=Number(directOpponent?.playerDuelsWon||0);if(index>0&&won>0)return`À la ${m}e, ton milieu adverse vient moins vite qu’au début. Tu l’as déjà attiré hors de sa zone une fois. À ta réception, une passe verticale s’ouvre tandis qu’un partenaire démarre sur le côté opposé.`;return`À la ${m}e, tu reçois entre deux lignes avec un joueur dans ton dos. Devant toi, un défenseur hésite à sortir et un appel traverse son champ de vision. Ton contrôle peut décider si l’action accélère ou meurt ici.`;}
function defensiveScene({minute,index,directOpponent}={}){const m=Number(minute||0),lost=Number(directOpponent?.opponentDuelsWon||0);if(index>0&&lost>0)return`À la ${m}e, ton adversaire direct redemande immédiatement le ballon. Il a gagné le dernier duel et tente de reproduire exactement la même course. Cette fois tu connais son intention avant même que la passe parte.`;return`À la ${m}e, ton adversaire direct reçoit lancé sur ton côté. Personne ne peut venir fermer tout de suite. Il ralentit une fraction de seconde pour te faire choisir : sortir, temporiser ou couper la trajectoire suivante.`;}
function goalkeeperScene({minute}={}){return`À la ${Number(minute||0)}e, une passe en retrait arrive avec l’avant-centre déjà lancé vers toi. Ton défenseur s’écarte pour proposer court, mais l’espace existe aussi derrière le premier rideau. Tu n’auras pas le temps de changer d’idée deux fois.`;}
export function decisionNarration({minute,memory={},index=0,position=null,age=null,level=null,competition=null,score=null,home=true,confidence=null,fatigue=null,coachTrust=null,directOpponent=null}={}){
 const tier=careerTier({age,level,competition}),m=Number(minute||0),pressure=scorePressure({score,home,minute:m}),playerRole=role(position);const direct=directOpponentBeat(directOpponent,{minute:m,index,playerPosition:position});
 if(Number(fatigue)>=78)return`À la ${m}e, tu vois l’ouverture avant les autres, mais tes jambes répondent un peu moins vite. Ton adversaire direct le sent aussi et avance d’un pas. ${pressure||'Il faut décider si ce ballon mérite vraiment ton prochain sprint.'}`;
 if(Number(memory.pressureMisses)>0)return`À la ${m}e, une nouvelle fenêtre apparaît. La précédente s’était refermée pendant ton hésitation ; cette fois tu la reconnais tout de suite. ${direct||''} ${pressure||''}`.trim();
 if(playerRole==='goalkeeper')return`${goalkeeperScene({minute:m})} ${pressure||''}`.trim();
 if(playerRole==='defender')return`${defensiveScene({minute:m,index,directOpponent})} ${direct||''} ${pressure||''}`.trim();
 if(playerRole==='midfielder')return`${midfieldScene({minute:m,index,directOpponent})} ${direct||''} ${pressure||''}`.trim();
 if(playerRole==='winger'||playerRole==='attacker'){
   const base=attackingScene({minute:m,index,directOpponent,memory});
   if(Number(confidence)>=75)return`${base} Tu demandes le ballon sans détourner le regard du duel. ${direct||''} ${pressure||''}`.trim();
   if(Number(confidence)<=35)return`${base} Ton premier réflexe est de sécuriser, mais l’espace devant toi ne restera pas ouvert longtemps. ${direct||''} ${pressure||''}`.trim();
   if(Number(coachTrust)>=75)return`${base} Depuis le bord du terrain, le coach lâche seulement : « Vas-y. » ${direct||''} ${pressure||''}`.trim();
   return`${base} ${direct||''} ${pressure||''}`.trim();
 }
 if(index===0&&tier==='u15')return`À la ${m}e, tu reçois avec assez d’espace pour lever la tête. Une voix familière t’encourage au bord du terrain, puis tout disparaît derrière la situation qui s’ouvre devant toi. ${direct||''}`.trim();
 return`À la ${m}e, le rapport de force change autour de toi. ${direct||''} ${pressure||''}`.trim();
}
export default decisionNarration;
