// domain/match/matchPerformanceEngine.js
// Moteur commun de performance individuelle. Les attributs lus ici passent
// désormais par V2 : 12 attributs football + mental caché.
import { get as getAttribute, ensure as ensureAttributesV2 } from '../../attributeSystemV2.js';
const clamp=(v,min,max)=>Math.min(max,Math.max(min,Number(v)||0));const n=v=>Number.isFinite(Number(v))?Number(v):0;const rand=(min,max)=>min+Math.random()*(max-min);
const ROLE_WEIGHTS={attacker:{finish:.23,speed:.12,dribble:.14,pass:.10,defense:.04,physical:.09,mental:.12,positioning:.16},midfielder:{finish:.06,speed:.09,dribble:.12,pass:.24,defense:.12,physical:.09,mental:.14,positioning:.14},defender:{finish:.02,speed:.09,dribble:.06,pass:.13,defense:.29,physical:.16,mental:.15,positioning:.10},goalkeeper:{finish:.01,speed:.05,dribble:.03,pass:.13,defense:.28,physical:.13,mental:.24,positioning:.13}};
function roleOf(position){const p=String(position||'').toUpperCase();if(['GK','GB','G'].includes(p))return'goalkeeper';if(['DC','CB','DD','RB','DG','LB','D','LAT'].includes(p))return'defender';if(['MC','CM','MOC','CAM','MD','MG','M','MDEF','MOFF'].includes(p))return'midfielder';return'attacker';}
function attribute(player,key,fallback=50){ensureAttributesV2(player);const map={finish:'finition',speed:'vitesse',dribble:'dribble',pass:'passe',defense:'defense',physical:'puissance',mental:'concentration',positioning:'placement'};return getAttribute(player,map[key]||key,fallback);}
function mental(player,key,fallback=50){ensureAttributesV2(player);return getAttribute(player,key,fallback);}
function expressionFactor(player){const fitness=clamp(player?.fitness??80,0,100),morale=clamp(player?.morale??70,0,100),concentration=mental(player,'concentration',50),confidence=clamp(morale*.55+concentration*.45,0,100),fatiguePenalty=Math.pow((100-fitness)/100,1.35)*.22,mentalPenalty=Math.pow((100-confidence)/100,1.15)*.14;return clamp(1-fatiguePenalty-mentalPenalty,.58,1.04);}
function consistency(player){return clamp(.78+mental(player,'regularite',60)/450,.80,.999);}
function relativeLevel(player,opponentStrength=50){const w=ROLE_WEIGHTS[roleOf(player?.position)],raw=attribute(player,'finish')*w.finish+attribute(player,'speed')*w.speed+attribute(player,'dribble')*w.dribble+attribute(player,'pass')*w.pass+attribute(player,'defense')*w.defense+attribute(player,'physical')*w.physical+attribute(player,'mental')*w.mental+attribute(player,'positioning')*w.positioning;return clamp((raw-clamp(opponentStrength,25,95))/45,-.55,.55);}
function situationProfile(player,context={}){const role=roleOf(player?.position),fitness=clamp(player?.fitness??80,0,100),morale=clamp(player?.morale??70,0,100),opponentStrength=n(context.opponentStrength??context.opponentOverall??55)||55,difficulty=clamp((opponentStrength-50)/50,-.5,.9),expression=expressionFactor(player),relative=relativeLevel(player,opponentStrength),consistencyFactor=consistency(player),base=6.25+relative*1.15+(expression-.82)*1.15,pressure=context.important?(mental(player,'sangFroid',50)-50)/250:0,randomness=rand(-.48,.48)*consistencyFactor;return{role,expression,relative,difficulty,base,ratingBase:base+pressure+randomness,fitness,morale,mental:mental(player,'concentration',50),consistencyFactor};}
function simulateActions(player,context,profile){const role=profile.role,minutes=clamp(n(context.minutes||80),20,105),volume=clamp(Math.round(minutes/5+rand(-2,3)),6,24),opponentStrength=n(context.opponentStrength??context.opponentOverall??55)||55,difficulty=clamp((opponentStrength-50)/50,-.4,.8),actions={chances:0,keyActions:0,successfulActions:0,failedActions:0,shots:0,shotsOnTarget:0,passes:0,successfulPasses:0,tackles:0,interceptions:0,duels:0,duelsWon:0,goals:0,assists:0,cleanSheet:false},technical=clamp((attribute(player,'pass')+attribute(player,'dribble')+attribute(player,'mental'))/3/99,.1,.98),attacking=clamp((attribute(player,'finish')*.42+attribute(player,'dribble')*.20+attribute(player,'speed')*.18+attribute(player,'mental')*.20)/99,.1,.98),defensive=clamp((attribute(player,'defense')*.52+attribute(player,'physical')*.18+attribute(player,'mental')*.30)/99,.1,.98);
 for(let i=0;i<volume;i++){const pressure=clamp(difficulty+rand(-.25,.25),-.4,.9);if(role==='attacker'){const chance=clamp(attacking*.34-pressure*.09+profile.expression*.08,.03,.40);if(Math.random()<chance){actions.chances++;actions.shots++;const onTarget=Math.random()<clamp(attribute(player,'tir')/120+profile.expression*.18,.18,.90);if(onTarget)actions.shotsOnTarget++;if(onTarget&&Math.random()<clamp(attribute(player,'finition')/155+profile.expression*.16-pressure*.08,.03,.48))actions.goals++;}Math.random()<clamp(technical*.72-pressure*.08,.30,.94)?actions.successfulActions++:actions.failedActions++;}else if(role==='midfielder'){actions.passes+=1+Math.floor(Math.random()*3);const passRate=clamp(technical*.90-pressure*.08,.45,.96);actions.successfulPasses+=Math.round((1+Math.random()*2)*passRate);if(Math.random()<clamp((attribute(player,'passe')+attribute(player,'vision'))/220-pressure*.05,.06,.40))actions.keyActions++;if(Math.random()<defensive*.24){actions.tackles++;actions.duels++;if(Math.random()<defensive)actions.duelsWon++;}}else if(role==='defender'){actions.duels+=1+(Math.random()<.45?1:0);const won=Math.random()<clamp(defensive*.92-pressure*.06,.25,.93);if(won)actions.duelsWon++;if(Math.random()<defensive*.35)actions.tackles++;if(Math.random()<defensive*.25)actions.interceptions++;actions.passes+=1+Math.floor(Math.random()*2);actions.successfulPasses+=Math.round(actions.passes*clamp(technical*.8,.35,.94));}else{const saves=Math.max(1,Math.round(rand(2,7)+difficulty*1.5));actions.keyActions+=Math.max(0,Math.round(saves*clamp(attribute(player,'defense')/110,.25,.88)));actions.shotsOnTarget=saves;actions.successfulActions=actions.keyActions;}}
 if(role!=='goalkeeper'&&actions.passes>0)actions.successfulPasses=Math.min(actions.passes,actions.successfulPasses);if(role==='goalkeeper')actions.cleanSheet=Math.random()<clamp(.62+attribute(player,'defense')/400-difficulty*.18,.12,.78);actions.assists=Math.random()<clamp((attribute(player,'passe')+attribute(player,'vision'))/520,.02,.24)?1:0;actions.keyActions+=actions.shotsOnTarget+actions.interceptions;return actions;}
function ratingFromActions(profile,actions,context={}){const role=profile.role;let score=profile.ratingBase;const total=Math.max(1,actions.successfulActions+actions.failedActions),successRate=actions.successfulActions/total;score+=(successRate-.55)*.72;score+=Math.min(actions.keyActions,8)*.055;score-=Math.min(actions.failedActions,8)*.045;score+=actions.goals*(role==='attacker'?.62:.48);score+=actions.assists*.30;if(role==='attacker')score+=actions.shotsOnTarget*.055;if(role==='midfielder')score+=actions.successfulPasses/Math.max(1,actions.passes)*.30;if(role==='defender')score+=actions.duelsWon*.055+actions.interceptions*.08;if(role==='goalkeeper')score+=actions.keyActions*.08+(actions.cleanSheet?.32:0);if(context.result==='win')score+=.08;if(context.result==='loss')score-=.08;return Number(clamp(score,4.2,9.4).toFixed(1));}
export function evaluateMatch(player,context={}){const profile=situationProfile(player,context),actions=simulateActions(player,context,profile),rating=ratingFromActions(profile,actions,context);return{rating,goals:actions.goals,assists:actions.assists,tackles:actions.tackles,interceptions:actions.interceptions,successfulPasses:actions.successfulPasses,passes:actions.passes,cleanSheet:actions.cleanSheet,shots:actions.shots,shotsOnTarget:actions.shotsOnTarget,duels:actions.duels,duelsWon:actions.duelsWon,expression:Number(profile.expression.toFixed(3)),performanceLevel:Number(profile.relative.toFixed(3))};}
export function recalibrateMatchResult(player,result={},context={}){const evaluated=evaluateMatch(player,{...context,result:result.result,important:context.important??false}),decisionCount=Array.isArray(result.decisions)?result.decisions.length:0,decisionQuality=Array.isArray(result.events)?result.events.length:0,interactionShift=clamp(decisionCount*.025+decisionQuality*.015,-.12,.14);return{...result,...evaluated,rating:Number(clamp(evaluated.rating+interactionShift,4.2,9.4).toFixed(1))};}
export function recalibrateReport(player,report,options={}){if(!report)return report;const results=Array.isArray(report.results)?report.results:Array.isArray(report.summary?.matchResults)?report.summary.matchResults:[];if(!results.length)return report;const recalibrated=results.map(result=>recalibrateMatchResult(player,result,{opponentStrength:result.opponentStrength??options.opponentStrength??55,opponentOverall:result.opponentOverall,important:['final','rival'].includes(String(result.type||'').toLowerCase())||result.importance==='important'}));const summary=report.summary||{},avgRating=Number((recalibrated.reduce((sum,r)=>sum+n(r.rating),0)/recalibrated.length).toFixed(1));return{...report,results:recalibrated,summary:{...summary,rating:avgRating,goals:recalibrated.reduce((s,r)=>s+n(r.goals),0),assists:recalibrated.reduce((s,r)=>s+n(r.assists),0),passes:recalibrated.reduce((s,r)=>s+n(r.successfulPasses),0),tackles:recalibrated.reduce((s,r)=>s+n(r.tackles),0),cleanSheets:recalibrated.reduce((s,r)=>s+(r.cleanSheet?1:0),0),matchesPlayed:recalibrated.length,matchResults:recalibrated}};}
export default{evaluateMatch,recalibrateMatchResult,recalibrateReport};