function careerTier({age,level,competition}={}){const a=Number(age||0),text=String(level||competition||'').toLowerCase();if((a&&a<=15)||/u15/.test(text))return'u15';if((a&&a<=18)||/u17|u18|formation|academy|jeune/.test(text))return'youth';if(/regional|régional|national|semi|amateur/.test(text))return'semi';return'pro';}
function scorePressure({score,home=true,minute}={}){if(!score)return null;const own=Number(score[home?'home':'away']||0),opp=Number(score[home?'away':'home']||0),m=Number(minute||0);if(m>=75&&own<opp)return'Le temps commence à compter autant que l’espace.';if(m>=80&&own>opp)return'Cette fois, perdre le ballon pourrait coûter plus cher que ne pas forcer l’action.';if(m>=70&&own===opp)return'Le score donne soudain plus de poids à chaque choix.';return null;}
export function decisionNarration({minute,opponent='l’adversaire',memory={},index=0,position=null,age=null,level=null,competition=null,score=null,home=true,confidence=null,fatigue=null,coachTrust=null}={}){
 const tier=careerTier({age,level,competition}),m=Number(minute||0),pressure=scorePressure({score,home,minute:m});
 if(index===0){if(tier==='u15')return`À la ${m}e, tu reçois avec un peu d’espace. Derrière la main courante, quelqu’un crie ton prénom, mais ton regard reste sur ${opponent}.`;if(tier==='youth')return`À la ${m}e, une première fenêtre s’ouvre face à ${opponent}. Tu as juste assez de temps pour lever la tête avant que le pressing revienne.`;return`À la ${m}e, une première brèche apparaît face à ${opponent}. Le défenseur hésite entre sortir sur toi et protéger l’espace dans son dos.`;}
 if(Number(memory.defenderStress)>=.35)return`À la ${m}e, le défenseur que tu as déjà fait reculer ne sort plus franchement. Avant même ton contrôle, il protège son dos. ${pressure||'Tu sens qu’il se souvient des duels précédents.'}`;
 if(Number(memory.pressureMisses)>0)return`À la ${m}e, une nouvelle fenêtre s’ouvre. La précédente s’était refermée pendant ton hésitation ; cette fois, tu la reconnais tout de suite. ${pressure||''}`.trim();
 if(Number(memory.technicalFailures)>=2)return`À la ${m}e, l’adversaire attend ton geste. Tes deux dernières tentatives lui ont donné des indices. Pour le surprendre, il faudra changer le tempo plutôt que répéter le même mouvement.`;
 if(Number(fatigue)>=75)return`À la ${m}e, l’espace est là, mais tes jambes mettent une fraction de seconde de plus à répondre. Tu dois choisir entre forcer l’action maintenant ou garder assez de lucidité pour la suite.`;
 if(Number(confidence)>=75)return`À la ${m}e, tu demandes le ballon avant même que le partenaire lève la tête. Le duel arrive et, cette fois, tu as envie qu’il arrive.`;
 if(Number(confidence)<=35)return`À la ${m}e, le ballon revient vers toi dans une zone où tu peux faire la différence. Après les dernières actions, ton premier réflexe est pourtant de sécuriser.`;
 if(Number(coachTrust)>=75)return`À la ${m}e, tu entends le coach derrière toi : « Vas-y. » Il ne donne pas de détail. Il te laisse lire la situation.`;
 if(/gardien/i.test(String(position||'')))return`À la ${m}e, la passe en retrait arrive avec un attaquant déjà lancé vers toi. Tu as une touche pour décider si tu fixes, joues court ou allonges.`;
 if(/déf|def|latéral|lateral/i.test(String(position||'')))return`À la ${m}e, ton adversaire direct te retrouve isolé. Aucun partenaire ne peut fermer l’espace immédiatement. Ton placement sur les deux prochaines secondes décidera du duel.`;
 if(/milieu|relayeur|meneur|6|8|10/i.test(String(position||'')))return`À la ${m}e, tu reçois entre deux lignes. Un milieu revient dans ton dos pendant qu’un défenseur hésite à sortir. ${pressure||'Il y a un choix avant même le prochain contrôle.'}`;
 if(/ailier|attaquant|buteur/i.test(String(position||'')))return`À la ${m}e, ton défenseur ferme l’intérieur et te laisse quelques mètres vers la ligne. Ce n’est peut-être pas un cadeau : il attend ton premier geste.`;
 return`À la ${m}e, le match t’offre une nouvelle décision. Les actions précédentes ont déjà changé la manière dont ${opponent} réagit à tes mouvements. ${pressure||''}`.trim();
}
export default decisionNarration;
