// ui/creationController.js
// Orchestration de la création d'un joueur. Aucun rendu dashboard ici.

import { POSITIONS, CONTINENTS, ORIGINS, HEART_CLUBS, YOUTH_CLUBS_POOL, COACH_VISIONS, COACH_NAMES } from '../constants.js';

const positions = Array.isArray(POSITIONS) ? POSITIONS : Object.values(POSITIONS || {});
const continents = CONTINENTS || {};
const origins = ORIGINS || {};
const heartClubs = HEART_CLUBS || {};
const youthPool = Array.isArray(YOUTH_CLUBS_POOL) ? YOUTH_CLUBS_POOL : Object.values(YOUTH_CLUBS_POOL || {});
const coachVisions = COACH_VISIONS?.length ? COACH_VISIONS : [{ title: 'Équilibré' }];
const coachNames = COACH_NAMES?.length ? COACH_NAMES : ['Thomas Tuchel', 'Pep Guardiola'];
const escape = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

export class CreationController {
    constructor(ui) { this.ui = ui; }
    render() {
        const { currentStep, selectedData } = this.ui;
        return `<div class="career-container"><header class="career-header"><h1>⚡ Street to Pro</h1><div class="progress-bar"><div class="progress" style="width:${(currentStep / 5) * 100}%"></div></div></header><main class="career-content">${this.renderStep(currentStep, selectedData)}</main><footer class="career-footer">${currentStep > 1 ? '<button id="prev-btn" class="btn-secondary" type="button">Précédent</button>' : ''}${currentStep < 5 ? '<button id="next-btn" class="btn-primary" type="button" disabled>Suivant</button>' : '<button id="start-btn" class="btn-success" type="button" disabled>Lancer</button>'}</footer></div>`;
    }
    renderStep(step, data) {
        switch (step) {
            case 1: return `<h2>Étape 1 : Identité & Poste</h2><div class="form-group"><label for="firstname">Prénom :</label><input id="firstname" type="text" value="${escape(data.firstname)}" placeholder="ex: Kylian"></div><div class="form-group"><label for="lastname">Nom :</label><input id="lastname" type="text" value="${escape(data.lastname)}" placeholder="ex: Mbappé"></div><div class="form-group"><label>Choisis ton poste sur le terrain :</label><div class="proclubs-pitch-container"><div class="proclubs-soccer-pitch">${positions.map(position => { const id = position?.id; if (!id) return ''; const coords = this.positionCoords(id); return `<button type="button" class="proclubs-node ${data.position === id ? 'selected' : ''}" data-pos="${escape(id)}" style="top:${coords.top};left:${coords.left}" title="${escape(position?.name || id)}"><div class="proclubs-jersey">👕</div><span class="proclubs-pos-name">${escape(id)}</span></button>`; }).join('')}</div></div></div>`;
            case 2: { const selected = Object.values(origins).find(item => item?.id === data.origin); return `<h2>Étape 2 : Origine</h2><p class="subtitle">Comment avez-vous façonné votre jeu ?</p><div class="grid-origins-compact">${Object.values(origins).map(origin => origin ? `<div class="origin-card-compact ${data.origin === origin.id ? 'selected' : ''}" data-origin="${escape(origin.id)}"><div class="origin-icon-small">${this.originEmoji(origin.trait)}</div><div class="origin-info-small"><h3>${escape(origin.name)}</h3><span class="trait-tag">${escape(origin.trait)}</span></div></div>` : '').join('')}</div><div class="origin-description-box">${selected ? `<p>📖 ${escape(selected.desc || '')}</p>` : '<p class="placeholder-text">👉 Clique sur une origine pour découvrir son histoire.</p>'}</div>`; }
            case 3: { const countries = data.continent && continents[data.continent] ? (Array.isArray(continents[data.continent]) ? continents[data.continent] : Object.values(continents[data.continent])) : []; return `<h2>Étape 3 : Région & Pays</h2><div class="grid-continents">${Object.keys(continents).map(name => `<button type="button" class="chip-continent ${data.continent === name ? 'selected' : ''}" data-continent="${escape(name)}">${escape(name)}</button>`).join('')}</div>${countries.length ? `<h3>Pays :</h3><div class="grid-countries">${countries.map(country => `<button type="button" class="chip-country ${data.country === country?.name ? 'selected' : ''}" data-country="${escape(country?.name || '')}">${country?.flag || ''} ${escape(country?.name || '')}</button>`).join('')}</div>` : ''}`; }
            case 4: return `<h2>Étape 4 : Club de Cœur</h2><div class="form-group"><label for="heart-club-select">Club de cœur :</label><select id="heart-club-select"><option value="">-- Choisir un club --</option>${Object.entries(heartClubs).map(([league, clubs]) => `<optgroup label="${escape(league)}">${(Array.isArray(clubs) ? clubs : Object.values(clubs || {})).map(club => `<option value="${escape(club?.name || '')}" ${data.heartClub === club?.name ? 'selected' : ''}>${escape(club?.name || '')}</option>`).join('')}</optgroup>`).join('')}</select></div>`;
            case 5: this.prepareYouthOffers(); return `<h2>Étape 5 : Offres de Contrat Jeune</h2><p class="subtitle">Analysez les propositions et choisissez votre point de chute :</p><div class="grid-youth-clubs">${this.ui.randomYouthClubs.map(club => `<div class="card-select club-card ${data.youthClub?.name === club?.name ? 'selected' : ''}" data-club-name="${escape(club?.name || '')}"><div class="club-header-info"><h3>${escape(club?.name || '')}</h3><span class="league-tag">🏆 ${escape(club?.league || '')} (${escape(club?.country || '')})</span></div><div class="contract-details"><p><strong>👨‍💼 Entraîneur :</strong> ${escape(club?.coachName || '')} <em>(${escape(club?.coachVision || '')})</em></p><p><strong>💶 Salaire :</strong> ${club?.salary || 0} € / semaine</p><p><strong>⏱️ Temps de jeu :</strong> ${escape(club?.playtime || '')}</p><p><strong>🎯 Objectif :</strong> Atteindre ${club?.targetRating || 60} Général</p></div><div class="prestige-badge">Prestige : ${club?.prestige || 0}</div></div>`).join('')}</div>`;
            default: return '<p>Chargement...</p>';
        }
    }
    positionCoords(id) { if (id === 'GK') return { top: '86%', left: '50%' }; if (['DC','CB'].includes(id)) return { top: '70%', left: '50%' }; if (['DD','RB'].includes(id)) return { top: '65%', left: '85%' }; if (['DG','LB'].includes(id)) return { top: '65%', left: '15%' }; if (['MDC','CDM'].includes(id)) return { top: '50%', left: '50%' }; if (['MC','CM'].includes(id)) return { top: '40%', left: '50%' }; if (['MO','CAM','MOC'].includes(id)) return { top: '28%', left: '50%' }; if (['AD','RW'].includes(id)) return { top: '22%', left: '80%' }; if (['AG','LW'].includes(id)) return { top: '22%', left: '20%' }; if (['BU','ST'].includes(id)) return { top: '12%', left: '50%' }; return { top: '50%', left: '50%' }; }
    originEmoji(trait = '') { const value = String(trait).toLowerCase(); if (value.includes('technique') || value.includes('dribble')) return '✨'; if (value.includes('physique') || value.includes('force')) return '💪'; if (value.includes('mental') || value.includes('leader')) return '🧠'; if (value.includes('vitesse') || value.includes('rapide')) return '🏃‍♂️'; return '⚡'; }
    prepareYouthOffers() { if (this.ui.randomYouthClubs.length || !youthPool.length) return; const shuffled = [...youthPool].sort(() => Math.random() - 0.5); const count = Math.floor(Math.random() * 3) + 4; this.ui.randomYouthClubs = shuffled.slice(0, count).map(club => { const vision = coachVisions[Math.floor(Math.random() * coachVisions.length)]; return { ...club, coachName: coachNames[Math.floor(Math.random() * coachNames.length)], coachVision: vision?.title || 'Équilibré', salary: Math.round(100 + Math.random() * 200), playtime: ['Temps de jeu limité','Joueur de rotation','Espoir / Prêt potentiel','Titulaire en jeunes'][Math.floor(Math.random() * 4)], targetRating: Math.min(75, 55 + Math.round((club?.prestige || 50) / 4)) }; }); }
    bind() {
        const ui = this.ui, nextBtn = document.getElementById('next-btn'), prevBtn = document.getElementById('prev-btn'), startBtn = document.getElementById('start-btn');
        const refreshButtons = () => { if (nextBtn) nextBtn.disabled = !this.isValid(); if (startBtn) startBtn.disabled = !this.isValid(); };
        document.getElementById('firstname')?.addEventListener('input', event => { ui.selectedData.firstname = event.target.value.trim(); refreshButtons(); });
        document.getElementById('lastname')?.addEventListener('input', event => { ui.selectedData.lastname = event.target.value.trim(); refreshButtons(); });
        document.querySelectorAll('.proclubs-node').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.proclubs-node').forEach(item => item.classList.remove('selected')); button.classList.add('selected'); ui.selectedData.position = button.dataset.pos; refreshButtons(); }));
        document.querySelectorAll('.origin-card-compact').forEach(card => card.addEventListener('click', () => { ui.selectedData.origin = card.dataset.origin; ui.render(); }));
        document.querySelectorAll('.chip-continent').forEach(button => button.addEventListener('click', () => { ui.selectedData.continent = button.dataset.continent; ui.selectedData.country = null; ui.render(); }));
        document.querySelectorAll('.chip-country').forEach(button => button.addEventListener('click', () => { ui.selectedData.country = button.dataset.country; refreshButtons(); }));
        document.getElementById('heart-club-select')?.addEventListener('change', event => { ui.selectedData.heartClub = event.target.value; refreshButtons(); });
        document.querySelectorAll('.club-card').forEach(card => card.addEventListener('click', () => { document.querySelectorAll('.club-card').forEach(item => item.classList.remove('selected')); card.classList.add('selected'); const offer = ui.randomYouthClubs.find(item => item?.name === card.dataset.clubName); if (offer) { ui.selectedData.youthClub = offer; ui.selectedData.coachVision = offer.coachVision; ui.selectedData.coachName = offer.coachName; } refreshButtons(); }));
        nextBtn?.addEventListener('click', () => { if (ui.currentStep < 5) { ui.currentStep += 1; ui.render(); } });
        prevBtn?.addEventListener('click', () => { if (ui.currentStep > 1) { ui.currentStep -= 1; ui.render(); } });
        startBtn?.addEventListener('click', () => { if (!this.isValid()) return; const result = ui.gateway?.startCareer(ui.selectedData); if (result) { ui.activeApp = 'home'; ui.render(); } });
        refreshButtons();
    }
    isValid() { const data = this.ui.selectedData; switch (this.ui.currentStep) { case 1: return Boolean(data.firstname && data.lastname && data.position); case 2: return data.origin !== null; case 3: return Boolean(data.continent && data.country); case 4: return Boolean(data.heartClub); case 5: return Boolean(data.youthClub); default: return false; } }
}
export default CreationController;
