// Compose les beats de présentation à partir d'un plan déjà validé.

import { impactLevel } from './narrativeSignificance.js';
import { stableNarrativeId } from './narrativeFactNormalizer.js';

const n = value => Number.isFinite(Number(value)) ? Number(value) : 0;
const finite = value => Number.isFinite(Number(value)) ? Number(value) : null;

function resultView(fact = {}) { const metrics=fact.metrics||{},payload=fact.payload||{}; return {factId:fact.id,fixture:payload.fixture||{},matchIndex:metrics.matchIndex,opponent:payload.opponent||'Adversaire',competitionName:payload.competitionName||'Match',importance:payload.importance,phase:payload.phase,round:payload.round,result:fact.outcome?.result||null,teamGoals:n(metrics.teamGoals),opponentGoals:n(metrics.opponentGoals),rating:metrics.rating===null?null:n(metrics.rating),goals:n(metrics.goals),assists:n(metrics.assists),playerPlayed:metrics.playerPlayed!==false,started:metrics.started!==false,minutesPlayed:n(metrics.minutesPlayed),interactive:Boolean(metrics.interactive),appearance:payload.appearance||(metrics.started===false?'substitute':'starter')}; }
function scoreText(r){return `${n(r?.teamGoals)}-${n(r?.opponentGoals)}`;}
function stablePick(seed,key,choices=[]){if(!choices.length)return null;const text=`${seed||'narrative'}|${key||'line'}`;let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return choices[(hash>>>0)%choices.length];}
function appearanceLabel(r={}){if(r.playerPlayed===false)return r.appearance==='bench'?'Resté sur le banc':'Hors groupe';if(r.started===false)return `Entré en jeu · ${n(r.minutesPlayed)} min`;if(n(r.minutesPlayed))return `Titulaire · ${n(r.minutesPlayed)} min`;return 'Titulaire';}
function impactLabel(level){return{decisive:'Impact décisif',strong:'Impact fort',present:'Présent',difficult:'En difficulté',unused:'Non utilisé'}[level]||'Présent';}
function impactDetail(r={}){if(r.playerPlayed===false)return appearanceLabel(r);const p=[],g=n(r.goals),a=n(r.assists),rating=n(r.rating);if(g)p.push(`${g} but${g>1?'s':''}`);if(a)p.push(`${a} passe${a>1?'s':''} décisive${a>1?'s':''}`);p.push(`note ${rating.toFixed(1)}`);return p.join(' · ');}
function outcomeText(r){const o=r?.opponent||'l’adversaire';if(r?.result==='win')return `Le coup de sifflet final confirme la victoire ${scoreText(r)} face à ${o}.`;if(r?.result==='loss')return `Le match s’achève sur une défaite ${scoreText(r)} face à ${o}.`;return `Les deux équipes se quittent sur un ${scoreText(r)} face à ${o}.`;}
function goalHaulLabel(g){return{2:'un doublé',3:'un triplé',4:'un quadruplé',5:'un quintuplé',6:'un sextuplé'}[g]||`${g} buts`;}
function contributionText(r={}){const g=n(r.goals),a=n(r.assists);if(g&&a)return `${g} but${g>1?'s':''} et ${a} passe${a>1?'s':''} décisive${a>1?'s':''}`;if(g)return g===1?'un but':goalHaulLabel(g);if(a)return a===1?'une passe décisive':`${a} passes décisives`;return null;}
function performanceText(player,r){if(!r)return `Le staff ne t’a pas utilisé récemment. Ta place dans la rotation reste à gagner.`;if(r.playerPlayed===false)return r.appearance==='bench'?`Tu as suivi toute la rencontre depuis le banc, sans que ton numéro ne soit appelé.`:`Cette fois, tu n’étais pas dans le groupe retenu.`;const rating=n(r.rating),g=n(r.goals),a=n(r.assists),c=contributionText(r);if(r.started===false&&c)return `Entré en cours de match, tu as trouvé le moyen de peser${r.minutesPlayed?` en ${r.minutesPlayed} minutes`:''} : ${c}.`;if(r.started===false&&rating>=7)return `Ton entrée a donné au staff une raison de te regarder autrement.`;if(g>=2)return `Tu quittes la pelouse avec ${goalHaulLabel(g)}. Cette rencontre restera difficile à confondre avec les autres.`;if(g===1&&a>=1)return `Un but et une passe décisive : tu as directement pesé sur deux moments du match.`;if(g===1)return `Ton but donne à cette rencontre une place à part.`;if(a>=2)return `Tes ${a} passes décisives ont placé ton influence au cœur du résultat.`;if(a===1)return `Ta passe décisive a laissé une trace concrète dans le scénario.`;if(rating>=8.2)return `Sans forcément apparaître au tableau des buteurs, tu as imposé ta présence du début à la fin.`;if(rating<5.5)return `Tu quittes le terrain en sachant que cette fois, tu es passé à côté.`;return `Tu as tenu ta place dans le collectif sans geste décisif, mais sans disparaître.`;}
function blockOverviewText(results,impactMatch){if(results.length<=1)return null;const appearances=results.filter(r=>r.playerPlayed!==false).length,starts=results.filter(r=>r.playerPlayed!==false&&r.started!==false).length;if(!appearances)return `Le staff ne t’a pas utilisé sur cette séquence. La concurrence a pris de l’avance et la prochaine occasion comptera davantage.`;const opponent=impactMatch?.opponent||'un adversaire';if(appearances===results.length&&starts===appearances)return `Tu as conservé une vraie continuité dans le onze. Ton empreinte la plus nette est venue face à ${opponent}.`;if(starts===0)return `Tes minutes sont venues du banc. Tu cherches encore le match capable de modifier la hiérarchie.`;return `Ton statut a bougé entre titularisations et passages sur le banc. Face à ${opponent}, tu as laissé la trace la plus nette.`;}
function atmosphereText(r,importance){const f=r?.fixture||{};if(importance==='exceptional')return `Pendant quelques secondes, tout semble ralentir. Ce genre de match ne ressemble pas aux autres.`;if(importance==='major')return f.isDerby||f.rival||f.rivalry?`La tension retombe lentement autour du terrain. Un derby ne se termine jamais vraiment au coup de sifflet.`:`L’atmosphère reste chargée bien après la dernière action.`;if(r?.result==='win')return `Les réactions accompagnent encore les joueurs qui quittent le terrain.`;if(r?.result==='loss')return `Les bruits autour de toi paraissent plus lointains au moment de rentrer.`;return `Les joueurs se dispersent lentement pendant que le terrain retrouve son calme.`;}
function firstCareerGoalMatch(context,results=[]){const seasonGoals=finite(context?.player?.seasonStats?.goals),previousGoals=finite(context?.career?.completedGoals);if(seasonGoals===null||previousGoals===null||previousGoals!==0)return null;const played=results.filter(r=>r.playerPlayed!==false),blockGoals=played.reduce((s,r)=>s+n(r.goals),0);if(blockGoals<=0||seasonGoals!==blockGoals)return null;return played.filter(r=>n(r.goals)>0).sort((a,b)=>n(a.matchIndex)-n(b.matchIndex))[0]?.factId||null;}
function playerMindsetText(context,r,importance,{firstCareerGoal=false}={}){if(!r)return null;const seed=context?.seed,key=r.factId||`${r.opponent}:${r.matchIndex}`,morale=finite(context?.player?.mindset?.morale),rating=r.rating===null?null:n(r.rating),contribution=n(r.goals)+n(r.assists);if(firstCareerGoal)return stablePick(seed,`${key}:first`,r.result==='loss'?[`La défaite prend presque toute la place. Presque. Au milieu de la frustration, une chose reste à toi : c’était le premier.`]:[`Dans le vestiaire, une pensée revient malgré le bruit : c’était le premier. Celui-là ne se confondra jamais avec les suivants.`,`Tu peux rejouer l’action autant que tu veux : tu viens de marquer le premier but de ta carrière.`]);if(r.playerPlayed===false)return morale!==null&&morale<=35?`Regarder le match avancer sans toi laisse une question difficile à chasser : comment reprendre ta place ?`:null;if(r.started===false&&(contribution>0||rating>=7.3))return `Tu n’avais pas beaucoup de temps. Tu as réussi à exister avant même que le match ne te laisse vraiment t’installer.`;if(r.result==='loss'&&(contribution>0||rating>=7.5))return `Ta prestation tient debout. Ce soir, ça ne suffit pourtant pas à rendre la défaite plus facile.`;if(rating!==null&&rating<5.5)return `Tu sais déjà quelles actions vont revenir dans ta tête. La réponse utile commencera à la prochaine séance.`;if((importance==='major'||importance==='exceptional')&&r.result==='win'&&(contribution>0||rating>=7.8))return `Tu sens que cette soirée peut déplacer quelque chose autour de toi. Pas toute une carrière, mais peut-être le regard porté sur toi demain.`;if(morale!==null&&morale>=75&&rating>=7)return `Tu rentres avec une sensation simple : en ce moment, tu fais confiance à ton jeu.`;return null;}

export function composeNarrativeBeat(plan={},context={}){const facts=plan.facts||[],results=facts.filter(f=>f.type==='match_result').map(resultView),impactMatch=results.find(r=>r.factId===plan.anchorFactId)||results[0]||null,level=impactLevel(impactMatch),firstId=firstCareerGoalMatch(context,results),overview=blockOverviewText(results,impactMatch),mind=playerMindsetText(context,impactMatch,plan.importance,{firstCareerGoal:impactMatch?.factId===firstId});const paragraphs=[overview,impactMatch?outcomeText(impactMatch):null,impactMatch?performanceText(context.player,impactMatch):null,mind,impactMatch?atmosphereText(impactMatch,plan.importance):null].filter(Boolean);return{id:stableNarrativeId(plan.anchorFactId||context.seed||'beat'),kind:'career_beat',title:plan.title||'Ce que cette période change',text:paragraphs.join(' '),importance:plan.importance||'normal',impact:impactLabel(level),detail:impactMatch?impactDetail(impactMatch):null,factIds:facts.map(f=>f.id).filter(Boolean),anchorFactId:plan.anchorFactId||null};}
export default composeNarrativeBeat;
